---
permalink: faq/faq-insight-licensing.html
sidebar: sidebar
keywords: 
summary: 'Answers to common questions about OnCommand Insight licensing.'
---
= OnCommand Insight Licensing
:icons: font
:imagesdir: ../media/

[.lead]
Answers to common questions about OnCommand Insight licensing.

== OCI Licensing Overview

OCI is licensed by capacity. Customers must purchase a license for each module they want to enable:

*Discover* is a prerequisite for Assure, Perform, and Plan and is not offered on its own. Discover is licensed by TB of managed capacity.

*Assure* is licensed by TB of managed capacity (as a single unit of charge for all storage infrastructure: FC, NAS, iSCSI, FCoE).

*Perform* is licensed by TB of managed capacity.

*Plan* is licensed by TB of managed capacity.

"`Managed capacity`" is defined as the raw capacity of the physical disks, virtual disks, and tapes prior to formatting. This is applicable to all storage discovered by Insight, both on-premises and in the cloud.

Most data sources are looking at disk raw base 2 capacity. There is no consideration for the disk role, such as a spare disk, unassigned disk, or RAID disk.

There are two types of Insight licenses available: *Perpetual* and *Subscription*.

*Perpetual licenses* allow you to indefinitely use the specific version/release of the software obtained subject to applicable license terms. If you have purchased a Software Support Plan (SSP), NetApp provides access to commercially available software updates through the NetApp Support site when and if updates are available in accordance with its Support Services terms. NetApp also provides access to special patches as determined by the NetApp Technical Support Center.

*Subscription* is a fixed term license of software which grants the right to:

* Use the software on-premises for a limited period only (most commonly 12 months) subject to applicable license terms
* Receive Software Support (previously referred to as SSP) for the period of the term
* While in effect the Licensee may use the most current commercially available version, release, or update, should any be made available as well as receive support for the software

At the end of each fixed term (most commonly 12 months), the license may be renewed for an additional fixed term (most commonly 12 months). If the license is not renewed, Licensee will no longer have the rights to use the software, will no longer be entitled to the benefits of SSP, and Licensee must destroy all copies of the software.

== More about OCI License Modules

OCI has 4 core license modules to meet today's datacenter environment needs. These modules are *Discover, Perform, Assure and Plan*. Discover is the base module and is required for all other module purchases.

The *Discover* module enables OCI to locate the assets in the datacenter and dynamically map the device service paths. Information such as capacity, vendor information, model, firmware and serial numbers are provided.

*Perform* is OCI's performance collection module. Perform captures IOPS, throughput, latency, and CPU and memory information as well as provides other analytics.

*Assure* is positioned toward Fibre Channel environments and efficiency technologies. It helps identify and manage risks in fibre channel and iSCSI environments. Assure also helps with information on identification, mapping and alerting of masking, mapping and zoning service path entries and efficiency best practice policies such as fabric redundancy, switch hops, fan-out ratios and thin provisioning.

*Plan* provides the ability to identify and forecast trends across compute, fabric and various types of storage (cDOT, 7-mode, 3rd party) in hybrid on premise and globally-dispersed Data Center environments. It allows for longer retention times. The Data Warehouse consists of a built-in Intelligence to allow report authoring and avoids double counting of metrics in enterprise shared storage environments. It has the ability to generate and schedule a compliment of "`out of the box`" productized reports, or create your own reports using its `" drag and drop`" integrated report authoring tools.
