---
permalink: faq/faq-configuration-and-supported-devices.html
sidebar: sidebar
keywords: 
summary: 'This FAQ answers common questions about OnCommand Insight configuration and supported devices.'
---
= Configuration and Supported devices
:icons: font
:imagesdir: ../media/

[.lead]
This FAQ answers common questions about OnCommand Insight configuration and supported devices.

== Does OCI make changes to my environment?

No. OCI is a read-only tool that gathers information about your environment. OCI never makes any changes to your assets or configurations.

== What permission-level access does OCI need to my devices?

In most cases where the device supports it, a read-only access is all that is required. There are some solutions that do not permit read-only access and thus would require the appropriate elevated permissions.

== How often does OCI collect information?

OCI typically collects performance data every 5 minutes and discovery of logical and physical constructs every ½ hr. OCI sets the default polling intervals according to suggested best practices and scalability but does permit the user complete control over these intervals.

== What is OCI's impact to my Environment?

OCI's agentless, out-of-band and passive IP communications help minimize setup, maintenance and impact to the data center ecosystem. OCI's performance development team takes great measures to minimize any impact to the Data center's performance in activities of monitoring performance itself. Impact is considered negligible in normal operating environments and can be relaxed or tightened in highly utilized or underperforming technology platforms. See the OnCommand Insight Installation Guide for more information.

== How can I list all the hosts/VM's in OCI?

OCI's compliment of widgets and query-listing possibilities can be used to provide inventory style listings for Data Center assets. Listings of Virtual Machines down to the spindles and numerous constructs in between can all be made available to queries, widgets, dashboards, and data warehouse reporting, and are accessible through the RESTful API.

== Does OCI provide the same type of support for related non-hypervisor hosts (i.e. physical servers)?

Hypervisors such as VMware provide detailed information on the ESXI hosts and their associated virtual machines (VMs). For physical servers, OCI collects metrics up to the host HBA. OCI employs a unique method in which it discovers physical servers using a patent-pending technology. Once storage and/or switches are discovered, host names for physical servers are contained within the fabric alias information. OCI selects these host names, matches them in DNS, and automatically brings the hosts into OCI. This technique greatly minimizes the need for manual entry updates and tool inventory maintenance.

== Does OCI provide the same device metric depth (parity) across heterogenous environments?

There are varying degrees of standardizing, commonality and nomenclature across 3rd party platforms and vendor technologies. OCI attempts to normalize capacity and performance information into a consistent framework. Some capacity and performance metrics are provided natively from the device's counters, such as IOPs, latency and raw capacity. When counters are not provided, OCI can attempt to summarize the values (for example, by totaling the IOPs or capacities of underlying volumes), and in cases where neither is available, OCI will attempt to derive the metric values through various computational algorithms. OCI provides a generic SNMP integration capability to incorporate additional metrics not currently collected by OCI today.

== Does OCI support Fibre Channel switches?

Yes, In addition to gathering data from your storage assets, OCI also acquires Inventory and Performance data from Cisco, Brocade and QLogic switches in your environment.

== Are topology views of the whole infrastructure available? Does OCI show "`end-to-end visibility`"?

Yes, OCI dynamically discovers and maps the logical and physical constructs, providing an interactive end-to-end topology view of Compute, Fabrics, Virtualizers and back-end Storage. Topology icons allow quick launch navigation to impacted resources and aid in identification of workloads & violations in shared storage environments.
