---
permalink: faq/faq-integrating-insight-and-third-party-tools.html
sidebar: sidebar
keywords: 
summary: 'This FAQ answers common questions about integration of OnCommand Insight with other tools.'
---
= Integrating Insight with other tools
:icons: font
:imagesdir: ../media/

[.lead]
This FAQ answers common questions about integration of OnCommand Insight with other tools.

== Can OCI integrate with other tools and what integration points are available?

Yes, OCI is an extensible (wide open) solution allowing for Integrations with 3rd party orchestration, business management, change control and ticketing systems as well as custom CMDB integrations. OCI's fully published RESTful API and open MySQL database primary points of integration allow simple and effective movement of data and allow users to gain seamless access to their data.

Insight's Swagger-based API documentation is found in the product under *(?) Help > REST API Documentation*.

== What is the Insight BMC Connector?

The OnCommand Insight Connector for BMC integrates the OnCommand Insight Data Warehouse (DWH) and the BMC Atrium Configuration Management Database (CMDB). The Insight Connector for BMC maps physical and logical stored data about network storage systems (for example, storage units, host storage services, VS Storage Service, and VM Storage Service) and their relationships with devices (hosts, storage switches, and tapes) and imports them into the BMC CMDB as configuration items and relationships. You can find more information about the OnCommand Insight Connector for BMC on the NetApp Support Site.

== Does OCI work with SCOM or VROPs?

Yes, OCI complements a number of business management solutions and is considered an authoritative source for Storage, Compute, Hypervisor and Fabric information for the data center. OCI customers leverage OCI's RESTful API and Extensible MySQL database to enhance numerous applications like BMC's Remedy, ServiceNow, SCOM, Vrops, and Splunk, to name a few. OCI extends integrations by importing information from almost any source of record and/or by sending the captured environmental metrics to popular 3rd party Monitoring, Ticketing, CMDB billing & orchestration systems.

== Can OCI work with cloud services I already use or am considering using?

Yes, OCI's management of both traditional on-premise and agile hybrid cloud environments provides visibility when determining the best, most cost-effective platform for your business service's needs. OCI can be leveraged for pre- and post-migration analysis, helping identify workloads that are suitable for the cloud. Historical capacity trending, performance and cost are all necessary in order to select the appropriate cloud service. Service Design Workshops leveraging OCI's I/O density and other metrics can also help you answer questions like whether you optimized your environment and if the cloud makes sense. OCI continues to expand its coverage with support for NetApp Private Storage, Cloud ONTAP, Amazon S3 and Openstack KVM. OCI continues to play a vital role in NetApp's Cloud management campaign, especially in areas where visibility into Capacity Planning, Performance, Service Quality and Chargeback are important.

== Can OCI open incidents in our incident management solution?

Yes, OCI violation events can be triggered and sent via SNMP as a trap or via Syslog to a server, and some by RESTful API. Details contained within the provided events can be interpreted by many 3rd party incident management and ticketing solutions.

== Can you allocate resources to a business unit or departments?

Yes, OCI incorporates a method of metadata tagging called Annotations. Business Units, Lines of Business, Tenants, and Projects can be assigned to data center resources for richer business context around assets, capacity planning, troubleshooting and reporting.

== Does OCI work with Work Flow Automator (WFA)?

OCI's integration capabilities with 3rd party CMDB, Billing and Orchestration technologies are a key value to its success, and WFA is no exception. NetApp's Professional Services have performed a number of successful Integrations that exist today with WFA workflows and OCI . 

== How long are the OCI retention times for performance data?

The OCI server holds 90 days of near-real-time performance as well as the current (point in time) inventory (Logical and Physical constructs).

OCI performance polling intervals are user-configurable. Storage performance is typically configured for every 5 minutes for most vendors. Each day, performance/inventory data is sent to the OCI data warehouse (DWH) for long term historical and forecast reporting. DWH transforms this data into summarized data (Hourly, Daily, Monthly rollup data). Our ability to track "`changes`" e.g. monitored environmental history for Storage/Compute /fabric configuration/mappings, has no defined limit today.

Data Warehouse retains historical data based on the data marts and granularity of the data.

== Are there any performance planning reports?

Yes, There are several reports provided with OCI and there are many others available in our Professional Services catalog, based on use case. The Data Warehouse module also comes with a suite of Cognos report authoring tools that allow users to create their own reports. 
