---
permalink: config-admin/adding-fc-devices-manually.html
sidebar: sidebar
keywords: 
summary: 'You can manually add a Fibre Channel device to OnCommand Insight using the manual add feature available in the Device resolution FC Identify tab. This process might be used for pre-identification of a device that is expected to be discovered in the future.'
---
= Adding a Fibre Channel device manually
:icons: font
:imagesdir: ../media/

[.lead]
You can manually add a Fibre Channel device to OnCommand Insight using the manual add feature available in the Device resolution FC Identify tab. This process might be used for pre-identification of a device that is expected to be discovered in the future.

== Before you begin

To successfully add a device identification to the system you need to know the WWN or IP address and the device name.

== About this task

You can add a Host, Storage, Tape or Unknown Fibre Channel device manually.

== Steps

. Log in to the Insight web UI
. Click *Manage* > *Device resolution*
. Click the *FC Identify* tab.
. Click the add button.
+
The Add Device dialog is displayed

. Enter the WWN or IP address, the device name, and select the device type.

== Results

The device you enter is added to the list of devices in the FC Identify tab. The "`Rule`" is identified as Manual.
