---
permalink: config-admin/additional-data.html
sidebar: sidebar
keywords: landing
summary: 'Additional data can be displayed in customizable widgets on each asset page. Customizing the page for an asset applies the customization to the pages for all assets of that type.'
---
= Customizable asset page
:icons: font
:imagesdir: ../media/

[.lead]
Additional data can be displayed in customizable widgets on each asset page. Customizing the page for an asset applies the customization to the pages for all assets of that type.

You customize asset page widgets by performing the following actions:

. Add a widget to the page
. Create a query or expression for the widget to showcase desired data
. Choose a filter if desired
. Choose a rollup or grouping method
. Save the widget
. Repeat for all desired widgets
. Save the asset page

You can also add variables to the custom asset page that can be used to further refine your showcased data in widgets. In addition to regular variables, each asset type can use a set of "$this" variables to quickly identify resources directly related to the current asset, for example, all virtual machines hosted by the same hypervisor that hosts the current virtual machine.

This custom asset page is unique for each user as well as for each asset type. For example, if User A creates a custom asset page for a virtual machine, that custom page will display for any virtual machine asset page, for that user.

Users can only view, edit, or delete custom asset pages that they create.

Custom asset pages are not included in Insight's export/import functionality.
