---
permalink: config-admin/anomaly-detection-monitoring-status.html
sidebar: sidebar
keywords: 
summary: 'Anomaly detection monitoring status is available in application queries, widgets and asset pages.'
---
= Anomaly detection monitoring status
:icons: font
:imagesdir: ../media/

[.lead]
Anomaly detection monitoring status is available in application queries, widgets and asset pages.

== Anomaly detection monitoring status

For each application, you will see one of the following:

* *OK*
+
No problems are detected.

* *Learning*
+
The anomaly detection server is fetching up to 14 days of performance data, and loading it into the anomaly detection engine.

* *Exceeds maximum assets*
+
The maximum number of assets being monitored for an application has been exceeded. No more than 4000 assets can be monitored for an application. Monitoring is paused until the number of assets is less than or equal to 4000. Reduce the number of assets being monitored to continue monitoring.

* *Failed*
+
The connection to the anomaly detection server has failed.

* *Not monitored*
+
Monitoring is turned off for the application. In queries and widgets, this field is left blank.
