---
permalink: config-admin/applying-a-data-source-patch.html
sidebar: sidebar
keywords: 
summary: 'Data source patches are periodically available and enable you to fix issues with an existing data source, add a data source for a new vendor, or add a new model for a vendor.'
---
= Applying a data source patch
:icons: font
:imagesdir: ../media/

[.lead]
Data source patches are periodically available and enable you to fix issues with an existing data source, add a data source for a new vendor, or add a new model for a vendor.

== Before you begin

You must have obtained the `.zip` file that contains the latest data source `.patch` files from technical support.

== Steps

. On the Insight toolbar, click *Admin*.
. Click *Patches*.
. From the Actions button, select *Apply patch*.
. In the *Apply data source patch* dialog box, click *Browse* to locate the `.patch` file.
. Inspect the *Patch name*, *Description*, and *Impacted data source types*.
. If the selected patch is correct, click *Apply Patch*.
+
If you are applying a patch that fixes issues with a data source, all data sources of the same type are updated with the patch and you must approve the patch. Patches that do not affect any configured data sources are automatically approved.

== After you finish

If you are applying a patch that adds a data source for a new vendor or a new model, you must add the data source after applying the patch.
