---
permalink: config-admin/asset-pages.html
sidebar: sidebar
keywords: 
summary: 'Asset pages provide performance troubleshooting data and present summary information about a base asset \(such as a virtual machine or a volume\) and the related assets it uses \(such as storage pools, storage nodes, and connected switch ports\), with links to additional information.'
---
= Asset page data
:icons: font
:imagesdir: ../media/

[.lead]
Asset pages provide performance troubleshooting data and present summary information about a base asset (such as a virtual machine or a volume) and the related assets it uses (such as storage pools, storage nodes, and connected switch ports), with links to additional information.

Beginning with OnCommand Insight 7.3.1, all asset pages have a *Main* page and an *Additional data* page. On the Main page are a summary of the asset and different sections for charts, topology and other information. The *Additional data* page allows you to configure a customizable dashboard page for the current asset type.

A solid red circle next to a line or message on the asset page main tab indicates potential issues with the monitored environment.
