---
permalink: config-admin/cdot-landing-page-terminology-storage.html
sidebar: sidebar
keywords: 
summary: 'Terms applying to objects or references that you might find on NetApp Clustered Data ONTAP storage asset landing pages.'
---
= Clustered Data ONTAP Storage
:icons: font
:imagesdir: ../media/

[.lead]
Terms applying to objects or references that you might find on NetApp Clustered Data ONTAP storage asset landing pages.

== Clustered Data ONTAP Storage Terminology

The following terms apply to objects or references that you might find on NetApp Clustered Data ONTAP storage asset landing pages. Many of these terms apply to other data collectors as well.

* Model -- A comma delimited list of the unique, discrete node model names within this cluster. If all the nodes in the clusters are the same model type, just one model name will appear.
* Vendor -- same Vendor name you would see if you were configuring a new data source.
* Serial number -- The array serial number. On cluster architecture storage systems like NetApp Clustered Data Ontap, this serial number may be less useful than the individual "`Storage Nodes`" serial numbers.
* IP -- generally will be the IP(s) or hostname(s) as configured in the data source.
* Microcode version -- firmware.
* Raw Capacity -- base 2 summation of all the physical disks in the system, regardless of their role.
* Latency -- a representation of what the host facing workloads are experiencing, across both reads and writes. Ideally, OCI is sourcing this value directly, but this is often not the case. In lieu of the array offering this up, OCI is generally performing an IOPs-weighted calculation derived from the individual internal volumes`' statistics.
* Throughput -- aggregated from internal volumes.
* Management -- this may contain a hyperlink for the management interface of the device. Created programmatically by the Insight data source as part of inventory reporting.
