---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html
sidebar: sidebar
keywords: 
summary: 'Security policies might require you to change the passwords in your OnCommand Insight environment. Some of the passwords on one server exist on a different server in the environment, requiring that you change the password on both servers. For example, when you change the “inventory” user password on the Insight Server you must match the “inventory” user password on the Data Warehouse server Connector configured for that Insight Server.'
---
= Changing OnCommand Insight internal user passwords
:icons: font
:imagesdir: ../media/

[.lead]
Security policies might require you to change the passwords in your OnCommand Insight environment. Some of the passwords on one server exist on a different server in the environment, requiring that you change the password on both servers. For example, when you change the "`inventory`" user password on the Insight Server you must match the "`inventory`" user password on the Data Warehouse server Connector configured for that Insight Server.

== Before you begin

[NOTE]
====
You should understand the dependencies of the user accounts before you change passwords. Failing to update passwords on all required servers will result in communication failures between the Insight components.
====

== About this task

The following table lists the internal user passwords for the Insight Server and lists the Insight components that have dependent passwords that need to match the new password.

|===
| Insight Server Passwords| Required changes
a|
_internal
a|
 
a|
acquisition
a|
LAU, RAU
a|
dwh_internal
a|
Data Warehouse
a|
hosts
a|
 
a|
inventory
a|
Data Warehouse
a|
root
a|
 
|===
The following table lists the internal user passwords for the Data Warehouse and lists the Insight components that have dependent passwords that need to match the new password.

|===
| Data Warehouse Passwords| Required changes
a|
cognos_admin
a|
 
a|
dwh
a|
 
a|
dwh_internal (Changed using the Server Connector configuration UI)
a|
Insight server
a|
dwhuser
a|
 
a|
hosts
a|
 
a|
inventory (Changed using the Server Connector configuration UI)
a|
Insight server
a|
root
a|
 
|===
*Changing passwords in the DWH Server Connection Configuration UI*

The following table lists the user password for the LAU and lists the Insight components that have dependent passwords that need to match the new password.

|===
| LAU Passwords| Required changes
a|
acquisition
a|
Insight Server, RAU
|===
