---
permalink: config-admin/changing-user-passwords.html
sidebar: sidebar
keywords: 
summary: 'A user with administrator privileges can change the password for any OnCommand Insight user account defined on the local server.'
---
= Changing user passwords
:icons: font
:imagesdir: ../media/

[.lead]
A user with administrator privileges can change the password for any OnCommand Insight user account defined on the local server.

== Before you begin

The following items must have been completed:

* Notifications to anyone who logs into the user account you are modifying.
* New password to be used after this change.

== About this task

When using this method, you cannot change the password for a user who is validated through LDAP.

== Steps

. Log in with administrator privileges.
. On the Insight toolbar, click *Admin*.
. Click *Setup*.
. Click the *Users* tab.
. Locate the row that displays the user account you want to modify.
. To the right of the user information, click *Edit user account*.
. Enter the new *Password* and then enter it again in the verification field.
. Click *Save*.
