---
permalink: config-admin/cisco-fc-switch-firmware-snmp-data-source.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight uses the Cisco FC Switch Firmware 2.0+ \(SNMP\) data source to discover inventory for Cisco MDS Fibre Channel switches as well as a variety of Cisco Nexus FCoE switches on which the FC service is enabled. Additionally, you can discover many models of Cisco devices running in NPV mode with this data source.'
---
= Cisco FC Switch Firmware (SNMP) data source
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight uses the Cisco FC Switch Firmware 2.0+ (SNMP) data source to discover inventory for Cisco MDS Fibre Channel switches as well as a variety of Cisco Nexus FCoE switches on which the FC service is enabled. Additionally, you can discover many models of Cisco devices running in NPV mode with this data source.

== Terminology

OnCommand Insight acquires the following inventory information from the Cisco FC Switch data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Switch
a|
Switch
a|
Port
a|
Port
a|
VSAN
a|
Fabric
a|
Zone
a|
Zone
a|
Logical Switch
a|
Logical Switch
a|
Name Server Entry
a|
Name Server Entry
a|
Inter-VSAN Routing (IVR) Zone
a|
IVR Zone
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* An IP address of one switch in the fabric or individual switches
* Chassis discovery, to enable fabric discovery
* If using SNMP V2, read-only community string
* Port 161 is used to access the device
* Access validation using the `snmpwalk` utility to the switch (see `<install_path\>\bin\`)

== Configuration

|===
| Field| Description
a|
Cisco Switch IP
a|
IP address or fully-qualified domain name of the switch
a|
SNMP Version
a|
SNMP version v2 or later is required for performance acquisition
a|
SNMP Community String
a|
SNMP read-only community string used to access the switch (not applicable for SNMP v3)
a|
User Name
a|
User name for the switch (SNMP v3 only)
a|
Password
a|
Password used for the switch (SNMPv3 only)
|===

== Advanced configuration

|===
| Field| Description
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 40 minutes)
a|
SNMP Auth Protocol
a|
SNMP authentication protocol (SNMPv3 only)
a|
SNMP Privacy Protocol
a|
SNMP privacy protocol (SNMPv3 only)
a|
SNMP Privacy Password
a|
SNMP privacy password
a|
SNMP Retries
a|
Number of SNMP retry attempts
a|
SNMP Timeout (ms)
a|
SNMP timeout (default 5000 ms)
a|
Enable Trapping
a|
Select to enable trapping. If you enable trapping, you must also activate SNMP notifications.
a|
Minimum Time Between Traps (sec)
a|
Minimum time between acquisition attempts triggered by traps (default 10 seconds)
a|
Discover All Fabric Switches
a|
Select to discover all switches in the fabric
a|
Exclude Devices
a|
Comma-separated list of device IPs to exclude from polling
a|
Include Devices
a|
Comma-separated list of device IPs to include in polling
a|
Check Device Type
a|
Select to accept only those devices that explicitly advertise themselves as Cisco devices
a|
Primary Alias Type
a|
Provide a first preference for resolution of the alias. Choose from the following:

* *Device Alias*
+
This is a user-friendly name for a port WWN (pWWN) that can be used in all configuration commands, as required. All switches in the Cisco MDS 9000 Family support Distributed Device Alias Services (device aliases).

* *None*
+
Do not report any alias

* *Port Description*
+
A description to help identify the port in a list of ports

* *Zone Alias (all)*
+
A user-friendly name for a port that can be used only for zoning configuration

* *Zone Alias (only active)*
+
A user-friendly name for a port that can be used only for the active configuration. This is the default.

a|
Secondary Alias Type
a|
Provide a second preference for resolution of the alias
a|
Tertiary Alias Type
a|
Provide a third preference for resolution of the alias
a|
Enable SANTap Proxy Mode Support
a|
Select if your Cisco switch is using SANTap in proxy mode. If you are using EMC RecoverPoint, then you are probably using SANTap.
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 300 seconds)
|===
