---
permalink: config-admin/cognos-configuration-for-smart-card-and-certificate-login-7-3-10-and-later.html
sidebar: sidebar
keywords: 
summary: 'You must modify the OnCommand Insight Data Warehouse configuration to support Smart Card \(CAC\) and certificate logins for the Cognos server.'
---
= Configuring Cognos for Smart Card and certificate login (OnCommand Insight 7.3.10 and later)
:icons: font
:imagesdir: ../media/

[.lead]
You must modify the OnCommand Insight Data Warehouse configuration to support Smart Card (CAC) and certificate logins for the Cognos server.

== Before you begin

This procedure is for systems running OnCommand Insight 7.3.10 and later.

[NOTE]
====
For the most up to date CAC and Certificate instructions, see the following Knowledgebase articles (Support login required):

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight[How to configure Common Access Card (CAC) authentication for OnCommand Insight]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse[How to configure Common Access Card (CAC) authentication for OnCommand Insight Data Warehouse]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X[How to create and import a Certificate Authority (CA) signed certificate into OnComand Insight and OnCommand Insight Data Warehouse 7.3.x]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host[How to create a Self Signed Certificate within OnCommand Insight 7.3.X installed on a Windows Host]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later[How to import a Cognos Certificate Authority (CA) signed certificate into OnCommand DataWarehouse 7.3.3 and later]

====

== Steps

. Add certificate authorities (CAs) to the Cognos trustore.
 .. In a command window, go to `..\SANscreen\cognos\analytics\configuration\certs\`
 .. Use the `keytool` utility to list the trusted CAs: `..\..\ibm-jre\jre\bin\keytool.exe -list -keystore CAMKeystore.jks -storepass NoPassWordSet`
+
The first word in each line indicates the CA alias.

 .. If no suitable files exist, supply a CA certificate file, usually a `.pem` file.
 .. To include customer's CAs with OnCommand Insight trusted CAs, go to `..\SANscreen\cognos\analytics\configuration\certs\`.
 .. Use the `keytool` utility to import the `.pem` file: `..\..\ibm-jre\jre\bin\keytool.exe -importcert -keystore CAMKeystore.jks -alias my_alias -file 'path/to/my.pem' -v -trustcacerts`
+
`my_alias` is usually an alias that would easily identify the CA in the``keytool -list`` operation.

 .. When prompted for a password, enter `NoPassWordSet`.
 .. Answer `yes` when prompted to trust the certificate.
. To enable CAC mode, do the following:
 .. Configure CAC logout page, using the following steps:
  *** Logon to Cognos portal (user must be part of System Administrators group i.e. cognos_admin)
  *** (Only for 7.3.10 and 7.3.11) Click Manage \-> Configuration \-> System \-> Security
  *** (Only for 7.3.10 and 7.3.11) Enter cacLogout.html against Logout Redirect URL \-> Apply
  *** Close browser.
 .. Execute `..\SANscreen\bin\cognos_cac\enableCognosCAC.bat`
 .. Start IBM Cognos service. Wait for Cognos service to start.
. To disable CAC mode, do the following:
 .. Execute `..\SANscreen\bin\cognos_cac\disableCognosCAC.bat`
 .. Start IBM Cognos service. Wait for Cognos service to start.
 .. (Only for 7.3.10 and 7.3.11) Unconfigure CAC logout page, using the following steps:
  *** Logon to Cognos portal (user must be part of System Administrators group i.e. cognos_admin)
  *** Click Manage \-> Configuration \-> System \-> Security
  *** Enter cacLogout.html against Logout Redirect URL \-> Apply
  *** Close browser.
