---
permalink: config-admin/concept_performance_data_archiving.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.3 introduces the ability to archive performance data on a daily basis. This supplements configuration and limited performance data backups.'
---
= Performance data archiving
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight 7.3 introduces the ability to archive performance data on a daily basis. This supplements configuration and limited performance data backups.

OnCommand Insight retains up to 90 days of performance and violation data. However, when creating a backup of that data, only the most recent information is included in the backup. Archiving allows you to save the remainder of your performance data and load it as necessary.

Once the archive location is configured and archiving is activated, once a day Insight will archive the previous day's performance data for all objects into the archive location. Each day's archive is kept in the archive folder in a separate file. Archiving happens in the background and will continue as long as Insight is running.

The most recent 90 days of archives are retained; archive files older than 90 days are deleted as newer ones are created.
