---
permalink: config-admin/concept_about_oncommand_insight_anomaly_detection.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight contains machine-learning anomaly detection analytics which provide visibility into an application’s infrastructure and identifies performance anomalies before they become service disruptions.'
---
= How OnCommand Insight anomaly detection works
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight contains machine-learning anomaly detection analytics which provide visibility into an application's infrastructure and identifies performance anomalies before they become service disruptions.

Anomaly analysis helps you identify the normal operating workload range for an application and informs when changes in performance are outside of expected levels. The application anomaly detection engine ingests performance metrics collected by Insight and identifies anomalies in the application infrastructure.

You can use anomaly detection to perform these tasks:

* Identify significant changes in the application infrastructure behavior
* Track an application through the entire stack and across multiple counters
* Diagnose the cause of periodically recurring events in an application workload
* Provide a more comprehensive set of information compared to data from performance counters using static threshold values
* Monitor in an improved reactive mode, with an end-to-end view of the topology and the ability to focus on the most anomalous behaviors.

The anomaly detection engine uses Insight data for application analysis. When monitoring is first started, up to 14 days of historical performance data can be ingested by the analysis engine. Data is collected for weeks or even months, providing more accurate data about a given resource. The data includes totals for the following counters:

|===
| Objects| Counter
a|
VM
a|
Latency, IOPS
a|
Hypervisor
a|
CPU utilization, IOPS
a|
Edge port
a|
BB credit zero
a|
Storage Node
a|
Latency, utilization, IOPS
a|
Volume
a|
Latency, IOPS
a|
Internal volume
a|
Latency, IOPS
a|
Storage pool
a|
IOPS, utilization
|===
Data collected by the anomaly detection engine is archived when Performance Data Archiving is enabled on the Insight server. See the System Health page to determine if archiving is enabled.

The anomaly detection engine is runs on a separate server than the Insight server. It can be configured on a physical machine or a VM. See the OnCommand Insight Installation Guide for Windows or Linux for more information.
