---
permalink: config-admin/configuring-anomaly-detection-for-applications.html
sidebar: sidebar
keywords: 
summary: 'You must turn on anomaly detection in order to monitor an application’s infrastructure for abnormal behavior. Anomaly detection monitoring is turned on or off for applications only.'
---
= Configuring applications for anomaly detection
:icons: font
:imagesdir: ../media/

[.lead]
You must turn on anomaly detection in order to monitor an application's infrastructure for abnormal behavior. Anomaly detection monitoring is turned on or off for applications only.

== Before you begin

* You must have installed and configured the anomaly detection engine.
* You must have assigned an application to the compute resource (virtual machine or host) for any assets for which you want anomaly detection information. Insight discovers the rest of the resources automatically.

== Steps

. Log in to the OnCommand Insightweb UI.
. Click *Manage* and select *Applications*.
. Locate the application assigned to the compute resource.
. In the *Anomalies* section, ensure that the *Monitor* control box in the upper right of the section shows *ON* rather than *OFF*; if not, click anywhere in the *Monitor* control box to switch the control to *ON*.
+
You are able to concurrently monitor up to 48 applications for anomalies.
+
The status in the section displays "`Learning`" for at least an hour; the anomaly detection engine preloads up to 14 days of any existing performance data so the engine can learn the behavior of your environment. After the Insight server performs the first poll of your environment's assets, the anomaly detection engine calculates and returns a score for the application within that time.

*Related information*

link:assigning-applications-to-assets.md#[Assigning applications to assets]
