---
permalink: config-admin/creating-rules-for-your-environment.html
sidebar: sidebar
keywords: 
summary: 'Using rules to identify devices in your environment is typically an iterative process that requires a thorough analysis of your environment and the creation of multiple rules to identify as many devices as possible. The best case scenario is to set a goal to identify 100% of the devices in your environment.'
---
= Planning device resolution rules for your environment
:icons: font
:imagesdir: ../media/

[.lead]
Using rules to identify devices in your environment is typically an iterative process that requires a thorough analysis of your environment and the creation of multiple rules to identify as many devices as possible. The best case scenario is to set a goal to identify 100% of the devices in your environment.

The most efficient order for rules is to place the most restrictive rules first, resulting in most entries not pattern matching, with the process proceeding to less restrictive rules. This allows Insight to apply more patterns to each entry increasing the possibility of patterns matching and of positive host identification.

When you create rules, your objective should be to create rules that address the largest number of unidentified devices possible. For example, creating rules that follow a pattern of coverage similar to the following is far more efficient that creating 30 rules with lower percentages of coverage:

|===
| Rule| Percentage of coverage
a|
Rule 1
a|
60%
a|
Rule 2
a|
25%
a|
Rule 3
a|
8%
a|
Rule 4
a|
4%
a|
Rule 5
a|
1%
|===
