---
permalink: config-admin/email-configuration-prerequisites.html
sidebar: sidebar
keywords: 
summary: 'Before you can configure OnCommand Insight to access your email system, you need to discover the host name or IP address to identify the \(SMTP or Exchange\) mail server and allocate an email account for OnCommand Insight reports.'
---
= Email configuration prerequisites
:icons: font
:imagesdir: ../media/

[.lead]
Before you can configure OnCommand Insight to access your email system, you need to discover the host name or IP address to identify the (SMTP or Exchange) mail server and allocate an email account for OnCommand Insight reports.

Ask your email administrator to create an email account for OnCommand Insight. You will need the following information:

* The host name or IP address to identify the (SMTP or Exchange) mail server used by your organization. You can find this information through the application you use to read your email. In Microsoft Outlook, for example, you can find the name of the server by viewing your account configuration: Tools - E-mail accounts - View or change existing email account.
* Name of email account through which OnCommand Insight will send regular reports. The account must be a valid email address in your organization. (Most mail systems will not send messages unless they are sent from a valid user.) If the email server requires a user name and password in order to send mail, obtain this information from your system administrator.
