---
permalink: config-admin/fujitsu-eternus-data-source.html
sidebar: sidebar
keywords: 
summary: 'The Fujitsu Eternus data source requires the IP address of the storage. It cannot be comma delimited.'
---
= Fujitsu Eternus data source
:icons: font
:imagesdir: ../media/

[.lead]
The Fujitsu Eternus data source requires the IP address of the storage. It cannot be comma delimited.

== Terminology

OnCommand Insight acquires the following inventory information from the Fujitsu Eternus data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Disk
a|
Disk
a|
Storage
a|
Storage
a|
Thin Pool, Flexible Tier Pool,

Raid Group

a|
Storage Pool
a|
Standard Volume, Snap Data Volume (SDV),

Snap Data Pool Volume (SDPV),

Thin Provisioning Volume (TPV)

a|
Volume
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* An IP address of the Eternus storage, which cannot be comma delimited
* SSH Administration-level user name and password
* Port 22
* Ensure that the page scroll is disabled. (clienv-show-more-scroll disable)

== Configuration

|===
| Field| Description
a|
IP Address of Eternus Storage
a|
IP address of the Eternus storage
a|
User Name
a|
User name for Eternus storage
a|
Password
a|
Password used for the sternus
|===

== Advanced configuration

|===
| Field| Description
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 20 minutes)
a|
SSH Process Wait Timeout (sec)
a|
SSH process timeout (default 600 seconds)
|===
