---
permalink: config-admin/hds-landing-page-terminology-storage-pool.html
sidebar: sidebar
keywords: 
summary: 'Terms applying to objects or references that you might find on HDS storage pool asset landing pages.'
---
= HDS Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
Terms applying to objects or references that you might find on HDS storage pool asset landing pages.

== HDS Storage Pool Terminology

The following terms apply to objects or references that you might find on HDS storage pool asset landing pages. Many of these terms apply to other data collectors as well.

* Type: The value here will be one of:
 ** RESERVED -- if this pool is dedicated for purposes other than data volumes, i.e, journaling, snapshots
 ** Thin Provisioning -- if this is a HDP pool
 ** Raid Group -- you will not likely see these for a few reasons:
+
OCI takes a strong stance to avoid double counting capacity at all costs. On HDS, one typically needs to build Raid Groups from disks, create pool volumes on those Raid Groups, and construct pools (often HDP, but could be special purpose) from those pool volumes. If OCI reported both the underlying Raid Groups as is, as well as the Pools, the sum of their raw capacity would vastly exceed the sum of the disks.
+
Instead, OCI's HDS HiCommand data collector arbitrarily shrinks the size of Raid Groups by the capacity of pool volumes. This may result in OCI not reporting the Raid Group at all. Additionally, any resulting Raid Groups are flagged in a way such that they are not visible in the OCI WebUI, but they do flow into the OCI Data Warehouse (DWH). The purpose of these decisions is to avoid UI clutter for things that most users do not care about -- if your HDS array has Raid Groups with 50MB free, you probably cannot use that free space for any meaningful outcome.
* Node - N/A, as HDS pools are not tied to any one specific node
* Redundancy - the RAID level of the pool. Possibly multiple values for a HDP pool comprised of multiple RAID types
* Capacity % - the percent used of the pool for data usage, with the used GB and total logical GB size of the pool
* Over-committed Capacity - a derived value, stating "`the logical capacity of this pool is oversubscribed by this percentage by virtue of the sum of the logical volumes exceeding the logical capacity of the pool by this percentage`"
* Snapshot - shows the capacity reserved for snapshot usage on this pool
