---
permalink: config-admin/importing-annotation-values.html
sidebar: sidebar
keywords: 
summary: 'If you maintain annotations on SAN objects \(such as storage, hosts, and virtual machines\) in a CSV file, you can import that information into OnCommand Insight. You can import applications, business entities, or annotations such as tier and building.'
---
= Importing annotation values
:icons: font
:imagesdir: ../media/

[.lead]
If you maintain annotations on SAN objects (such as storage, hosts, and virtual machines) in a CSV file, you can import that information into OnCommand Insight. You can import applications, business entities, or annotations such as tier and building.

== About this task

The following rules apply:

* If an annotation value is empty, that annotation is removed from the object.
* When annotating volumes or internal volumes, the object name is a combination of storage name and volume name using the dash and arrow (\->) separator:
+
----
<storage_name>-><volume_name>
----

* When storage, switches, or ports are annotated, the Application column is ignored.
* The columns of Tenant, Line_of_Business, Business_Unit, and Project make up a business entity.
+
Any of the values can be left empty. If an application is already related with a business entity different from the input values, the application is assigned to the new business entity.

The following object types and keys are supported in the import utility:

|===
| Type| Key
a|
Host
a|
`+id-><id>+` or `<Name>` or `<IP>`
a|
VM
a|
`+id-><id>+` or `<Name>`
a|
Storage pool
a|
`+id-><id>+` or `<Storage_name>`\->``<Storage_Pool_name>``
a|
Internal volume
a|
`+id-><id>+` or `<Storage_name>`\->``<Internal_volume_name>``
a|
Volume
a|
`+id-><id>+` or `<Storage_name>`\->``<Volume_name>``
a|
Storage
a|
`+id-><id>+` or `<Name>` or `<IP>`
a|
Switch
a|
`+id-><id>+` or `<Name>` or `<IP>`
a|
Port
a|
`+id-><id>+` or `<WWN>`
a|
Share
a|
`+id-><id>+` or `+<Storage Name>-><Internal Volume Name>-><Share Name>-><Protocol>+` [`+-><Qtree Name >+`]`<Qtree>` is optional if there is a default qtree.

a|
Qtree
a|
`+id-><id>+` or `+<Storage Name>-><Internal Volume Name>-><Qtree Name>+`
|===
The CSV file should use the following format:

----
, , <Annotation Type> [, <Annotation Type> ...]
[, Application] [, Tenant] [, Line_Of_Business] [,
Business_Unit] [, Project]

<Object Type Value 1>, <Object Key 1>, <Annotation Value> [,
<Annotation Value> ...] [, <Application>] [, <Tenant>] [,
<Line_Of_Business>] [, <Business_Unit>] [, <Project>]

...

<Object Type Value N>, <Object Key N>, <Annotation Value> [,
<Annotation Value> ...] [, <Application>] [, <Tenant>] [,
<Line_Of_Business>] [, <Business_Unit>] [, <Project>]
----

== Steps

. Log in to the Insight web UI.
. Click *Admin* and select *Troubleshooting*.
+
The Troubleshooting page displays.

. In the *Other tasks section* of the page, click the *OnCommand Insight Portal* link.
. Click *Insight Connect API*.
. Log in to the portal.
. Click *Annotation Import Utility*.
. Save the `.zip` file, unzip it, and read the `readme.txt` file for additional information and samples.
. Place the CSV file in same folder as the `.zip` file.
. In the command line window, enter the following:
+
----
java -jar rest-import-utility.jar [-uusername] [-ppassword]
[-aserver name or IP address] [-bbatch size] [-ccase sensitive:true/false]
[-lextra logging:true/false] csv filename
----
+
The -l option, which enables extra logging, and the -c option, which enables case sensitivity, are set to false by default. Therefore, you must specify them only when you want to use the features.
+
[NOTE]
====
There are no spaces between the options and their values.
====
+
[NOTE]
====
The following keywords are reserved and prevent users from specifying them as annotation names:
    -   Application
    -   Application_Priority
    -   Tenant
    -   Line_Of_Business
    -   Business_Unit
    -   Project
    Errors are generated if you attempt to import an annotation type using one of the reserved keywords. If you have created annotation names using these keywords, you must modify them so that the import utility tool can work correctly.
+
====

NOTE: The Annotation Import utility requires Java 8 or Java 11. Ensure that one of those is installed prior to running the import utility. It is recommended to use the latest OpenJDK 11.

