---
permalink: config-admin/importing-fc-identification-from-a-csv-file.html
sidebar: sidebar
keywords: 
summary: 'You can manually import Fibre Channel device identification into OnCommand Insight Device Resolution feature using a list of devices in a CSV file.'
---
= Importing Fibre Channel device identification from a CSV file
:icons: font
:imagesdir: ../media/

[.lead]
You can manually import Fibre Channel device identification into OnCommand Insight Device Resolution feature using a list of devices in a CSV file.

== Before you begin

You must have a correctly formatted CSV file in order to import device identifications directly into the Device Resolution feature. The CSV file for Fibre Channel devices requires the following information:

|===
a|
WWN
a|
IP
a|
Name
a|
Type
|===

[NOTE]
====
As a best practice, it is recommended to first export the FC Identify information to a CSV file, make your desired changes in that file, and then import the file back into FC Identify. This ensures that the expected columns are present and in the proper order.
====

To import FC Identify information:

== Steps

. Log into the Insight web UI.
. Click *Manage* > *Device Resolution*
. Select the *FC identify* tab.
. Click *Identify* > *Identify from file*
. {blank}
 .. Navigate to the folder containing your CSV files for import and select the desired file.

+
The devices you enter are added to the list of devices in the FC Identify tab. The "`Rule`" is identified as "`Manual`".
