---
permalink: config-admin/managing-security-on-the-data-warehouse.html
sidebar: sidebar
keywords: 
summary: 'The securityadmin tool allows you to manage security options on the Data Warehouse server. Security management includes updating internal passwords for internal users on the DWH server, creating backups of the security configuration, or restoring configurations to the default settings.'
---
= Managing security on the Data Warehouse
:icons: font
:imagesdir: ../media/

[.lead]
The `securityadmin` tool allows you to manage security options on the Data Warehouse server. Security management includes updating internal passwords for internal users on the DWH server, creating backups of the security configuration, or restoring configurations to the default settings.

== About this task

You use the `securityadmin` tool to manage security:

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`

== Steps

. Perform a remote login to the Data Warehouse server.
. Start the security admin tool in interactive mode: `Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i`
+
The system requests login credentials.

. Enter the user name and password for an account with "`Admin`" credentials.
+
The system displays the security admin menu for the Data Warehouse:

 ** *Backup*
+
Creates a backup zip file of the vault containing all passwords and keys and places the file in a location specified by the user, or in the default location:

  *** Windows - `C:\Program Files\SANscreen\backup\vault`
  *** Linux - `/var/log/netapp/oci/backup/vault`

 ** *Restore*
+
Restores the zip backup of the vault that was created. Once restored, all passwords and keys are reverted to values existing at the time of the backup creation.
+
[NOTE]
====
Restore can be used to synchronize passwords and keys on multiple servers, for example:
        -   Change encryption keys on one server
        -   Create a backup of the vault
        -   Restore the vault backup to the second server
====

 ** *Change encryption keys*
+
Change the DWH encryption key used to encrypt or decrypt passwords such as connector passwords and SMPT passwords.

 ** *Update Password*
+
Change password for a specific user account.

  *** _internal
  *** acquisition
  *** cognos_admin
  *** dwh
  *** dwh_internal
  *** dwhuser
  *** hosts
  *** inventory
  *** root

+
[NOTE]
====
When you change the dwhuser, hosts, inventory, or root passwords, you have the option to use SHA-256 password hashing. This options requires that all clients accessing the accounts use SSL connections.
====

 ** *Reset to Defaults*
+
Resets encryption keys and passwords to default values. Default values are those provided during installation.

 ** *Exit*
+
Exit the `securityadmin` tool.
