---
permalink: config-admin/netapp-host-and-vm-filesystems-data-source.html
sidebar: sidebar
keywords: 
summary: 'You can use the NetApp Host and VM File Systems data source to retrieve file system details and storage resource mappings for all Microsoft Windows host and VM \(virtual machine\) file systems and for all supported Linux VMs \(those that are virtually mapped only\) existing in the Insight server that are annotated with the configured Compute Resource Group \(CRG\).'
---
= NetApp Host and VM File Systems data source
:icons: font
:imagesdir: ../media/

[.lead]
You can use the NetApp Host and VM File Systems data source to retrieve file system details and storage resource mappings for all Microsoft Windows host and VM (virtual machine) file systems and for all supported Linux VMs (those that are virtually mapped only) existing in the Insight server that are annotated with the configured Compute Resource Group (CRG).

== General Requirements

* This feature must be purchased separately.
+
You can contact your Insight representative for assistance.

* You should check the Insight support matrix to verify that your host or virtual machine operating system is supported.
+
To verify that links from file systems to storage resources are created, check that the relevant storage or virtualization vendor type and version report the volume or virtual disk identification data required.

== Microsoft Windows Requirements

* This data source uses Window Management Instrumentation (WMI) data structures to retrieve data.
+
This service must be operational and available remotely. In particular, port 135 must be accessible and must be opened if behind a firewall.

* Windows domain users must have the appropriate permissions to access WMI structures.
* Administrator permissions are required.
* Dynamic TCP ports assigned 1024-65535 for Windows 2003 and older
* Ports 49152--65535 for Windows 2008

[NOTE]
====
As a general rule, when trying to use a firewall between Insight, an AU, and this data source, you should consult with your Microsoft team to identify the ports they believe will be required.
====

== Linux Requirements

* This data source uses a Secure Shell (SSH) connection to execute commands on Linux VMs.
+
The SSH service must be operational and available remotely. In particular, port 22 must be accessible and must be opened if behind a firewall.

* SSH users must have sudo permissions to execute read-only commands on Linux VMs.
+
You must use the same password to log in to SSH and to answer any sudo password challenge.

== Usage Recommendations

* You should annotate a group of hosts and virtual machines that have common operating system credentials using the same Compute Resource Group annotation.
+
Each group has an instance of this data source discovering file system details from those hosts and virtual machines.

* If you have an instance of this data source for which the success rate is low (for example, OnCommand Insight is discovering file system details for only 50 of 1000 hosts and virtual machines in a group), you should move the hosts and virtual machines for which discovery is successful into a separate Compute Resource Group.

== Configuration

|===
| Field| Description
a|
User Name
a|
Operating system user with appropriate rights to retrieve file system data For Windows operating system users, this must include the domain prefix.

a|
Password
a|
Password for the operating system user
a|
Compute Resource Group
a|
Annotation value used to flag host and virtual machines for the data source discovers file systems.A blank value indicates that the data source discovers file systems for all hosts and virtual machines not currently annotated with any Compute Resource Group.

|===

== Advanced configuration

|===
| Field| Description
a|
Inventory poll interval (min)
a|
Interval between inventory polls (default 360 minutes)
|===
