---
permalink: config-admin/performance-policy-precedence.html
sidebar: sidebar
keywords: 
summary: 'The Performance Policies page groups policies by object type and Insight evaluates the policies in the order in which they appear in the object’s performance policy list. You can change the order in which Insight evaluates policies in order to show the information that is most important to you in your network.'
---
= Performance policy evaluation precedence
:icons: font
:imagesdir: ../media/

[.lead]
The Performance Policies page groups policies by object type and Insight evaluates the policies in the order in which they appear in the object's performance policy list. You can change the order in which Insight evaluates policies in order to show the information that is most important to you in your network.

Insight evaluates all policies that are applicable to an object sequentially when performance data samples are taken into the system for that object; however, depending on annotations, not all policies apply to one group of objects. For example, suppose that internal volume has the following policies:

* Policy 1 (the Insight-supplied default policy)
* Policy 2 (with an annotation of "`Service Level = Silver`" with the *Stop processing further policies if alert is generated* option
* Policy 3 (with an annotation of"`Service Level = Gold`")
* Policy 4

For an internal volume tier with a Gold annotation, Insight evaluates Policy 1, ignores Policy 2, and then evaluates Policy 3 and Policy 4. For an unannotated tier, Insight evaluates by the order of the policies; thus, Insight evaluates only Policy 1 and Policy 4. For an internal volume tier with a Silver annotation, Insight evaluates Policy 1 and Policy 2; however, if an alert is triggered when the policy's threshold is crossed once and is continuously crossed for the window of time specified in the policy, then Insight no longer evaluates the other policies in the list while it evaluates the current counters for the object. When Insight captures the next set of performance samples for the object, it again begins to evaluate the performance policies for the object by filter and then order.
