---
permalink: config-admin/predefined-annotation-types.html
sidebar: sidebar
keywords: 
summary: 'OnCommandInsight provides some default annotation types. These annotations can be used to filter or group data and to filter data reporting.'
---
= Default annotation types
:icons: font
:imagesdir: ../media/

[.lead]
OnCommandInsight provides some default annotation types. These annotations can be used to filter or group data and to filter data reporting.

You can associate assets with default annotation types such as the following:

* Asset life cycle, such as birthday, sunset, or end of life
* Location information about a device, such as data center, building, or floor
* Classification of assets, such as by quality (tiers), by connected devices (switch level), or by service level
* Status, such as hot (high utilization)

The following table lists the default annotation types. You can edit any of these annotation names to suit your needs.

|===
| Annotation types| Description| Type
a|
Alias
a|
User-friendly name for a resource.
a|
Text
a|
Birthday
a|
Date when the device was or will be brought online.
a|
Date
a|
Building
a|
Physical location of host, storage, switch, and tape resources.
a|
List
a|
City
a|
Municipality location of host, storage, switch, and tape resources.
a|
List
a|
Compute Resource Group
a|
Group assignment used by the Host and VM Filesystems data source.
a|
List
a|
Continent
a|
Geographic location of host, storage, switch, and tape resources.
a|
List
a|
Country
a|
National location of host, storage, switch, and tape resources.
a|
List
a|
Data Center
a|
Physical location of the resource and is available for hosts, storage arrays, switches, and tapes.
a|
List
a|
Direct Attached
a|
Indicates (Yes or No) if a storage resource is connected directly to hosts.
a|
Boolean
a|
End of Life
a|
Date when a device will be taken offline, for example, if the lease expired or the hardware is being retired.
a|
Date
a|
Fabric Alias
a|
User-friendly name for a fabric.
a|
Text
a|
Floor
a|
Location of a device on a floor of a building. Can be set for hosts, storage arrays, switches, and tapes.
a|
List
a|
Hot
a|
Devices already in heavy use on a regular basis or at the threshold of capacity.
a|
Boolean
a|
Note
a|
Comments that you want associated with a resource.
a|
Text
a|
Rack
a|
Rack in which the resource resides.
a|
Text
a|
Room
a|
Room within a building or other location of host, storage, switch, and tape resources.
a|
List
a|
SAN
a|
Logical partition of the network. Available on hosts, storage arrays, tapes, switches, and applications.
a|
List
a|
Service Level
a|
A set of supported service levels that you can assign to resources. Provides an ordered options list for internal volumes, qtree, and volumes. Edit service levels to set performance policies for different levels.
a|
List
a|
State/Province
a|
State or province in which the resource is located.
a|
List
a|
Sunset
a|
Threshold set after which no new allocations can be made to that device. Useful for planned migrations and other pending network changes.
a|
Date
a|
Switch Level
a|
Includes predefined options for setting up categories for switches. Typically, these designations remain for the life of the device, although you can edit them, if needed. Available only for switches.
a|
List
a|
Tier
a|
Can be used to define different levels of service within your environment. Tiers can define the type of level, such as speed needed (for example, gold or silver). This feature is available only on internal volumes, qtrees, storage arrays, storage pools, and volumes.
a|
List
a|
Violation Severity
a|
Rank (for example, major) of a violation (for example, missing host ports or missing redundancy), in a hierarchy of highest to lowest importance.
a|
List
|===

[NOTE]
====
Alias, Data Center, Hot, Service Level, Sunset, Switch Level, Service Level, Tier, and Violation Severity are system-level annotations, which you cannot delete or rename; you can change only their assigned values.
====
