---
permalink: config-admin/pure-storage-flasharray-http-data-source.html
sidebar: sidebar
keywords: 
summary: 'The Pure Storage FlashArray \(HTTP\) data source is used to collect information from the Pure Storage Flash Array. Insight supports both inventory and performance collection.'
---
= Pure Storage FlashArray data source
:icons: font
:imagesdir: ../media/

[.lead]
The Pure Storage FlashArray (HTTP) data source is used to collect information from the Pure Storage Flash Array. Insight supports both inventory and performance collection.

== Terminology

OnCommand Insight acquires the following inventory information from the Pure Storage FlashArray data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Drive (SSD)
a|
Disk
a|
Array
a|
Storage
a|
Controller
a|
Storage Node
a|
Volume
a|
Volume
a|
Port
a|
Port
a|
LUN Map (Host, Host Group, Target Port)
a|
Volume Map, Volume Mask
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* Storage system IP address
* User name and password for the Administrator account of the Pure storage system.
* Port requirement: HTTP/HTTPS 80/443

== Configuration

|===
| *Field*| *Description*
a|
FlashArray Host
a|
IIP address or fully-qualified domain name of FlashArray Management Server
a|
User Name
a|
User name for the FlashArray Management Server
a|
Password
a|
Password for the FlashArray Management Server
|===

== Advanced configuration

|===
| *Field*| *Description*
a|
Connection Type
a|
Management Server
a|
TCP Port
a|
TCP Port used to connect to FlashArray Server (default 443 )
a|
Connection Timeout (sec)
a|
Connection timeout (default 60 seconds)
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 60 minutes)
a|
Performance Poll Interval (sec)
a|
Interval between perfromance polls (default 300 seconds)
|===
