---
permalink: config-admin/reference_emc_xtremeio_data_source.html
sidebar: sidebar
keywords: 
summary: 'To configure the EMC XtremIO \(HTTP\) data source, you must have the XtremIO Management Server \(XMS\) Host address and an account with administrator privileges.'
---
= EMC XtremIO data source
:icons: font
:imagesdir: ../media/

[.lead]
To configure the EMC XtremIO (HTTP) data source, you must have the XtremIO Management Server (XMS) Host address and an account with administrator privileges.

== Terminology

OnCommand Insight acquires the following inventory information from the EMC XtremIO data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Disk (SSD)
a|
Disk
a|
Cluster
a|
Storage
a|
Controller
a|
Storage Node
a|
Volume
a|
Volume
a|
LUN Map
a|
Volume Map
a|
Initiator, Target
a|
Volume Mask
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* An IP address of each XtremIO Management Server
* An account with Administrator privileges
* Access to port 443 (HTTPS)

== Configuration

|===
| Field| Description
a|
XMS Host
a|
IP address or fully-qualified domain name of the XtremIO Management Server
a|
User name
a|
User name for the XtremIO Management Server
a|
Password
a|
Password for the XtremIO Management Server
|===

== Advanced configuration

|===
| Field| Description
a|
TCP port
a|
TCP Port used to connect to XTremIO Management Server (default 443 )
a|
Inventory poll interval (min)
a|
Interval between inventory polls (default 60 minutes)
a|
Connection timeout (sec)
a|
Connection timeout (default 60 seconds)
a|
Performance poll interval(sec)
a|
Interval between performance polls (default 300 seconds)
|===
