---
permalink: config-admin/reference_hitachi_content_platform_hcp_data_source.html
sidebar: sidebar
keywords: 
summary: 'This data collector supports the Hitachi Content Platform \(HCP\) using the HCP Management API.'
---
= Hitachi Content Platform (HCP) data source
:icons: font
:imagesdir: ../media/

[.lead]
This data collector supports the Hitachi Content Platform (HCP) using the HCP Management API.

== Terminology

OnCommand Insight acquires the following inventory information from the HCP data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
HCP Cluster
a|
Storage
a|
Tenant
a|
Storage Pool
a|
Namespace
a|
Internal Volume
a|
Node
a|
Node
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Inventory Requirements

* IP address of the HCP server
* Read-only user name and password for the HCP software and peer privileges

== Configuration

|===
| *Field*| *Description*
a|
HCP Host
a|
IP address or fully-qualified domain name of the HCP host
a|
HCP Port
a|
Default is 9090
a|
HCP user ID
a|
User name for the HCP host
a|
HCP Password
a|
Password used for the HCP host
a|
HCP Authentication Type
a|
Choose HCP_LOCAL or ACTIVE_DIRECTORY
|===

== Advanced configuration

|===
| Field| Description
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 60 minutes)
a|
Performance Polling Interval (sec)
a|
Interval between performance polls (default 900 seconds)
|===
