---
permalink: config-admin/reference_microsoft_azure_compute_data_source.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insights uses the Azure compute data collector to acquire inventory and performance data from Azure compute instances.'
---
= Microsoft Azure compute data source
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insights uses the Azure compute data collector to acquire inventory and performance data from Azure compute instances.

== Requirements

You need the following information to configure this data collector:

* Port requirement: 443 HTTPS
* Azure Management Rest IP (management.azure.com)
* Azure Service Principal Application (Client) ID (user account)
* Azure Service Principal Authentication key (user password)

You need to set up an Azure account for Insight discovery. Once the account is properly configured and you register the application in Azure, you will have the credentials required to discover the Azure instance with Insight. The following link describes how to set up the account for discovery:https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal

== Configuration

Enter data into the data source fields according to the table below:

|===
| Field| Description
a|
Azure Service Principal Application (Client) ID (Reader role required)
a|
Sign-in ID to Azure. Requires Reader Role access.
a|
Azure tenant ID
a|
Microsoft tenant ID
a|
Azure Service Principal Authentication Key
a|
Login authentication key
a|
I understand Microsoft bills me for API requests
a|
Check this to verify your understanding that Microsoft bills you for API requests made by Insight polling.
|===

== Advanced Configuration

Enter data into the data source fields according to the table below:

|===
| Field| Description
a|
Inventory Poll Interval (min)
a|
The default is 60
a|
Choose 'Exclude' or 'Include' to Apply to Filter VMs by Tags
a|
Specify whether to include or exclude VM's by Tags when collecting data. If '`Include`' is selected, the Tag Key field can not be empty.
a|
Tag Keys and Values on which to Filter VMs
a|
Click *+ Filter Tag* to choose which VMs (and associated disks) to include/exclude by filtering for keys and values that match keys and values of tags on the VM. Tag Key is required, Tag Value is optional. When Tag Value is empty, the VM is filtered as long as it matches the Tag Key.
a|
Performance Poll Interval (sec)\|
a|
The default is 300
|===
