---
permalink: config-admin/reference_cdot_landing_page_terminology_storage_pool.html
sidebar: sidebar
keywords: 
summary: 'Terms applying to objects or references that you might find on NetApp Clustered Data ONTAP storage pool asset landing pages.'
---
= Clustered Data ONTAP Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
Terms applying to objects or references that you might find on NetApp Clustered Data ONTAP storage pool asset landing pages.

== Clustered Data ONTAP Storage Pool Terminology

The following terms apply to objects or references that you might find on NetApp Clustered Data ONTAPstorage pool asset landing pages. Many of these terms apply to other data collectors as well.

* Storage -- what storage array this pool lives on. Mandatory.
* Type -- a descriptive value from a list of an enumerated list of possibilities. Most commonly will be "`Aggregate`" or "`RAID Group`"`".
* Node -- if this storage array's architecture is such that pools belong to a specific storage node, its name will be seen here as a hyperlink to its own landing page.
* Uses Flash Pool -- Yes/No value -- does this SATA/SAS based pool have SSDs used for caching acceleration?
* Redundancy -- RAID level or protection scheme. RAID_DP is dual parity, RAID_TP is triple parity.
* Capacity -- the values here are the logical used, usable capacity and the logical total capacity, and the percentage used across these.
* Over-committed capacity -- If by using efficiency technologies you have allocated a sum total of volume or internal volume capacities larger than the logical capacity of the storage pool, the percentage value here will be greater than 0%.
* Snapshot -- snapshot capacities used and total, if your storage pool architecture dedicates part of its capacity to segments areas exclusively for snapshots. Ontap in MetroCluster configurations are likely to exhibit this, while other Ontap configurations are less so.
* Utilization -- a percentage value showing the highest disk busy percentage of any disk contributing capacity to this storage pool. Disk utilization does not necessarily have a strong correlation with array performance -- utilization may be high due to disk rebuilds, deduplication activities, etc in the absence of host driven workloads. Also, many arrays`' replication implementations may drive disk utilization while not showing as internal volume or volume workload.
* IOPS -- the sum IOPs of all the disks contributing capacity to this storage pool.
* Throughput -- the sum throughput of all the disks contributing capacity to this storage pool.
