---
permalink: config-admin/reference_netapp_data_ontap_operating_in_7_mode_data_source.html
sidebar: sidebar
keywords: 
summary: 'For storage systems using Data ONTAP software operating in 7-Mode, you should use the ONTAPI data source, which uses the CLI to obtain capacity numbers.'
---
= NetApp Data ONTAP operating in 7-Mode data source
:icons: font
:imagesdir: ../media/

[.lead]
For storage systems using Data ONTAP software operating in 7-Mode, you should use the ONTAPI data source, which uses the CLI to obtain capacity numbers.

== Terminology

OnCommand Insight acquires the following inventory information from the NetApp Data ONTAP 7-Mode data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Disk
a|
Disk
a|
Raid Group
a|
Disk Group
a|
Filer
a|
Storage
a|
Filer
a|
Storage Node
a|
Aggregate
a|
Storage Pool
a|
LUN
a|
Volume
a|
Volume
a|
Internal Volume
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* IP address of the FAS storage controller and partner
* Port 443
* User name and password for the controller and the partner
* A custom admin level username and password for controller and partner controller with the following role capabilities for 7-Mode:
 ** "api-*": Use this to allow OnCommand Insight to execute all NetApp storage API commands.
 ** "login-http-admin": Use this to allow OnCommand Insight to connect to the NetApp storage via HTTP.
 ** "security-api-vfiler": Use this to allow OnCommand Insight to execute NetApp storage API commands to retrieve vFiler unit information.
 ** "cli-options": Use this to read storage system options.
 ** "cli-lun": Access these commands for managing LUNs. Displays the status (LUN path, size, online/offline state, and shared state) of the given LUN or class of LUNs.
 ** "cli-df": Use this to display free disk space.
 ** "cli-ifconfig": Use this to display interfaces and IP addresses.

== Configuration

|===
| *Field*| *Description*
a|
Address of Filer
a|
IP address or fully-qualified domain name for the NetApp Filer
a|
User Name
a|
User name for the NetApp Filer
a|
Password
a|
password for the NetApp Filer
a|
Address of HA Partner Filer in Cluster
a|
IP address or fully-qualified domain name for the HA Partner Filer
a|
User Name of HA Partner Filer in Cluster
a|
User name for the NetApp HA Partner Filer
a|
Password of HA Partner Filer in Cluster
a|
password for the NetApp HA Partner Filer
|===

== Advanced configuration

|===
| *Field*| *Description*
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 20 minutes)
a|
Connection Type
a|
Choose connection type
a|
Connection Port
a|
Port used for NetApp API
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 300 seconds)
|===

== Storage systems connection

As an alternative to using the default administrative user for this data source, you can configure a user with administrative rights directly on the NetApp storage systems so that this data source can acquire data from NetApp storage systems.

Connecting to NetApp storage systems requires that the user, who is specified when acquiring the main pfiler (on which the storage system exist), meet the following conditions:

* The user must be on vfiler0 (root filer/pfiler).
+
Storage systems are acquired when acquiring the main pfiler.

* The following commands define the user role capabilities:
 ** "api-*": Use this to allow OnCommand Insight to execute all NetApp storage API commands. This command is required to use the ZAPI.
 ** "login-http-admin": Use this to allow OnCommand Insight to connect to the NetApp storage via HTTP. This command is required to use the ZAPI.
 ** "security-api-vfiler": Use this to allow OnCommand Insight to execute NetApp storage API commands to retrieve vFiler unit information.
 ** "cli-options": For "options" command and used for partner IP and enabled licenses.
 ** " cli-lun": Access these command for managing LUNs. Displays the status (LUN path, size, online/offline state, and shared state) of the given LUN or class of LUNs.
 ** "cli-df": For "df -s", "df -r", "df -A -r" commands and used to display free space.
 ** "cli-ifconfig": For "ifconfig -a" command and used for getting filer IP address.
 ** "cli-rdfile": For "rdfile /etc/netgroup" command and used for getting netgroups.
 ** "cli-date": For "date" command and used to get full date for getting Snapshot copies.
 ** "cli-snap": For "snap list" command and used for getting Snapshot copies.

If cli-date or cli-snap permissions are not provided, acquisition can finish, but Snapshot copies are not reported.

To acquire a 7-Mode data source successfully and generate no warnings on the storage system, you should use one of the following command strings to define your user roles. The second string listed here is a streamlined version of the first:

----
login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,
or
login-http-admin,api-*,security-api-vfile,cli-*
----
