---
permalink: config-admin/reference_e_series_landing_page_terminology_storage_pool.html
sidebar: sidebar
keywords: 
summary: 'Terms applying to objects or references that you might find on NetApp E-Series storage pool asset landing pages.'
---
= E-Series Storage Pool
:icons: font
:imagesdir: ../media/

[.lead]
Terms applying to objects or references that you might find on NetApp E-Series storage pool asset landing pages.

== E-Series Storage Pool Terminology

The following terms apply to objects or references that you might find on NetApp E-Series storage pool asset landing pages. Many of these terms apply to other data collectors as well.

* Storage -- what storage array this pool lives on. Mandatory.
* Type -- a descriptive value from a list of an enumerated list of possibilities. Most commonly will be "`Thin Provisioning`" or "`RAID Group`".
* Node -- if this storage array's architecture is such that pools belong to a specific storage node, its name will be seen here as a hyperlink to its own landing page.
* Uses Flash Pool -- Yes/No value.
* Redundancy -- RAID level or protection scheme. E-Series reports "`RAID 7`" for DDP pools.
* Capacity -- the values here are the logical used, usable capacity and the logical total capacity, and the percentage used across these. These value both include E-Series "`preservation`" capacity, resulting both in numbers and the percentage being higher than what the E-Series own user interface may show.
* Over-committed capacity -- If by using efficiency technologies you have allocated a sum total of volume capacities larger than the logical capacity of the storage pool, the percentage value here will be greater than 0%.
* Snapshot -- snapshot capacities used and total, if your storage pool architecture dedicates part of its capacity to segments areas exclusively for snapshots.
* Utilization -- a percentage value showing the highest disk-busy percentage of any disk contributing capacity to this storage pool. Disk utilization does not necessarily have a strong correlation with array performance -- utilization may be high due to disk rebuilds, deduplication activities, etc in the absence of host-driven workloads. Also, many arrays`' replication implementations may drive disk utilization while not showing as volume workload.
* IOPS -- the sum IOPs of all the disks contributing capacity to this storage pool.
* Throughput -- the sum throughput of all the disks contributing capacity to this storage pool.
