---
permalink: config-admin/reference_qlogic_fc_switch_snmp_data_source.html
sidebar: sidebar
keywords: 
summary: 'For configuration, the QLogic FC Switch \(SNMP\) data source requires the network address for the FC Switch device, specified as an IP address, and an SNMP read-only community string used to access the device.'
---
= QLogic FC Switch data source
:icons: font
:imagesdir: ../media/

[.lead]
For configuration, the QLogic FC Switch (SNMP) data source requires the network address for the FC Switch device, specified as an IP address, and an SNMP _read-only_ community string used to access the device.

== Configuration

|===
| *Field*| *Description*
a|
SANSurfer Switch
a|
IP address or fully-qualified domain name for the SANSurfer switch
a|
SNMP version
a|
SNMP version
a|
SNMP community
a|
SNMP Community String
a|
User Name
a|
User name for the SANSurfer switch
a|
Password
a|
Password for the SANSurfer switch
|===

== Advanced configuration

|===
| *Field*| *Description*
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 15 minutes)
a|
SNMP Auth Protocol
a|
SNMP authentication protocol (SNMPv3 only)
a|
SNMP Retries
a|
Number of SNMP retry attempts
a|
SNMP Timeout (ms)
a|
SNMP timeout (default 5000 ms)
a|
Enable Trapping
a|
Select to enable trapping
a|
Minimum Time Between Traps (sec)
a|
Minimum time between acquisition attempts triggered by traps (default 10 seconds)
a|
Fabric Name
a|
Fabric name to be reported by the data source. Leave blank to report the fabric name as WWN.
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 300 seconds)
|===
