---
permalink: config-admin/reference_dell_emc_ecs_data_source.html
sidebar: sidebar
keywords: 
summary: 'This data collector acquires inventory and performance data from EMC ECS storage systems. For configuration, the data collector requires an IP address of the ECS server and an administrative level domain account..'
---
= Dell EMC ECS data source
:icons: font
:imagesdir: ../media/

[.lead]
This data collector acquires inventory and performance data from EMC ECS storage systems. For configuration, the data collector requires an IP address of the ECS server and an administrative level domain account..

== Terminology

OnCommand Insight acquires the following inventory information from the EMC ECS data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Cluser
a|
Storage
a|
Tenant
a|
Storage Pool
a|
Bucket
a|
Internal Volume
a|
Disk
a|
Disk
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* An IP address of the ECS Management Console
* Administrative level domain account for the ECS system
* Port 443 (HTTPS). Requires outbound connectivity to TCP port 443 on the ECS system.
* For performance, read-only username and password for ssh/scp access.
* For performance, port 22 is required.

== Configuration

|===
| Field| Description
a|
ECS Host
a|
IP addresses or fully-qualified domain names of the ECS system
a|
ECS Host Port
a|
Port used for communication with ECS Host
a|
ECS Vendor ID
a|
Vendor ID for ECS
a|
Password
a|
Password used for ECS
|===

== Advanced configuration

|===
| Field| Description
a|
Inventory Poll Interval (minutes)
a|
Interval between inventory polls. The default is 360 minutes.
|===
