---
permalink: config-admin/reference_brocade_sphereon_intrepid_switch_snmp_data_source.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight uses the Brocade Sphereon/Intrepid Switch \(SNMP\) data source to discover inventory for Brocade Sphereon or Intrepid switches.'
---
= Brocade Sphereon/Intrepid Switch data source
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight uses the Brocade Sphereon/Intrepid Switch (SNMP) data source to discover inventory for Brocade Sphereon or Intrepid switches.

== Requirements

[NOTE]
====
This data collector not available starting with OnCommand Insight 7.3.11.
====

* There must be IP connectivity to all switches in the fabric. If you select the Discover all switches in the fabric check box, OCI identifies all the switches in the fabric; however, it needs IP connectivity to these additional switches to discover them.
* Read-only community string if using SNMP V1 or SNMP V2.
* HTTP access to the switch to obtain zoning information.
* Access validation by running the `snmpwalk` utility to the switch (see `<install_path\>\bin\)`.

== Configuration

|===
| *Field*| *Description*
a|
Sphereon Switch
a|
IP address or fully-qualified domain name of the switch
a|
SNMP Version
a|
SNMP version
a|
SNMP Community
a|
SNMP read-only community string used to access the switch
a|
User Name
a|
SMI-S user name for the switch (SNMP v3 only)
a|
Password
a|
SMI-S password for the switch (SNMP v3 only)
|===

== Advanced configuration

|===
| *Field*| *Description*
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 15 minutes)
a|
SNMP Auth Protocol
a|
SNMP authentication protocol (SNMPv3 only)
a|
SNMP Privacy Protocol
a|
SNMP privacy protocol (SNMPv3 only)
a|
SNMP Privacy Password
a|
SNMP privacy password
a|
SNMP Number of Retries
a|
Number of SNMP retry attempts
a|
SNMP Timeout (ms)
a|
SNMP timeout (default 5000 ms)
a|
Fabric Name
a|
Fabric name to be reported by the data source. Leave blank to report the fabric name as WWN.
a|
Enable Trapping
a|
Select to enable acquisition upon receiving an SNMP trap from the device. If you select enable trapping, you must also activate SNMP.
a|
Minimum Time Between Ttraps (seconds)
a|
Minimum time between acquisition attempts triggered by traps (default 10 seconds)
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 300 seconds)
|===
