---
permalink: config-admin/reference_emc_solutions_enabler_cli_with_smi_s_performance.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight discovers Symmetrix storage arrays by using Solutions Enabler symcli commands in conjunction with an existing Solutions Enabler server in your environment. The existing Solutions Enabler server has connectivity to the Symmetrix storage array through access to gatekeeper volumes. Administrator permissions are required to access this device.'
---
= EMC Solutions Enabler with SMI-S Performance data source
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight discovers Symmetrix storage arrays by using Solutions Enabler `symcli` commands in conjunction with an existing Solutions Enabler server in your environment. The existing Solutions Enabler server has connectivity to the Symmetrix storage array through access to gatekeeper volumes. Administrator permissions are required to access this device.

== Terminology

OnCommand Insight acquires the following inventory information from the EMC Solutions Enabler data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Disk
a|
Disk
a|
Disk Group
a|
Disk Group
a|
Storage Array
a|
Storage
a|
Director
a|
Storage Node
a|
Device Pool, Storage Resource Pool (SRP)
a|
Storage Pool
a|
Device, TDev
a|
Volume
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

Before configuring this data source, you should ensure that the OnCommand Insight server has TCP connectivity to port 2707 on the existing Solutions Enabler server. OnCommand Insight discovers all the Symmetrix arrays that are "`Local`" to this server, as seen in "`symcfg list`" output from that server.

* The EMC Solutions Enabler (CLI) with SMI-S provider application must be installed and the version must match or be earlier than the version running on the Solutions Enabler Server.
* A properly configured `+{installdir}\EMC\SYMAPI\config\netcnfg+` file is required. This file defines service names for Solutions Enabler servers, as well as the access method (SECURE / NOSECURE /ANY).
* If you require read/write latency at the storage node level, the SMI-S Provider must communicate with a running instance of the UNISPHERE for VMAX application.
* Administrator permissions on the Solutions Enabler (SE) Server
* Read-only user name and password to the SE software
* Solutions Enabler Server 6.5X requirements:
 ** SMI-S provider 3.3.1 for SMIS-S V1.2 installed
 ** After install, run `\Program Files\EMC\SYMCLI\bin>stordaemon start storsrvd`
* The UNISPHERE for VMAX application must be running and collecting statistics for the Symmetrix VMAX storage arrays that are managed by the SMI-S Provider installation
* Access validation: Verify that the SMI-S provider is running: `telnet <se_server\> 5988`

== Configuration

[NOTE]
====
If SMI-S user authentication is not enabled, the default values in the OnCommand Insight data source are ignored.
====

Having symauth enabled on Symmetrix arrays might inhibit the ability of OnCommand Insight to discover them. OnCommand Insight Acquisition runs as the SYSTEM user on the OnCommand Insight / Remote Acquisition Unit server that is communicating with the Solutions Enabler server. If hostname\SYSTEM does not have symauth privileges, OnCommand Insight fails to discover the array.

The EMC Solutions Enabler Symmetrix CLI data source includes support for device configuration for thin provisioning and Symmetrix Remote Data Facility (SRDF).

Definitions are supplied for Fibre Channel and Switch Performance packages.

|===
| Field| Description
a|
Service Name
a|
Service name as specified in netcnfg file
a|
Full path to CLI
a|
Full path to the Symmetrix CLI
|===

== Advanced configuration

|===
| Field| Description
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 40 minutes)
a|
Choose 'Exclude' or 'Include' to specify a list
a|
Specify whether to include or exclude the array list below when collecting data
a|
Inventory Exclude Devices
a|
Comma-separated list of device IDs to include or exclude
a|
Connection Caching
a|
Choose connection caching method:

* LOCAL means that the OnCommand Insight Acquisition service is running on the Solutions Enabler server, which has Fibre Channel connectivity to the Symmetrix arrays you seek to discover, and has access to gatekeeper volumes. This might be seen in some Remote Acquisition Unit (RAU) configurations.
* REMOTE_CACHED is the default and should be used in most cases. This uses the NETCNFG file settings to connect using IP to the Solutions Enabler server, which must have Fibre Channel connectivity to the Symmetrix arrays you seek to discover, and has access to Gatekeeper volumes.
* In the event that REMOTE_CACHED options make CLI commands fail, use the REMOTE option. Keep in mind that it will slow down the acquisition process (possibly to hours or even days in extreme cases). The NETCNFG file settings are still used for an IP connection to the Solutions Enabler server that has Fibre Channel connectivity to the Symmetrix arrays being discovered.

[NOTE]
====
This setting does not change OnCommand Insight behavior with respect to the arrays listed as REMOTE by the "symcfg list" output. OnCommand Insight gathers data only on devices shown as LOCAL by this command.
====

a|
CLI Timeout (sec)
a|
CLI process timeout (default 7200 seconds)
a|
SMI-S Host IP
a|
IP address of the SMI-S Provider Host
a|
SMI-S Port
a|
Port used by SMI-S Provider Host
a|
Protocol
a|
Protocol used to connect to the SMI-S provider
a|
SMI-S Namespace
a|
Interoperability namespace that the SMI-S provider is configured to use
a|
SMI-S User Name
a|
User name for the SMI-S Provider Host
a|
SMI-S Password
a|
User name for the SMI-S Provider Host
a|
Performance Polling Interval (sec)
a|
Interval between performance polls (default 1000 seconds)
a|
Performance Filter Type
a|
Specify whether to include or exclude the array list below when collecting performance data
a|
Performance Filter Device List
a|
Comma-separated list of device IDs to include or exclude
a|
RPO Polling Interval (sec)
a|
Interval between RPO polls (default 300 seconds)
|===
