---
permalink: config-admin/reference_emc_vplex_cli_data_source.html
sidebar: sidebar
keywords: 
summary: 'For configuration, this data source requires an IP address of the VPLEX server and an administrative level domain account.'
---
= EMC VPLEX data source
:icons: font
:imagesdir: ../media/

[.lead]
For configuration, this data source requires an IP address of the VPLEX server and an administrative level domain account.

== Terminology

OnCommand Insight acquires the following inventory information from the EMC VPLEX data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Cluster
a|
Storage
a|
Engine
a|
Storage Node
a|
Device, System Extend
a|
Backend Storage Pool
a|
Virtual Volume
a|
Volume
a|
Front-End Port, Back-End Port
a|
Port
a|
Distributed Device
a|
Storage Synchronization
a|
Storage View
a|
Volume Map, Volume Mask
a|
Storage Volume
a|
Backend LUN
a|
ITLs
a|
Backend Path
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* An IP address of the VPLEX server
* Administrative level domain account for the VPLEX server
* Port 443 (HTTPS). Requires outbound connectivity to TCP port 443 on the VPLEX management station.
* For performance, read-only username and password for ssh/scp access.
* For performance, port 22 is required.
* Validate access: Verify by using `telnet` to port 443. For a port other than the default port, with any browser use `HTTPS://``<ip>`:``<port>``

== Configuration

|===
| Field| Description
a|
IP address of VPLEX Management Console
a|
IP address or fully-qualified domain name of the VPLEX Management Console
a|
User Name
a|
User name for VPLEX CLI
a|
Password
a|
Password used for VPLEX CLI
a|
Performance Remote IP Address of VPLEX Management Console
a|
Performance Remote IP address of the VPLEX Management Console
a|
Performance Remote User Name
a|
Performance Remote user name of VPLEX Management Console
a|
Performance Remote Password
a|
Performance Remote Password of VPLEX Management Console
|===

== Advanced configuration

|===
| Field| Description
a|
Communication Port
a|
Port used for VPLEX CLI
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 20 minutes)
a|
Connection timeout (sec)
a|
Connection timeout (default 60 seconds)
a|
Number of Retries
a|
Number of inventory retry attempts
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 600 seconds)
a|
Performance SSH Process Wait Timeout (sec)
a|
SSH process timeout (default 600 seconds)
a|
SSH Banner Wait Timeout (sec)
a|
SSH banner wait timeout (default 20 seconds)
a|
Number of Retries
a|
Number of performance retry attempts
|===
