---
permalink: config-admin/researching-a-failed-data-source.html
sidebar: sidebar
keywords: 
summary: 'If a data source has the "Inventory failed !" or "Performance failed !" message and a High or Medium Impact, you need to research this problem using the data source summary page with its linked information.'
---
= Researching a failed data source
:icons: font
:imagesdir: ../media/

[.lead]
If a data source has the "*Inventory failed !*" or "*Performance failed !*" message and a High or Medium Impact, you need to research this problem using the data source summary page with its linked information.

== Steps

. Click the linked *Name* of the data source to open the Summary page.
. On the Summary page, check the *Comments* area to read any notes left by another engineer who might also be investigating this failure.
. Note any performance messages.
. If there is a patch being applied to this data source, click link to check the *patch page* to see if that has caused the problem.
. Move your mouse pointer over the segments of the *Event timeline* graph to display additional information.
. Select an error message for a Device and displayed below the Event timeline and click the *Error details* icon that displays to the right of the message.
+
The Error details include the text of the error message, most likely causes, information in use, and suggestions of what can be tried to correct the problem.

. In the Devices reported by this data source area, you might filter the list to display only devices of interest, and you can click the linked *Name* of a device to display the _asset page_ for that device.
. To return to previously displayed pages, use one of these techniques:
 ** Click the browser back arrow.
 ** Right-click the back arrow to display a list of the pages and select the page you want.
. To display detailed information about other resources, click other linked names.
. When you return to the data source summary page, check the *Changes* area at the bottom of the page to see if recent changes caused the problem.
