---
permalink: config-admin/rolling-back-a-data-source-patch.html
sidebar: sidebar
keywords: 
summary: 'If a data source patch is not working in the manner you expected, you can roll it back. Rolling back a patch deletes it, and restores the previous version as it was before this patch was applied.'
---
= Rolling back a data source patch
:icons: font
:imagesdir: ../media/

[.lead]
If a data source patch is not working in the manner you expected, you can roll it back. Rolling back a patch deletes it, and restores the previous version as it was before this patch was applied.

== Steps

. On the Insight toolbar, click *Admin*.
. Click *Patches*.
. In *Patches currently under review*, click the linked name of the patch that appears to be unsuccessful.
. On the Patches page for the data source, examine this information:
 ** *Summary* describes when the patch was applied, the affected data sources, and comments about the patch from you or other members of your team.
 ** *Affected data sources* lists all of the data sources being patched and includes a comparison of the before and after patching status.
. To display the details for a data source that is not successfully processing the patch, click the linked *Name*.
 .. Check the summary information.
 .. Check the *Event timeline* to see any configuration or performance data that might be affecting this data source.
. If you conclude that the patch is not going to be successful, click the browser back arrow to return to the Patches summary page.
. Click *Roll back* to remove that patch.
+
If you know of a different patch that is more likely to be successful, click *Replace patch* and upload the new patch.
