---
permalink: config-admin/rule-assisted-manual-identification.html
sidebar: sidebar
keywords: 
summary: 'This feature is used for special cases where you want to run a specific rule or a list of rules \(with or without a one-time reordering\) to resolve unknown hosts, storage, and tape devices or group of them.'
---
= Rule assisted manual identification
:icons: font
:imagesdir: ../media/

[.lead]
This feature is used for special cases where you want to run a specific rule or a list of rules (with or without a one-time reordering) to resolve unknown hosts, storage, and tape devices or group of them.

== Before you begin

You have a number of devices that have not been identified and you also have multiple rules that successfully identified other devices.

== About this task

[NOTE]
====
If your source only contains part of a host or device name, use a regular expression rule and format it to add the missing text.
====

== Steps

. Log into the OnCommand Insight web UI.
. Click *Manage* > *Device resolution*
. Click the *FC Identify* tab.
+
The system displays the identified and unidentified devices.

. Select multiple unidentified devices.
. Click *Identify* > *Set host resolution* or *> Set tape resolution*
+
The system displays the Identify screen which contains a list of all of the rules that successfully identified devices.

. Change the order of the rules to an order that meets your needs.
+
The order of the rules are changed in the Identify screen, but are not changed globally.

. Select the method that that meets your needs.
+
OnCommand Insight executes the host resolution process in the order in which the methods appear, beginning with those at the top.
+
When rules that apply are encountered, rule names are shown in the rules column and identified as manual.
