---
permalink: config-admin/task_locating_required_information_for_new_disk_model.html
sidebar: sidebar
keywords: 
summary: 'To locate the disk model information, identify the vendor and model number and run an Internet search.'
---
= Locating required information for new disk model
:icons: font
:imagesdir: ../media/

[.lead]
To locate the disk model information, identify the vendor and model number and run an Internet search.

== About this task

Locating disk model information is as simple as running an internet search. Be sure to note the vendor name and disk model number before searching.

== Steps

. It is recommended to use an advanced internet search for the vendor, model, and document type "`PDF`" to find the vendor's data sheet and/or installation guide for the drive. These data sheets are usually the best source for vendor disk information.
. Vendor specifications do not always provide all of the necessary information based on the full model number. It is often useful to search for different parts of the model number string on the vendor's site to locate all of the information.
. Locate the disk vendor name, full model number, disk size and speed, and the interface type in order to define the new disk model in OnCommand Insight You can use the following table as a guide to help note this information as you find it:
+
|===
| For this field:| Which is:| Enter this:
a|
Model number (aka Key)
a|
Required
a|
 
a|
Vendor
a|
Required
a|
 
a|
Disk speed (RPM)
a|
Required
a|
 
a|
Size (in GB)
a|
Required
a|
 
a|
Interface Type (select one)
a|
Required
a|
ATA, SATA, SATA2, SATA3, FC, SAS, FATA, SSD, OTHER
a|
Seek time in ms
a|
Optional
a|
 
a|
Maximum transfer rate in MB/sec
a|
Optional
a|
 
a|
Interface transfer rate in MB/sec
a|
Optional
a|
 
a|
Link to vendor/model information
a|
Optional but recommended
a|
 
|===

. Enter that information into the `new_disk_models.txt` file. See link:reference_content_of_the_new_disk_models_txt_file.md#[Content of the new_disk_models.txt file] for format, order, and examples.
