---
permalink: config-admin/task_setting_up_weekly_backups_for_your_oci_database.html
sidebar: sidebar
keywords: 
summary: 'You might want to set up automatic weekly backups for your Insight database to protect your data. These automatic backups overwrite the files in the specified backup directory.'
---
= Setting up weekly backups for your Insight database
:icons: font
:imagesdir: ../media/

[.lead]
You might want to set up automatic weekly backups for your Insight database to protect your data. These automatic backups overwrite the files in the specified backup directory.

== About this task

*Best practice*: When you are setting up the weekly backup of the OCI database, you need to store the backups on a different server than Insight is using, in case that server fails. Do not store any manual backups in the weekly backup directory because each weekly backup overwrites the files in the directory.

The backup file will contain the following:

* Inventory data
* Up to 7 days of performance data

== Steps

. On the Insight toolbar, click *Admin* > *Setup*.
. Click the *Backup & Archive* tab.
. In the Weekly Backup section, select *Enable weekly backup*.
. Enter the path to the *Backup location*. This can be on the on the local Insight server or on a remote server that is accessible from the Insight server.
+
[NOTE]
====
The backup location setting is included in the backup itself, so if you restore the backup on another system, be aware that the backup folder location may be invalid on the new system. Double-check your backup location settings after restoring a backup.
====

. Select the *Cleanup* option to keep either the last two or the last five backups.
. Click *Save*.

== Results

You can also go to *Admin* > *Troubleshooting* to create an on-demand backup.
