---
permalink: config-admin/task_setting_annotation_rule_precedence.html
sidebar: sidebar
keywords: 
summary: 'By default, OnCommand Insight evaluates annotation rules sequentially; however, you can configure the order in which OnCommand Insight evaluates annotation rules if you want Insight to evaluate rules in a specific order.'
---
= Setting annotation rule precedence
:icons: font
:imagesdir: ../media/

[.lead]
By default, OnCommand Insight evaluates annotation rules sequentially; however, you can configure the order in which OnCommand Insight evaluates annotation rules if you want Insight to evaluate rules in a specific order.

== Steps

. Log in to the Insightweb UI.
. Click *Manage* and select *Annotation rules*.
+
The Annotation Rules page displays the list of existing annotation rules.

. Position your cursor over an annotation rule.
+
The precedence arrows appear to the right of the rule.

. To move a rule up or down in the list, click the up arrow or the down arrow.
+
By default, new rules are added sequentially to the list of rules. Annotations set manually on an individual asset pages take precedence over rule-based annotations when Insight evaluates the annotation rules.
