---
permalink: config-admin/task_editing_multiple_data_sources.html
sidebar: sidebar
keywords: bulk edit
summary: 'You can edit most of the information for multiple data sources of the same vendor and model at one time. For example, if these data sources share a user name and password, you can change the password in one place and thereby update the password for all the selected data sources.'
---
= Editing information for multiple data sources
:icons: font
:imagesdir: ../media/

[.lead]
You can edit most of the information for multiple data sources of the same vendor and model at one time. For example, if these data sources share a user name and password, you can change the password in one place and thereby update the password for all the selected data sources.

== About this task

Options that you cannot edit for the selected data sources appear dimmed or are not displayed in the Edit data source dialog box. Additionally, when an option displays a value of *Mixed*, it indicates that the value for the option varies between the selected data sources. For example, if the *Timeout (sec)* option for two selected data sources is *Mixed*, one data source could have a timeout value of 60 and the other could have a value of 90; therefore, if you change this value to 120 and save the changes to the data sources, the timeout setting for both data sources becomes 120.

== Steps

. Click *Admin* and navigate to the data source list view
. Select the data sources you want to modify. Selected data sources must belong to same vendor, model and acquisition unit.
. Click the *Actions* button and select the *Edit* option.
. In the edit dialog, change any of the *Settings* as needed.
. Click the *Configuration* link to change any of the basic options for the data sources.
. Click the *Advanced Configuration* link to change any of the advanced options for the data sources.
. Click *Save*.
