---
permalink: config-admin/task_viewing_queries.html
sidebar: sidebar
keywords: 
summary: 'You can view your queries to monitor your assets and change how your queries display the data related to your assets.'
---
= Viewing queries
:icons: font
:imagesdir: ../media/

[.lead]
You can view your queries to monitor your assets and change how your queries display the data related to your assets.

== Steps

. Log in to the OnCommand Insight web UI.
. Click *Queries* and select *Show all queries*.
. You can change how queries display by doing any of the following:
 ** You can enter text in the *filter* box to search to display specific queries.
 ** You can change the sort order of the columns in the table of queries to either ascending (up arrow) or descending (down arrow) by clicking the arrow in the column header.
 ** To resize a column, hover the mouse over the column header until a blue bar appears. Place the mouse over the bar and drag it right or left.
 ** To move a column, click on the column header and drag it right or left.
 ** When scrolling through the query results, be aware that the results may change as Insight automatically polls your data sources. This may result in some items being missing, or some items appearing out of order depending on how they are sorted.
