---
permalink: config-admin/task_importing_data_sources_from_a_spreadsheet.html
sidebar: sidebar
keywords: 
summary: 'You can import multiple data sources into OnCommand Insight from a spreadsheet. This might be helpful if you already maintain your discovery devices in a spreadsheet. This process adds new data sources, but cannot be used to update existing data sources.'
---
= Importing data sources from a spreadsheet
:icons: font
:imagesdir: ../media/

[.lead]
You can import multiple data sources into OnCommand Insight from a spreadsheet. This might be helpful if you already maintain your discovery devices in a spreadsheet. This process adds new data sources, but cannot be used to update existing data sources.

== About this task

OnCommand Insight includes a spreadsheet to help you create data sources. This spreadsheet has the following attributes:

* The spreadsheet can be used with Microsoft Excel 2003 or later.
* Each tab holds one data source type, for example, Brocade SSH/CLI.
* Each row represents an instance of a new data source to be created.

The spreadsheet includes a macro that creates a new data source in OnCommand Insight.

== Steps

. Locate the spreadsheet in the `<install_directory>/SANscreen/acq/bin/acqcli/SiteSurvey_DataSourceImporter_w_Macro.zip`.
. In the spreadsheet, enter data source information in the cells with color.
. Delete empty rows.
. From the spreadsheet, run the `CreateDataSources` macro to create the data sources.
. When prompted for credentials, enter the OnCommand Insight Server administration user name and password.
+
The results are logged in the acquisition log.

. A prompt asks if the machine currently running the macro has OnCommand Insight installed.
+
Select one of the following:

 ** No: Select "No" if a batch file will be created that must be run on the OnCommand Insight machine. Run this batch file from the install directory.
 ** Yes: Select "Yes" if OnCommand Insight is already installed and no additional steps are required to generate the data source information.

. To verify the addition of the data sources, open Insight in your browser.
. On the Insight toolbar, click *Admin*.
. Check the Data sources list for the data sources you imported.
