---
permalink: config-admin/updating-expired-licenses.html
sidebar: sidebar
keywords: 
summary: 'If one or more of your Insight licenses expired, you can update the licenses quickly using the same procedure as you did to install the licenses originally.'
---
= Updating expired licenses
:icons: font
:imagesdir: ../media/

[.lead]
If one or more of your Insight licenses expired, you can update the licenses quickly using the same procedure as you did to install the licenses originally.

== Steps

. In a text editor, such as Notepad, open the new license file you received from NetApp Support and copy the license key text to your Windows Clipboard.
. Open OnCommand Insight in your browser.
. Click on *Admin* on the toolbar.
. Click *Setup*.
. Click the *Licenses* tab.
. Click *Update License*.
. Copy the license key text into the *License* text box.
. Select the *Update (most common)* operation.
+
This operation adds your new licenses to any currently active Insight licenses.

. Click *Save*.
. If you are using the Insight consumption licensing model, you must check the box to *Enable sending usage information to NetApp* in the usage section. Proxy must be properly configured and enabled for your environment.
