---
permalink: config-admin/violin-memory-data-source.html
sidebar: sidebar
keywords: 
summary: 'The Violin 6000-Series Flash Memory Array \(HTTP\) data source collects network information for analysis and validation from Violin 6000-series flash memory arrays.'
---
= Violin Flash Memory Array data source
:icons: font
:imagesdir: ../media/

[.lead]
The Violin 6000-Series Flash Memory Array (HTTP) data source collects network information for analysis and validation from Violin 6000-series flash memory arrays.

== Terminology

[NOTE]
====
This data collector is no longer available starting with OnCommand Insight 7.3.11.
====

OnCommand Insight acquires the following inventory information from the Violin 6000-Series Flash Memory Array data source. For each asset type acquired by Insight, the most common terminology used for this asset is shown. When viewing or troubleshooting this data source, keep the following terminology in mind:

|===
| Vendor/Model Term| Insight Term
a|
Violin Intelligent Memory Module (VIMM)
a|
Disk
a|
Container
a|
Storage
a|
Memory Gateway
a|
Storage Node
a|
LUN
a|
Volume
a|
Initiator, Initiator Group, Target
a|
Volume Map, Volume Mask
|===

[NOTE]
====
These are common terminology mappings only and might not represent every case for this data source.
====

== Requirements

* You need a read-only user name and password to the storage.
* Validate access with a web browser using the storage IP address.

== Configuration

|===
| Field| Description
a|
IP address or FQDN of Violin Memory Array Main Gateway
a|
IP address or fully-qualified domain name of the Violin Memory Array Main Gateway
a|
User Name
a|
User name for the Violin Memory Array Main Gateway
a|
Password
a|
Password for the Violin Memory Array Main Gateway
|===

== Advanced configuration

|===
| Field| Description
a|
Communication Port
a|
Port used for communication with Violin array
a|
HTTPS Enabled
a|
Select to use HTTPS
a|
Inventory Poll Interval (min)
a|
Interval between inventory polls (default 20 minutes)
a|
Connection timeout (sec)
a|
Connection timeout (default 60 seconds)
a|
Performance Poll Interval (sec)
a|
Interval between performance polls (default 300 seconds)
|===
