---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
sidebar:
  entries:
    - title: OnCommand Insight docs
      url: /index.html
    - section: relnotes
    - section: overview
    - section: install-linux
    - section: install-windows
    - section: config-admin
    - section: dwh
    - section: reporting
    - section: faq
    - section: howto
    - title: Legal notices
      url: /legal-notices.html
  
