---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
sidebar:
  entries:
    - title: OnCommand Insight docs
      url: /index.html
    - section: config-admin
    - section: dwh
    - section: faq
    - section: howto
    - section: install-linux
    - section: install-windows
    - section: reporting
    - title: Legal notices
      url: /legal-notices.html
      
homepage:
  tiles:
    - title: Get started
      links:
        - title: Configuration and administration
          summary: This is the description of the link target
          url: config-admin/index.html
