---
permalink: reporting/concept_reporting_made_easy.html
sidebar: sidebar
keywords: 
summary: 'You can generate pre-defined reports from the OnCommand Insight Reporting Portal, email them to other users, and even modify them. Several reports enable you to filter by device, business entity, or tier. The reporting tools use IBM Cognos as a foundation and give you many data presentation options.'
---
= Reporting made easy
:icons: font
:imagesdir: ../media/

[.lead]
You can generate pre-defined reports from the OnCommand Insight Reporting Portal, email them to other users, and even modify them. Several reports enable you to filter by device, business entity, or tier. The reporting tools use IBM Cognos as a foundation and give you many data presentation options.

* The OnCommand Insight pre-defined reports show your inventory, storage capacity, chargeback, performance, storage efficiency, and cloud cost data. You can modify these pre-defined reports and save your modifications.

The report data available to you is controlled by several things, including the following:

* Login access to the OnCommand Insight Reporting Portal, which is defined by roles.
* The setup of the OnCommand InsightData Warehouse, which stores the data for the reports.

You can generate reports in various formats, including HTML, PDF, CSV, XML, and Excel.

OnCommand Insight accommodates multiple tenancy in reporting by enabling you to associate users with business units. With this feature, administrators can separate data or reports according to the attributes of a user or his affiliation.

[NOTE]
====
With Cognos version 11.1.2 onward, reporting URLs are not considered "stable" and are subject to change. If you have bookmarked reporting URLs, these bookmarks may subsequently fail. More information can be found here: http://queryvision.com/ibm-analytics-11-x-urls-they-are-a-changing/
====

[NOTE]
====
OnCommand Insight does not support any Dashboards created using Packages in IBM Cognos, unless using the new Data Module feature.
====
