---
permalink: reporting/what-you-need-to-do-before-you-design-your-report.html
sidebar: sidebar
keywords: 
summary: 'Before you design your custom report, you need to complete some prerequisite tasks. If you do not complete these, reports could be inaccurate or incomplete.'
---
= What you need to do before you design your report
:icons: font
:imagesdir: ../media/

[.lead]
Before you design your custom report, you need to complete some prerequisite tasks. If you do not complete these, reports could be inaccurate or incomplete.

For example, if you do not finish the device identification process, your capacity reports will not be accurate. Or, if you do not finish setting annotations (such as tiers, business units, and data centers), your custom reports might not accurately report data across your domain and might show "N/A" for some data points.

Before you design your reports, complete the following tasks:

* Configure all data sources. For details, see the _OnCommand Insight Configuration and Administration Guide_.
* Enter annotations (such as tiers, data centers, and business units) on devices and resources in your environment. It is beneficial to have annotations stable before generating reports, because OnCommand Insight Data Warehouse collects historical information.
* Configure OnCommand Insight Data Warehouse to accept the data from the OnCommand Insight server in the Extract, Transform, and Load (ETL) process.
