---
permalink: install-windows/concept_oncommand_insight_installation_instructions.html
sidebar: sidebar
keywords: 
summary: 'Installation requires you to install several OnCommand Insight components, including Insight Server, Data Warehouse and Reporting, and Anomaly Detection.'
---
= Insight installation instructions
:icons: font
:imagesdir: ../media/

[.lead]
Installation requires you to install several OnCommand Insight components, including Insight Server, Data Warehouse and Reporting, and Anomaly Detection.

The installation includes the following major tasks:

* Downloading the OnCommand Insight installer
* Installing OnCommand Insight server
* Installing licenses
* Optionally, installing DWH and Reporting (must be installed on a separate machine or virtual machine)
* Optionally, installing a remote acquisition unit (RAU), which acquires information from your device resources that reside behind a firewall, are located at a remote site, or are on a private network
* Optionally, installing the anomaly detection engine (must be installed on a separate machine or virtual machine running Linux.)
* For upgrades, upgrading OnCommand Insight reports.

After installation, you must configure Insight to acquire information about your environment. The tasks required are described in the _OnCommand Insight Configuration and Administration Guide_.
