---
permalink: install-windows/installation-prerequisites.html
sidebar: sidebar
keywords: 
summary: 'Before you install OnCommand Insight, you must download the current software version, acquire the appropriate license, and set up your environment.'
---
= Installation prerequisites
:icons: font
:imagesdir: ../media/

[.lead]
Before you install OnCommand Insight, you must download the current software version, acquire the appropriate license, and set up your environment.

Before installing OnCommand Insight, ensure that you have the following:

* OnCommand Insight software files in the downloaded installation package for the current version
* A license to operate the downloaded OnCommand Insight version
* The minimum hardware and software environment
+
The current product might consume additional hardware resources (due to enhanced OnCommand Insight product functionality) that were not consumed with earlier versions of the OnCommand Insight product.

* A deployment plan that includes the hardware and network configurations for the OnCommand Insight Server, Data Warehouse and Reporting, and remote acquisition units.
* Java 8 for the OnCommand Insight Java UI.
+
NOTE: OnCommand Insight includes a paid Oracle license for Java SE 8. Customers do not have to buy any additional Java SE 8 licenses. This license covers use of Java SE 8 with all OCI components. Please refer to the http://docs.netapp.com/oci-73/topic/com.netapp.ndc.notices/GUID-93BE9A1E-D79E-4A97-87A2-4DBE31372A16.html[Notices] page for specific details.

* Disabled virus scan software
+
During the installation of OnCommand Insight, you must completely disable all virus scanners. Following installation, the paths used by the Insight component (install, backup, and archiver paths) must be excluded from virus scanning, in addition to excluding the entire `sanscreen` directory from the scan.
+
Additionally, you must also exclude the IBM/Db2 folder (for example _C:\Program Files\IBM\DB2_) from anti-virus scanning following installation.

[NOTE]
====
If you are performing a full installation as an upgrade or as a migration to new hardware and your existing system contains a non-default security configuration, you must back up the security configuration before you perform the installation. After the installation is complete, you must restore the security configuration before you restore the Server (which includes the local acquisition unit) or Data Warehouse database.You must restore the security configuration to all of your Insight servers before you restore the DWH Database.

For in-place upgrade (available for Insight Server only), the security configuration is properly handled and you do not need to restore it.

You use the `securityadmin` tool to create a backup of the configuration and to restore the saved configuration. For more information, search for `securityadmin` in the OnCommand Insight Documentation Center: http://docs.netapp.com/oci-73/index.jsp

====
