---
permalink: install-windows/installing-a-remote-acquisition-unit-rau.html
sidebar: sidebar
keywords: 
summary: 'Install one or more RAUs in your OnCommand Insight environment.'
---
= Installing a Remote Acquisition Unit (RAU)
:icons: font
:imagesdir: ../media/

[.lead]
Install one or more RAUs in your OnCommand Insight environment.

== Before you begin

You must have completed all of the installation prerequisites.

At least one port needs to be open and available between the RAU server and the OnCommand Insight Server in order to forward change information to the server. If you are unsure about this, validate it by opening a Web browser on the RAU computer and directing it to the OnCommand Insight server:

----
 https://< OnCommand Insight Server hostname >:< acquisition_port >
----

The acquisition port defaults to 443, but it may have been changed during the server installation. If the connection is successful, you see a OnCommand Insight response page indicating an open and available port between the RAU and the OnCommand Insight server.

== Steps

. Log in to the RAU server using an account with administrator privileges.
. Open Windows Explorer and navigate to the directory where the RAU installation file is located.
. Double-click `.MSI` file to start the installation.
. Click *Next* to continue to the window that shows the License Agreement. Read this and accept the terms of the License Agreement and click *Next*.
. Select to install the RAU on a local hard drive or the entire feature on a local hard drive. (You can check the Disk Usage link to ensure you have enough space - 116MB is required.) Click *Next*.
. In the Configure window, set these parameters that are specific to your site:
 ** *OnCommand Insight* *Server Name or Address* - hostname or IP address to identify the OnCommand Insight Server. The RAU uses this name/IP to open a communications link with the server. If you specify a hostname, make sure it can be resolved through DNS.
 ** *Acquisition Unit Name* - unique name that identifies the RAU.
 ** *OnCommand Insight Secured Remote Acquisition Port (HTTPS)* - Port used by Remote Acquisition Units to send environment change information to the OnCommand Insight server. This setting should match the value entered when installing the OnCommand Insight server and must be the same on all RAUs.
 ** Enter the _acquisition_ user password. 
. Review your selections. Click *Back* to go back and make changes. Click *Next*.
. Click *Install* to start the installation.
+
Wait for the installation to complete. This should take approximately 5 to 10 minutes.

== After you finish

When the installation is complete, a final window appears. Click the *Start Remote Acquisition Service* box to start the RAU, and click *Finish* to end this operation.

If your data begins acquiring, you are all set; you do _not_ need to synchronize the Server and RAU as noted below.


== Synchronize Server and RAU

IMPORTANT: After installing the Remote Acquisition Unit, you *must* synchronize the RAU with the OnCommand Insight Server. Follow these steps:

. On the OnCommand Insight Server system, start the *SecurityAdmin* tool in interactive mode
+
 securityadmin -i
 
. Change the password for the _acquisition_ user for the Insight Server to a password of your choice. *Make note of this password* as you will require it below. 

. Restart the server/LAU.

. On the Remote Acquisition Unit (RAU) system, start the *SecurityAdmin* tool in interactive mode. You will need the password you noted from step 2 above.
+
 securityadmin -i
 
. Change the password for the _acquisition_ user to the password used in step 2.

. Restart the RAU.
