---
permalink: install-windows/task_restoring_the_data_warehouse_database.html
sidebar: sidebar
keywords: 
summary: 'When you back up the Data Warehouse database, Data Warehouse creates a .zip file that you can later use to restore that same database.'
---
= Restoring the Data Warehouse database
:icons: font
:imagesdir: ../media/

[.lead]
When you back up the Data Warehouse database, Data Warehouse creates a `.zip` file that you can later use to restore that same database.

== About this task

When you restore the Data Warehouse database, you can restore user account information from the backup as well. User management tables are used by the Data Warehouse report engine in a Data Warehouse only installation.

== Steps

. Log in to the Data Warehouse Portal at `+https://fqdn/dwh+`.
. From the navigation pane on the left, click *Backup/Restore*.
. In the *Restore Database and Reports* section, click *Browse* and locate the `.zip` file that holds the Data Warehouse backup.
. It is a best practice to leave both of the following options selected:
 ** *Restore database*
+
Includes Data Warehouse settings, data marts, connections, and user account information.

 ** *Restore reports*
+
Includes custom reports, predesigned reports, changes to predesigned reports that you made, and reporting settings you made in the Reporting Connection.
. Click *Restore*.
+
Do not navigate away from the restore status. If you do, the restore status is no longer displays and you receive no indication when the restore operation is complete.

. To check the upgrade process, view the `dwh_upgrade.log` file, which is in the following location: `<install directory>\SANscreen\wildfly\standalone\log`.
+
After the restore process finishes, a message appears just below the *Restore* button. If the restore process is successful, the message indicates success. If the restore process fails, the message indicates the specific exception that occurred to cause the failure. In this case, contact technical support and provide them with `dwh_upgrade.log` file. If an exception occurs and the restore operation fails, the original database is automatically reset.
+
[NOTE]
====
If the restore operation fails with a "`Failed upgrading cognos content store`" message, restore the Data Warehouse database without its reports (database only) and use your XML report backups to import your reports.
====
