---
permalink: install-windows/task_installing_the_oncommand_insight_data_warehouse_and_reporting.html
sidebar: sidebar
keywords: 
summary: 'The installation is self-contained and includes the elements required to run and operate OnCommand Insight Data Warehouse \(DWH\) and the Reporting utilities.'
---
= Installing OnCommand Insight Data Warehouse and Reporting
:icons: font
:imagesdir: ../media/

[.lead]
The installation is self-contained and includes the elements required to run and operate OnCommand Insight Data Warehouse (DWH) and the Reporting utilities.

== Before you begin

Please note the following before installing or upgrading.

* If you are upgrading, back up DWH.
* You must have local __administrator__permissions to install OnCommand Insight Data Warehouse with Reporting.
* Make sure Windows Modules Installer service is enabled (either automatically or manually).
* If installing on non-C: drive, Short File Names must be enabled. If it is not enabled, the installer will enable it.
* For the Db2 component, the Db2 User can be either _domain_ user or _local_ user.
 ** If the Db2 User is a _domain_ user, you must have the following:
  *** Db2 User must have been already created, and you must know the user name and password
  *** As the user who is installing DWH with Reporting, you must be able to query the Db2 User. You can validate this using the command:
   **** `net user <db2 user name> /domain`
 ** If Db2 User is a _local_ user, you must have the following:
  *** User name and password for the user which will be used to run as Db2 User. If this user does not exist, installation will create it.
 ** [NOTE]
====
The Db2 user name as well as the Windows login name have the following restrictions:
* Valid characters are: 'A' through 'Z'; 'a' through 'z'; '0' through '9'; '#'; '@'; '_'; '!'; ' '('; ')'; '{'; '}'; '-'; and '.'.
* If using the special characters '!'; ' '('; ')'; '{'; '}'; '-'; and '.' you must use all uppercase letters for the user name.
* The first character in the string must be an alphabetic character, @, #, or $; it cannot be a number or the letter sequences _SYS_, _DBM_, or _IBM_
* It cannot exceed 128 bytes in length.
* It cannot be USERS, ADMINS, GUESTS, PUBLIC, LOCAL or any SQL reserved word.

====

* The Db2 user can not be the same as the user performing the installation.

== Steps

. Log in to the Data Warehouse server using an account with administrator privileges.
. Download the Data Warehouse with Reporting .zip file and extract the files to an installation folder.
. Navigate to the _<download location>\oci_dwh_installer\_ folder and run the _install_oci_dwh.bat_ script.
+
[NOTE]
====
With OnCommand Insight 7.3.10 and later, you must run the script for proper DWH/Reporting installation. Do not run the .MSI installation executable.
====

. Enter the Db2 domain, or press Enter for local domain.
. Enter the Db2 User name. See above for user name restrictions.
. Enter the password for the Db2 user. Re-enter the password when prompted.
. Enter the installation path for the Db2 component, or press Enter for default.
. You are presented with the information you entered. Verify all settings carefully. Press Enter to start installation.
. If prompted, allow Windows to proceed with the Db2 installation.
. Following Db2 Installation, the DWH installation wizard will run. Follow its directions to install DWH with Reporting.
+
Data Warehouse with Reporting Installation may take up to an hour to complete.
