---
permalink: install-windows/task_locating_ibm_cognos_documentation.html
sidebar: sidebar
keywords: 
summary: 'For basic information such as how to start and stop the Reporting portal software, see the IBM Cognos documentation installed with the product. You can search with a web browser for information about any of the IBM Cognos reporting products, such as Query Studio, Report Studio, Business Insight, or Business Insight Advanced on the IBM website in the Information Centers for those software products.'
---
= Locating IBM Cognos documentation
:icons: font
:imagesdir: ../media/

[.lead]
For basic information such as how to start and stop the Reporting portal software, see the IBM Cognos documentation installed with the product. You can search with a web browser for information about any of the IBM Cognos reporting products, such as Query Studio, Report Studio, Business Insight, or Business Insight Advanced on the IBM website in the Information Centers for those software products.

== Steps

. To locate the IBM Cognos documentation installed with OnCommand Insight, navigate to this directory.
+
`<install_dir\>\cognos\c10_64\webcontent\documentation\help_docs.html`

. You can also display topics describing individual IBM Cognos windows used in the OnCommand Insight Reporting Portal. Click the *?* icon on the window toolbar.
