---
permalink: install-windows/uninstalling-the-remote-acquisition-unit-software.html
sidebar: sidebar
keywords: 
summary: 'You must uninstall the existing version of the remote acquisition unit software before you can upgrade to a new version. You should perform this task on all remote acquisition unit servers in your environment.'
---
= Uninstalling the remote acquisition unit software
:icons: font
:imagesdir: ../media/

[.lead]
You must uninstall the existing version of the remote acquisition unit software before you can upgrade to a new version. You should perform this task on all remote acquisition unit servers in your environment.

[NOTE]
====
*It is strongly recommended to back up the vault* before uninstalling OnCommand Insight. 
*You must back up the vault* if you will be upgrading OnCommand Insight.

See the link:../config-admin\/security-management.html[SecurityAdmin Tool] instructions for more information.
====

== Steps

. Log in to the remote acquisition unit server.
. Ensure that all of the OnCommand Insight windows on the server are closed.
. Open the *Uninstall a Program* feature from the control panel and select the OnCommand Insight Remote Acquisition Unit program for removal.
. Click *Uninstall* and follow the prompts.
