---
permalink: install-windows/upgrading-remote-acquisition-servers.html
sidebar: sidebar
keywords: 
summary: 'After you complete all prerequisite tasks, you can log in to the remote acquisition unit server and run the installation package to complete the upgrade. You must perform this task on all remote acquisition servers in your environment.'
---
= Upgrading remote acquisition unit servers
:icons: font
:imagesdir: ../media/

[.lead]
After you complete all prerequisite tasks, you can log in to the remote acquisition unit server and run the installation package to complete the upgrade. You must perform this task on all remote acquisition servers in your environment.

== Before you begin

* You must have upgraded OnCommand Insight.
* The OnCommand Insight installation package must be located on the server.

[NOTE]
====
You must back up the vault prior to upgrading. 

See the link:../config-admin\/security-management.html[SecurityAdmin Tool] instructions for more information about the vault.

====

== Steps

. Log in to the remote acquisition unit server using an account that has Windows local administrator permissions.
. Back up the vault. 
. Locate the Insight installation package (`RAU-x64-version_number-build_number.msi`) using Windows Explorer and double-click it.
+
The OnCommand Insight Setup Wizard displays.

. Move the installation wizard progress window away from the center of the screen and away from the installation wizard window so that any generated errors are not hidden from view.
. Follow the Setup Wizard prompts.
+
It is a best practice to leave all the defaults selected.

== After you finish

* To verify if the upgrade is successful or if errors are generated, check the upgrade log in the following location: `<install directory>\SANscreen\bin\log`.
* Use the `securityadmin` tool to restore the saved security
+
configuration. For more information, search for securityadmin in the OnCommand Insight
+
Documentation Center: http://docs.netapp.com/oci-73/index.jsp

* Clear your browser's cache and history to ensure that you are receiving the latest data from the server.
