---
permalink: install-windows/verifying-the-data-warehouse-and-reporting-installation.html
sidebar: sidebar
keywords: 
summary: 'After a successful OnCommand Insight Data Warehouse installation, you should ensure that all of the DWH and Reporting services are available in your Microsoft Windows services.'
---
= Verifying the Data Warehouse and Reporting installation
:experimental:
:icons: font
:imagesdir: ../media/

[.lead]
After a successful OnCommand Insight Data Warehouse installation, you should ensure that all of the DWH and Reporting services are available in your Microsoft Windows services.

== Steps

. From the Windows Start menu, select menu:Control Panel[System and Security > Administrative Tools > Services].
. Ensure that the following entries appear in the list of services:
+
|===
| Name / State| Description
a|
*SANScreen Server / Running*
a|
The OnCommand Insight DWH server
a|
*MySQL / Running*
a|
The OnCommand Insight SQL database
a|
*IBM Cognos / Running*
a|
IBM Cognos Content Database
a|
*DB2- DB2COPY1 - DB2-0 / Running*
a|
Manage Db2 databases
a|
*DB2 Governor (DB2COPY1) / Not running*
a|
Collects statistics for applications connected to Db2 databases.
a|
*DB2 License Server (DB2COPY1) / Not running*
a|
Monitors Db2 license compliance.
a|
*DB2 Management Service (DB2COPY1) / Running*
a|
Manages Db2 registry entries for compatibility with earlier Db2 copy versions.
a|
*DB2 Remote Command Server (DB2COPY1) / Running*
a|
Supports remote Db2 command execution.
a|
*IBM Secure Shell Server for Windows / Not running*
a|
IBM Secure Shell Server for Windows
|===
