---
permalink: install-linux/concept_network_traffic_generated_by_oncommand_insight.html
sidebar: sidebar
keywords: 
summary: 'The network traffic that OnCommand Insight generates, the amount of processed data traversing the network, and the load that OnCommand Insight places on devices differ based on many factors.'
---
= Network traffic generated by OnCommand Insight
:icons: font
:imagesdir: ../media/

[.lead]
The network traffic that OnCommand Insight generates, the amount of processed data traversing the network, and the load that OnCommand Insight places on devices differ based on many factors.

The traffic, data, and load differ across environments based on the following factors:

* The raw data
* Configuration of devices
* Deployment topology of OnCommand Insight
* Different inventory and performance data source polling intervals, which can be reduced to allow for slow devices to be discovered or bandwidth to be conserved

The raw configuration data that OnCommand Insight collects can vary significantly.

The following example illustrates how the configuration data can vary and how traffic, data, and load are affected by many configuration factors. For example, you might have two arrays each having 1,000 disks:

* Array 1: Has 1,000 SATA disks all 1 TB in size. All 1,000 disks are in one storage pool, and there are 1,000 LUNs, all presented (mapped and masked) to the same 32 nodes in an ESX cluster.
* Array 2: Has 400 2-TB data disks, 560 600-GB FC disks, and 40 SSD. There are 3 storage pools, but 320 of the FC disks are used in traditional RAID groups. The LUNs carved on the RAID groups use a traditional masking type (symmaskdb), while the thin provisioned, pool-based LUNs use a newer masking type (symaccess). There are 600 LUNs presented to 150 different hosts. There are 200 BCVs (full block replica volumes of 200 of the 600 LUNs). There are also 200 R2 volumes, remote replica volumes of volumes that exist on an array in a different site.

These arrays each have 1,000 disks and 1,000 logical volumes. They might be physically identical in the amount of rack space they consume in the data center, and they might even be running the same firmware, but the second array is much more complex in its configuration than the first array.
