---
permalink: install-linux/data-warehouse-server-requirements-linux.html
sidebar: sidebar
keywords: 
summary: 'The Data Warehouse server must run on a computer that is compatible with established hardware and software requirements. You must ensure that Apache web server or reporting software is not already installed on this machine.'
---
= Data Warehouse server requirements
:icons: font
:imagesdir: ../media/

[.lead]
The Data Warehouse server must run on a computer that is compatible with established hardware and software requirements. You must ensure that Apache web server or reporting software is not already installed on this machine.

[NOTE]
====
Sizing for OnCommand Insight has multiple dependencies, such as number of assets in your environment, amount of historical data retained, and more. The following data warehouse sizing examples are guidelines only; they represent some of the environments in which Insight has been tested. Changing any of these or other factors in the environment can change the sizing requirements for Insight.
====

It is recommended to contact your Sales Engineer for detailed sizing guidance before installing or upgrading Insight.

*Examples:*

|===
| Environment factors:| Disk space, CPUs, and Memory tested:
a|
18 storage arrays3,400 VMs

4,500 switch ports

a|
200 GB hard disk8 cores

32 GB RAM

a|
110 storage arrays11,500 VMs

14,500 switch ports

a|
300 GB hard disk8 cores

48 GB RAM

|===
*Requirements:*

|===
| Component| Required
a|
Operating system
a|
A computer running a licensed version of one of the following, that is running no other application-level software:

* Red Hat Enterprise Linux 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5, 8.8, 9.2, 9.4
* CentOS 7.2, 7.5, 7.6, 7.7, 7.8, 7.9, CentOS 8 Stream, CentOS 9 Stream
* Oracle Enterprise Linux 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5, 8.8, 8.10, 9.4

a|
Virtual machine (VM)
a|
This component can run in a virtual environment, provided that the CPU and memory resources for your instance are reserved.
a|
CPU
a|
8 - 40 CPU cores
a|
Memory
a|
32 GB - 2 TB RAM
a|
Available Disk Space
a|
200 GB - 512 GB disk space There should be at least 50 GB of free disk space in the `/var/lib` partition and 25 GB of free disk space in the `/opt` and `/var/log` partitions.

a|
Network
a|

* 100 Mbps or 1 Gbps Ethernet connection
* Static IP address
* For the OnCommand Insight DWH server process, ports 80, 443, 1098, 1099, 3873, 8083, and 4444 through 4446
* For MySQL, port 3306

|===
