---
permalink: install-linux/installing-a-remote-acquisition-unit-rau-linux.html
sidebar: sidebar
keywords: 
summary: 'You can install one or more Remote Acquisition Units \(RAUs\) in your OnCommand Insight environment. Acquisition units run in the network that accesses \(through modules called data sources\) and collect data from different devices in the data center.'
---
= Installing a Remote Acquisition Unit
:icons: font
:imagesdir: ../media/

[.lead]
You can install one or more Remote Acquisition Units (RAUs) in your OnCommand Insight environment. Acquisition units run in the network that accesses (through modules called data _sources_) and collect data from different devices in the data center.

== Before you begin

You must have completed all of the installation prerequisites.

At least one port must be open and available between the RAU server and the OnCommand Insight Server to forward change information to the server. If you are unsure about this, validate it by opening a Web browser on the RAU computer and directing it to the OnCommand Insight server:

----
 https://< OnCommand Insight Server hostname >:< acquisition_port >
----

The acquisition port defaults to 443, but it might have changed during the server installation. If the connection is successful, you see a OnCommand Insight response page, indicating an open and available port between the RAU and the OnCommand Insight server.

For environments using Network Address Translation or Port Address Translation (NAT/PAT: i.e, any translation of IP addresses), Insight only supports insertion of an RAU between NAT and the Device.

* Supported: OnCommand Insight \-> NAT \-> RAU \-> Device
* Unsupported: OnCommand Insight \-> RAU \-> NAT \-> Device

== Steps

. Log in to the RAU server using an account with sudo privileges.
. Navigate to the directory on the server where the installation files are located and type the following command:
+
`unzip oci-rau-<version>-linux-x86_64.zip`

. You can view syntax, command arguments, and parameter usage for `oci-install.sh`:
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh --help`

. Run the installation script:
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh`

. Read the License Agreement, accept it, and then follow the prompts.
+
After you answer all the prompts, the installation begins and should take approximately 10 minutes, depending on the applications installed.
