---
permalink: install-linux/installing-your-insight-licenses.html
sidebar: sidebar
keywords: 
summary: 'After you receive the license file containing the Insight license keys from NetApp, you can use the setup features to install all of your licenses at the same time.'
---
= Installing your Insight licenses
:icons: font
:imagesdir: ../media/

[.lead]
After you receive the license file containing the Insight license keys from NetApp, you can use the setup features to install all of your licenses at the same time.

== About this task

Insight license keys are stored in a `.txt` or `.lcn` file.

== Steps

. Open the license file in a text editor and copy the text.
. Open Insight in your browser.
. On the Insight toolbar, click *Admin*.
. Click *Setup*.
. Click the *Licenses* tab.
. Click *Update License*.
. Copy the license key text into the *License* text box.
. Select the *Update (most common)* operation.
. Click *Save*.
. If you are using the Insight consumption licensing model, you must check the box to *Enable sending usage information to NetApp* in the *Send usage information* section. Proxy must be properly configured and enabled for your environment.

== After you finish

After installing the licenses, you can perform these configuration tasks:

* Configure data sources.
* Create OnCommand Insight user accounts.
