---
permalink: install-linux/installing-oncommand-insight-data-warehouse-linux.html
sidebar: sidebar
keywords: 
summary: 'The installation is self-contained and includes the elements required to run and operate OnCommand Insight Data Warehouse \(DWH\).'
---
= Installing OnCommand Insight Data Warehouse
:icons: font
:imagesdir: ../media/

[.lead]
The installation is self-contained and includes the elements required to run and operate OnCommand Insight Data Warehouse (DWH).

== Before you begin

You must have completed all of the installation prerequisites.

== About this task

Data Warehouse has Cognos reporting capabilities. If you install Insight on a Linux server, you can use these capabilities, however, only if you install the Data Warehouse on a Windows server. For information about installing the Data Warehouse on Windows and Cognos reporting capabilities, refer to the _OnCommand Insight Installation Guide for Microsoft Windows_.

== Steps

. Log in to the Data Warehouse server using an account with sudo privileges.
. Navigate to the directory on the server where the installation files are located and type the following command:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`
+
Ensure that you check the version number of the installation file; the version number might be different than the one shown in the command.

. You can view syntax, command arguments, and parameter usage for `oci-install.sh` before you begin the installation:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Run the installation script:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`
+
When installing Insight Server or Data Warehouse on CentOS 9 Stream, Red Hat Enterprise Linux 9.4, or Oracle Linux 9.4, you must first change to the directory containing the installer file and then execute the install command using the "--install-mysql-dependencies" command-line option:

 cd /tmp/oci-7.3.16.1.297-linux-x86_64
 sudo ./oci-install.sh --install-mysql-dependencies 
 
. Read the License Agreement, accept it, and follow the prompts.

== Results

After you answer all the prompts, the installation begins and should take approximately 10 minutes, depending on the applications installed.


== Synchronize Server and DWH

IMPORTANT: After installing the Data Warehouse, you *must* synchronize the Data Warehouse with the OnCommand Insight Server. Follow these steps:

. On the OnCommand Insight Server system, start the *SecurityAdmin* tool in interactive mode
+
 securityadmin -i
 
. Change the password for the _inventory_ and _dwh_internal_ users to passwords of your choice. *Make note of these passwords* as you will require them below. 

. Restart the DWH service

. On *each Connector* start the *SecurityAdmin* tool in interactive mode. You will need the passwords you noted from step 2 above.
+
 securityadmin -i
 
. Change the passwords for the _inventory_ and _dwh_internal_ users to the passwords used in step 2.

. Restart services on the Connectors.

. Add the Connectors to DWH, using the passwords for _inventory_ and _dwh_internal_ users from step 2
