---
permalink: install-linux/installation-prerequisites.html
sidebar: sidebar
keywords: 
summary: 'Before you install OnCommand Insight, you must download the current software version, acquire the appropriate license, and set up your environment.'
---
= Installation prerequisites
:icons: font
:imagesdir: ../media/

[.lead]
Before you install OnCommand Insight, you must download the current software version, acquire the appropriate license, and set up your environment.

Before installing OnCommand Insight, ensure that you have the following:

* OnCommand Insight software files in the downloaded installation package for the current version
* A license to operate the downloaded OnCommand Insight version
* The minimum hardware and software environment
+
The current product might consume additional hardware resources (due to enhanced OnCommand Insight product functionality) that were not consumed with earlier versions of the OnCommand Insight product.

* A deployment plan that includes the hardware and network configurations for the OnCommand Insight Server, Data Warehouse and Reporting, and remote acquisition units.

