---
permalink: install-linux/installing-the-oncommand-insight-server-linux.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight Server is installed by using the command line.'
---
= Installing the OnCommand Insight Server
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight Server is installed by using the command line.

== Before you begin

You must have completed all of the installation prerequisites.

== Steps

. Log in to the Insight server using an account with sudo privileges.
. Navigate to the directory on the server where the installation files are located and type the following command:
+
`unzip oci-<version>-linux-x86_64.zip`
+
Ensure that you check the version number of the installation file; the version number might be different than the one shown in the command.

. You can view syntax, command arguments, and parameter usage for `oci-install.sh` :
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --help`

. Run the installation script:
+
`sudo ./oci-<version>-linux-x86_64/oci-install.sh`
+
Note: When installing on *Red Hat Enterprise Linux version 9.4*, the _install-mysql-dependencies_ option must be included on the command line:
 +
`sudo ./oci-<version>-linux-x86_64/oci-install.sh --install-mysql-dependencies`

. Read the License Agreement, accept it, and follow the prompts.
. If you are using the Insight consumption licensing model, you must enable sending of usage information to NetApp. Enter `Y` at this prompt.

== Results

After you answer all the prompts, the installation begins and should take approximately 10 minutes, depending on the applications installed.


== Synchronize Server with DWH and RAU

IMPORTANT: After installing the Remote Acquisition Unit and/or the Data Warehouse, you *must* synchronize the RAU/DWH with the OnCommand Insight Server. Follow the steps as noted below:

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau[Synchronize Server and RAU (Windows)]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh[Synchronize Server and DWH (Windows)]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau[Synchronize Server and RAU (Linux)]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh[Synchronize Server and DWH (Linux)]

