---
permalink: install-linux/oncommand-insight-installation-instructions.html
sidebar: sidebar
keywords: 
summary: 'Installation requires installing several OnCommand Insight components, Insight Server, and Data Warehouse.'
---
= Insight installation instructions
:icons: font
:imagesdir: ../media/

[.lead]
Installation requires installing several OnCommand Insight components, Insight Server, and Data Warehouse.

The installation includes the following major tasks:

* Downloading the OnCommand Insight installer
* Installing OnCommand Insight server
* Installing licenses
* Optionally, installing DWH and Reporting (must be installed on a separate machine or virtual machine. Reporting requires Microsoft Windows.)
* Optionally, installing a remote acquisition unit (RAU), which acquires information from your device resources that reside behind a firewall, are located at a remote site, or are on a private network

After installation, you must configure Insight to acquire information about your environment. The tasks required are described in the _OnCommand Insight Configuration and Administration Guide_.
