---
permalink: install-linux/reference_remote_acquisition_unit_server_requirements.html
sidebar: sidebar
keywords: redhat
summary: 'You must install a Remote Acquisition Unit \(RAU\) to acquire information from SAN devices that are behind a firewall, at a remote site, on a private network, or in different network segments. Before you install the RAU, you should ensure that your environment meets RAU operating system, CPU, memory, and disk space requirements.'
---
= Remote Acquisition Unit server requirements
:icons: font
:imagesdir: ../media/

[.lead]
You must install a Remote Acquisition Unit (RAU) to acquire information from SAN devices that are behind a firewall, at a remote site, on a private network, or in different network segments. Before you install the RAU, you should ensure that your environment meets RAU operating system, CPU, memory, and disk space requirements.

|===
| Component| Requirement
a|
Operating system
a|
A computer running a licensed version of one of the following, that is running no other application-level software:

* Red Hat Enterprise Linux 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS 7.2, 7.5, 7.6, 7.7, 7.8, 7.9, CentOS 8 Stream
* Oracle Enterprise Linux 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5

A dedicated server is recommended.

a|
CPU
a|
4 CPU cores
a|
Memory
a|
16 GB RAM
a|
Available disk space
a|
40 GB
a|
Network
a|
100 Mbps /1 Gbps Ethernet connection, static IP address, IP connectivity to all FC devices, and a required port to the OnCommand Insight server (80 or 443).
a|
Permissions
a|
Sudo permissions on the RAU server

|===
