---
permalink: install-linux/reference_insight_java_ui_requirements.html
sidebar: sidebar
keywords: 
summary: 'Because the OnCommand InsightJava UI Client operates in a Java run-time environment on your computer, it is important that you ensure that your environment meets specific operating system, CPU, and memory requirements.'
---
= Insight Java UI requirements
:icons: font
:imagesdir: ../media/

[.lead]
Because the OnCommand InsightJava UI Client operates in a Java run-time environment on your computer, it is important that you ensure that your environment meets specific operating system, CPU, and memory requirements.

To access the Java UI Client, you must install the Java run-time environment (JRE) on your computer.

For OnCommand Insight 7.3.2 and later, the 64-bit version of the Java Runtime Environment (JRE) is required to run the Insight Java client.

|===
| Component| Requirement
a|
Operating system
a|
Any Java 8-enabled machine. The Java-based client supports Windows, Macintosh, and Linux platforms.
a|
CPU
a|
1.8 GHz or faster is required.
a|
Memory
a|
2 GB or more is recommended. If you are monitoring the performance of complex data centers (over 50,000 switch ports), the server requires more memory. This is applicable only if the Perform license is installed.

|===
