---
permalink: install-linux/task_submitting_an_online_technical_support_request.html
sidebar: sidebar
keywords: 
summary: 'If you have problems with the Insight installation, as a registered support customer, you can submit an online technical support request.'
---
= Submitting an online technical support request
:icons: font
:imagesdir: ../media/

[.lead]
If you have problems with the Insight installation, as a registered support customer, you can submit an online technical support request.

== Before you begin

Using your corporate email address, you must register as a support customer to obtain online support services. Registration is performed through the support site (http://support.netapp.com).

== About this task

To assist customer support in solving the installation problem, you should gather as much information as possible, including these items:

* Insight serial number
* Description of the problem
* All Insight log files
* Screen capture of any error messages

== Steps

. Create a `.zip` file of the information you gathered to create a troubleshooting package.
. Log in to the support site at http://mysupport.netapp.com/[mysupport.netapp.com] and select *Technical Assistance*.
. Click *Open a Case*.
. Follow the instructions to your package of data.

== After you finish

You can use *Check Case Status* on the Technical Assistance page to follow your request.
