---
permalink: install-linux/upgrading-data-warehouse.html
sidebar: sidebar
keywords: 
summary: 'After upgrading the Insight server software, you must upgrade your data warehouse software.'
---
= Upgrading Data Warehouse software
:icons: font
:imagesdir: ../media/

[.lead]
After upgrading the Insight server software, you must upgrade your data warehouse software.

== About this task

[NOTE]
====
It is strongly recommended to back up the vault and the database prior to upgrading DWH. 

See the link:../config-admin\/security-management[SecurityAdmin Tool] instructions for more information about the vault.

====

== Steps

. Log in to the Data Warehouse (DWH) server using an account with sudo privileges.
. Download the Insight DWH software from the NetApp support site.
. Navigate to the download directory and type the following command:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`
+
Ensure that you have the correct the version number of the installation file.

. You can view syntax, command arguments, and parameter usage for `oci-install.sh` :
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Run the installation script:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

. Accept the License Agreement and follow the prompts.

