---
permalink: install-linux/upgrading-ethernet-monitoring-units.html
sidebar: sidebar
keywords: 
summary: 'After upgrading the Insight server software, you must upgrade your ethernet monitoring software.'
---
= Upgrading Ethernet Monitoring Unit software
:icons: font
:imagesdir: ../media/

[.lead]
After upgrading the Insight server software, you must upgrade your ethernet monitoring software.

== About this task

[NOTE]
====
Ethernet Monitoring Unit (EMU) is not supported in OnCommand Insight version 7.3.12 and later.
====

== Steps

. Log in to the Ethernet Monitoring Unit (EMU) server using an account with sudo privileges.
. Download the Insight EMU software from the NetApp support site.
. Navigate to the download directory and type the following command:
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`
+
Ensure that you have the correct the version number of the installation file.

. You can view syntax, command arguments, and parameter usage for `oci-install.sh` :
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. Run the installation script:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. Accept the License Agreement and follow the prompts.
