---
permalink: how-to-use-these-release-notes.html
sidebar: sidebar
keywords: 
summary: 'These release notes list the new features and functionalities that are introduced in the latest release of OnCommand Insight.'
---
= OnCommand Insight Release Notes
:icons: font
:imagesdir: ./media/

[.lead]
These release notes list the new features and functionalities that are introduced in the latest release of OnCommand Insight.

It is a best practice for all users to review these release notes.

* If OnCommand Insight is already running in your environment, you should familiarize yourself with relevant topics from all releases between your current release and this new release before upgrading OnCommand Insight.
* If this is the first deployment of OnCommand Insight in your environment, you should also see the OnCommand Insight guides at the NetApp Support Site to learn how to use the product.

== How to use the release notes when upgrading OnCommand Insight

Before you upgrade OnCommand Insight, you should read all the notes that describe known problems, fixed issues, customer-requested enhancements, and any deprecated software to verify that these changes do not impact your environment. You should check whether there are any changes between the versions of the software that are in your upgrade path. For example, if you are upgrading from OnCommand Insight 7.0.3 to the latest version of the software, you should be aware of any changes in the software between OnCommand Insight 7.0.3 and the OnCommand Insight version to which you are upgrading.

== Location of the most up-to-date version of the Data Source Support Matrix

The OnCommand Insight Data Source Support Matrix is updated with each service pack release. The latest version of the document can be found at the https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf[NetApp Support Site].

== Location of the most up-to-date Documentation

The OnCommand Insight Documentation is now delivered in a NetApp Documentation Center. The Documentation Center provides one-stop access to the Release Notes, user documentation, and many other resources. Visit the Documentation Center at https://docs.netapp.com/oci-73/index.jsp[http://docs.netapp.com/oci-73/index.jsp]
