---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-3-5.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.'
---
= Product enhancements and changes for OnCommand Insight 7.3.5
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.

OnCommand Insight provides intelligent operations and business insights across the enterprise. The software enables the rationalization and optimization of costs, reduces risks, and provides advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.

== Active Directory changes

OnCommand Insight 7.3.5 supports Microsoft Azure Active Directory and Secure Active Directory users.

For all Secure Active Directory (i.e. LDAPS) users, you must use the AD server name exactly as it is defined in the certificate. You can not use IP address for secure AD login.

== Third-party software library changes

The following third-party software changes are included in this release:

* ElasticSearch has been upgraded to 6.3.1
* Wildfly has been updated to 14.0.1
* Cognos has been upgraded to 11.0.13
* Java has been upgraded to 8u192
* MySQL has been upgraded to 5.7.24

== Data Source changes

The following new data sources are supported in 7.3.5:

* EMC Solutions Enabler - Support VMAX Linked clones
* HP 3Par - Support remote copies
* OpenStack - Support Gnocchi API for performance

The following data sources are promoted out of beta status in 7.3.5:

* Brocade BNA
* Oracle ZFS performance collection
* Microsoft Azure

== Corrected issues in OnCommand Insight 7.3.5

OnCommand Insight 7.3.5 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-5823
a|
Changing the browser language sometimes shows the wrong day of the week in Insight date calendars.
a|
Day-of-week is now correctly displayed in time selectors.
a|
ICI-5698
a|
Data Warehouse ETL Capacity job times out in some environments.
a|
A new index has been added that improves ETL timing in cases where the Capacity job fails after an inordinate amount of time.
a|
ICI-5567
a|
Planning tasks failing due to invalid timestamps for volume replicas.
a|
When validating tasks, entries in the volume replicas database were not being correctly updated, causing some tasks to fail. Insight 7.3.5 correctly writes the entries.
a|
ICI-5555
a|
REST API call to assets/applications/\{id}/assets does not return hypervisors.
a|
This is corrected in Insight 7.3.5.
a|
ICI-5527
a|
During automatic device resolution, if two previously-identified hosts are being collapsed into one, and each of the previous hosts had a different policy, Insight attempted to insert both policies, causing an exception.
a|
Insight now ensures that only one policy will survive.
a|
 
a|
 
a|
 
|===

== Known problems and limitations

* *Data Warehouse installation failure*
+
If the Data Warehouse installation fails to complete successfully, but has already created the Informix user and Informix group, you must delete them from the operating system before re-trying the installation:

 ** Computer management > Users > Informix
 ** Computer management > Groups > Informix-Admin
You must also ensure that the "Sanscreen" folder is completely removed before re-installing.

+
This is a requirement for releases 7.3.3, 7.3.4, and 7.3.5.

== Documentation notes

The Insight Documentation Center contains all of the published user documentation. For secure sites that do not allow unlimited access to the Internet, you can download PDF or EPUB versions of the documents. The following changes are included in the documentation:

* *Smart card for Data Warehouse*
+
Because of differences between earlier and recent versions of the Insight reporting engine, the instructions for Importing CA-signed SSL certificates for Cognos and DWH have been split into the following sections in the Configuration and Administration guide:

 ** Importing CA-signed SSL certificates for Cognos and DWH (Insight 7.3.2 and earlier)
 ** Importing CA-signed SSL certificates for Cognos and DWH (Insight 7.3.3, 7.3.4)
 ** Importing CA-signed SSL certificates for Cognos and DWH (Insight 7.3.5 and later)

* *Storage Manager Dashboard topic*
+
The OnCommand Insight Reporting Guide for 7.3.3 did not include a section for the Storage Manager Dashboard (SMD). This information was still available in the Reporting Guide for version 7.3.2 and earlier. Beginning with 7.3.5, the SMD section has been included in both guides.

* *FC import field order*
+
The instructions for Importing Fibre Channel device identification from a CSV file previously listed the import fields in incorrect order. The documentation has been corrected to show the proper field order below:
+
|===
a|
WWN
a|
IP
a|
Name
a|
Type
|===
