---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-3-7.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.'
---
= Product enhancements and changes for OnCommand Insight 7.3.7
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.

OnCommand Insight provides intelligent operations and business insights across the enterprise. The software enables the rationalization and optimization of costs, reduces risks, and provides advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.

== Updated Anomaly Detection Engine

OnCommand Insight 7.3.7 includes an updated Anomaly Detection Engine (ADE). The following ADE server requirements have changed:

|===
a|
Memory and CPU
a|
8 cores, 64 GB memory
|===
The 7.3.7 version of OnCommand Insight is not compatible with previous versions of the ADE. You must uninstall the previous version from your ADE server and install the 7.3.7 version.

Note that your previous Anomaly Detection modeling and scores will be lost and will have to start "`learning`" again. Insight uses up to two weeks of historical data to start learning.

The OnCommand Insight 7.3.7 ADE installation has an integrated option to configure a firewall to restrict access to the ADE from the OCI Server only.

== Additional Audited Events

The following additional events can now be viewed on the Admin > Audit page:

* Create/Modify/Remove a User
* User Logout
* Enable/Disable Backup
* Enable/Disable ASUP
* Security Re-Key/Change System Password
* Annotation Rule Order
* Add/Remove Annotation on Asset
* Annotation Assigned to Asset via Rule

== Third-party software library changes

The following third-party software changes are included in this release:

* ElasticSearch has been upgraded to 6.7.2
* Wildfly has been updated to 16.0.0
* Cognos has been upgraded to 11.1.2
* Java has been upgraded to 8u212
* MySQL has been upgraded to 5.7.26

== Data Source change

The following new data source is supported in 7.3.7:

* HPE Nimble Storage provides beta support for inventory and performance

== SOAP API Deprecated

The SOAP API included with earlier versions of OnCommand Insight has been deprecated. SOAP API is not included with OnCommand Insight 7.3.7.

== Java UI with Java 11

OnCommand Insight cannot launch the Java UI with JRE version 11 and up due to deprecation of the Java Web Start executable (javaws.exe).

== Security Warning during upgrade

If you upgrade from a previous Insight version with re-keyed security, you may receive a message that you are using default keys. This can happen if one of the Insight components (for example, the Server or Local Acquisition Unit) is still using a default security key.

== Corrected issues

This version of OnCommand Insight corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-6316
a|
Data source fails update due to read-only state on extended-data index
a|
See https://kb.netapp.com/app/answers/answer_view/a_id/1078969/loc/en_US and contact NetApp Support if you have additional questions.
a|
ICI-6313
a|
Unable to login to Web UI. After rebooting the server, login succeeds.
a|
The system may become unresponsive due to excessive scripted logins. Limit the number and/or rate of scripted logins.
a|
ICI-6177
a|
Circular symbolic links may be created during inline upgrade on Linux.
a|
Circular links are no longer created during inline upgrade.
a|
ICI-6147
a|
Dashboards not refreshing table the first time after the dashboard loads, when the table is grouped by a field with all rows collapsed, when variable text filtering is used.
a|
Table widget logic has been updated to filter immediately and update number of items and groups when using the variable text filter.
a|
ICI-6143
a|
Performance Archive failing with 'Error: For input string: ""; '
a|
Corrected in latest Wildfly update.
a|
ICI-6140
a|
Underscore (_) in domain name causing Remote Acquisition Unit installation to fail.
a|
Installer now validates underscores in domain names, allowing installation to continue.
a|
ICI-6132

ICI-6129

a|
Unable to load topology view in web UI, or topology view renders inconsistently for objects with large or complex topology.
a|
Topology rendering now handles complex topologies more efficiently.
a|
ICI-6130
a|
Duplicate key error in 7.3.5 related to table au_attrs env variable entry that already exists
a|
Spaces around keys were not being properly trimmed, causing some keys to be added instead of properly handled as duplicates of existing keys. Spaces around keys are now handled more efficiently.
a|
ICI-5996
a|
Intermittent server availability issues.
a|
Memory-intensive processes were not always getting cleaned up correctly, leading to tasks not completing. Memory handling has been optimized to reduce this type of back-up.
a|
ICI-5991
a|
ApplicationTK is zero (0) in vm_hourly_performance_fact and dwh_performance.vm_daily_performance_fact.
a|
This has been corrected in load_vm_hourly_performance_datamart.sql with 7.3.7.
a|
ICI-5958
a|
Rest query that returns extended performance data can crash Linux OCI server over time
a|
Insight caches metadata on extended data attributes retruned in the REST response. Over time, this cache can grow and take up most of the heap. Insight 7.3.7 optimizes handling of this cache to avoid the build-up.
a|
ICI-5733
a|
UNKNOWN port type shown in csv export despite valid port in GUI
a|
This was caused by incorrect processing in the Web UI. This has been fixed in 7.3.7.
|===

== Documentation notes

The Insight Documentation Center contains all of the published user documentation. The following changes are included in the documentation:

The OnCommand Insight Windows installation guide states that Data Warehouse Reporting is not supported on Windows 2016. This note only applies to Insight 7.3.2 and earlier. Insight 7.3.3 and later support Reporting on Windows 2016.
