---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-2-2.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.2.2 includes new and enhanced features, changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.2.2
:experimental:
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.2.2 includes new and enhanced features, changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== Export and import user data

The import and export functions allow you to export annotations, annotation rules, queries, performance policies, and custom dashboards to one file. This file can then be imported into different OnCommand Insight servers. The export and import functions are supported only between servers that are running the same version of OnCommand Insight.

During the import operation, data is added, merged, or replaced, depending on the objects and object types that are being imported.

* Annotation Types
 ** Adds an annotation if no annotation with the same name exists in the target system.
 ** Merges an annotation if the annotation type is a list, and an annotation with the same name exists in the target system.
 ** Replaces an annotation if the annotation type is anything other than a list, and an annotation with the same name exists in the target system.

+
[NOTE]
====
If an annotation with the same name but with a different type exists in the target system, the import fails. If objects depend on the failed annotation, those objects may show incorrect or unwanted information. You must check all annotation dependencies after the import operation is complete.
====
* Annotation Rules
 ** Adds an annotation rule if no annotation rule with the same name exists in the target system.
 ** Replaces an annotation rule if an annotation rule with the same name exists in the target system.

+
[NOTE]
====
Annotation rules are dependent on both queries and annotations. You must check all the annotation rules for accuracy after the import operation is complete.
====
* Policies
 ** Adds a policy if no policy with the same name exists in the target system.
 ** Replaces a policy if a policy with the same name exists in the target system.

+
[NOTE]
====
Policies may be out of order after the import operation is complete. You must check the policy order after the import.    Policies that are dependent on annotations may fail if the annotations are incorrect. You must check all the annotation dependencies after the import.
+
====
* Queries
 ** Adds a query if no query with the same name exists in the target system.
 ** Replaces a query if a query with the same name exists in the target system, even if the resource type of the query is different.

+
[NOTE]
====
If the resource type of a query is different, after the import, any dashboard widgets that use that query may display unwanted or incorrect results. You must check all query-based widgets for accuracy after the import.     Queries that are dependent on annotations may fail if the annotations are incorrect. You must check all the annotation dependencies after the import.
+
====
* Dashboards
 ** Adds a dashboard if no dashboard with the same name exists in the target system.
 ** Replaces a dashboard if a dashboard with the same name exists in the target system, even if the resource type of the query is different.

+
[NOTE]
====
You must check all query-based widgets in dashboards for accuracy after the import.    If the source server has multiple dashboards with the same name, they are all exported. However, only the first one will be imported to the target server. To avoid errors during import, you should ensure that your dashboards have unique names before exporting them.
+
====

== ASUP status in Health page

The ASUP status is displayed in the Health page (*Admin* > *Health*). The status messages include:

* ASUP Enabled (displays last successful ASUP time, if available)
* ASUP Disabled
* ASUP Failed (displays last attempt time as well as last successful ASUP time, if available)

== Removed Proxy settings from the ASUP configuration section

Proxy settings are included in a separate section because they are not specific to OnCommand Insight ASUP. You can access the Proxy settings section (*Admin* > *Setup* > *Backup / ASUP / Proxy*) to configure a proxy for:

* ASUP
* Disk model updates
* Service pack check
* Version update check

== Custom email targets for performance policies

You can set customized email addresses for email alerts about specific performance policy breaches. Customized email targets override the default addresses. If no email address is specified, the default addresses are used.

== Additional time options for performance policies

You can select from a greater range of times for the alerts related to performance policy violations. The choices for "`Apply after a window of`" are as follows:

* First Occurrence
* 5 minutes
* 10 minutes
* 15 minutes
* 30 minutes
* 45 minutes
* 1 hour
* 2 hours

== Query owner user name is now displayed

The user name of the query owner is available for display, sorting, and filtering.

== Link to data source Support matrix

In order to ensure that users have access to the latest version of the Data Source Support Matrix, the Data Source Support Matrix is no longer embedded as a static file within the OnCommand Insight product. Instead, the link to the Data Source Support Matrix points to a URL on the NetApp Support Site. Your server must be connected to the Internet in order to access the Data Source Support Matrix.

== Service pack update notification

In Online Help, "`Check for updates`" informs you if any service packs are available for your version of Insight. This notification is also available on the Health page (*Admin* > *Health*).

== Used capacity ratio

Users can view, filter, and query by "`used capacity ratio (%)`" for the following objects:

* Virtual Machine
* VMDK
* Volume
* Internal Volume
* Storage pool
* Datastore

== REST API maintenance version

Previously, the Insight REST API version number was in the <major version>.<minor version> format--for example, "`1.3`". With Insight 7.2.2, the REST API version also includes a maintenance version--for example, 1.3.1. You must be aware of the following information:

* Code that works with major.minor version numbers that are older than the current version will work with the new version--for example, code that is written for 1.3.1 will work with 1.3.2.
* Code for the current major.minor.maintenance version is not guaranteed to work with earlier versions--for example, code that is written for 1.3.2 is not guaranteed to work with 1.3.1.

== Object ID for annotation import

In Insight 7.2.2, you can use the object ID as a key for annotation import, along with the object name or IP. The object ID is entered in the format `+id-><id+`.

== Default encryption ciphers

In Insight 7.2.2, the default encryption ciphers are changed to take advantage of TLS 1.2. The default cipher suites are SHA 2 (SHA 256) only.

== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* MySQL is upgraded to version 5.5.49
* Java is upgraded to version 1.8.92
* Apache Groovy upgraded to 2.4.4

== Customer-requested enhancements

The following customer-requested enhancements are included in this release.

|===
| Request ID| Description
a|
IFR-2463
a|
Previously, Brocade ENC_in and ENC_out error counters were collected and aggregated into "`other errors`" that were not displayed anywhere. In Insight 7.2.2, these counters are separated from the aggregated "`other errors`", and are visible with other counters on asset pages, in queries, and in performance policies, as well as in the switch port performance data mart in Cognos reporting.
a|
IFR-2400
a|
Throughput, latency, and IOPS counters in Data Warehouse were previously integers, which were presented in hourly or daily averages as "`0`" in cases where they were more likely to be presented by the Insight server as decimal values such as 0.2, 0.45, etc. In Insight 7.2.2, the performance counters in Data Warehouse match the granularity that is presented in the operational server.
a|
IFR-2469
a|
The following fields are added to the summary section of the Node asset page:

* Serial Number
* Memory
* Processors

|===

== Data Source enhancements

The following data sources are added:

* The Infinidat InfiniBox (HTTP) data source provides support for inventory.
* The NetApp StorageGRID data source provides beta support for inventory.
* The EMC RecoverPoint data source provides beta support for inventory.

You can see the latest OnCommand Insight Data Source Support Matrix for more information: https://mysupport.netapp.com/NOW/products/interoperability/[mysupport.netapp.com/NOW/products/interoperability/]

== Anomaly detection changes

The following changes have been made:

The three anomaly score icons have been replaced by a blue bar; the bar represents a score between 0 and 100. The bar is present on the application landing page, in the widget, and in the application list page.

The values of the blue bars that represent the significance value that an asset has contributed to the anomaly score have changed:

* The old values represented: 1 bar = 1-50; 2 bars = 51-75; 3 bars = 76-100
* In Insight 7.2.2, the values represent: 1 bar = 1-33; 2 bars = 34-67; 3 bars = 68-100

== Anomaly Detection monitoring status

Anomaly detection monitoring status is available in application queries, widgets and asset pages. For each application, you will see one of the following:

* *OK*
+
No problems are detected.

* *Learning*
+
The anomaly detection server is fetching up to 14 days of performance data, and loading it into the anomaly detection engine.

* *Exceeds maximum assets*
+
The maximum number of assets being monitored for an application has been exceeded. No more than 4000 assets can be monitored for an application. Monitoring is paused until the number of assets is less than or equal to 4000. Reduce the number of assets being monitored to continue monitoring.

* *Failed*
+
The connection to the anomaly detection server has failed.

* *Not monitored*
+
Monitoring is turned off for the application. In queries and widgets, this field is left blank.

== Upgrading the anomaly detection engine

Newer releases of OnCommand Insight may contain a new release of the anomaly detection engine. In order to preserve anomaly detection configuration data and anomaly score data following an upgrade of the software, you must follow these instructions. Refer to the release notes to determine whether your Anomaly detection needs to be upgraded.

Before you begin

* The system must be running OnCommand Insight 7.2 or later.
* The system must be running version 1.4.x of the anomaly detection engine.

IMPORTANT: Failure to execute the steps of this task in sequential order might result in the loss of the anomaly detection configuration data and anomaly score data stored on the Insight server.

Steps

. Back up the existing version of OnCommand Insight to preserve the anomaly detection registrations, application monitoring, anomaly history, and so on.
. Shut down the OnCommand Insight server.
+
IMPORTANT: Failure to shut down the OnCommand Insight server before uninstalling the anomaly detection software results in the loss of the anomaly detection configuration data and anomaly score data stored on the Insight server.

. Uninstall the anomaly detection software:
+
`sudo /usr/bin/oci-prelert-uninstall.sh`
+
The system displays a "`failure to unregister`" message. You can ignore this message.

. Install the newer version of OnCommand Insight by using the upgrade process.
+
See the OnCommand Insight Installation Guide for instructions.

. Restart the OnCommand Insight server.
+
The system reports that applications are "`failing to monitor`". You can ignore these failures.

. Install the new version of the anomaly detection software on a system that has the same IP address as the previous machine that was running the anomaly detection software:
+
`sudo /usr/bin/oci-prelert-install.sh`
+
See the OnCommand Insight Installation Guide for instructions.
+
The anomaly detection software is successfully registered with the OnCommand Insight server.

== Running custom scripts in Data Warehouse

Starting with OnCommand Insight 7.2.2, Data Warehouse allows customers to create jobs that can run custom scripts that prepare customized data in Data Warehouse.

To prevent the custom script from being deleted during a Data Warehouse upgrade, do not store the script in the SANscreen directory.

Steps

. In Data Warehouse, select menu:DWH Admin[Schedule].
. Select the**Script enabled** check box.
. Enter the absolute path of the script name in the**Script Location** text box.
. Click *Save*.

Result

The Data Warehouse job engine schedules the task to run a "`Custom scripting`" job. The job is scheduled to run after an ETL and avoiding other conflicting background processes. The job is not run by a "`Build from history`" operation.

== Preserving custom Cognos settings during a Data Warehouse upgrade

Custom Cognos settings, such as non-default SMTP email settings, are not automatically backed up as part of a Data Warehouse upgrade. You need to manually document and then restore the custom settings following an upgrade.

Prior to upgrading Data Warehouse, prepare a checklist with any custom Cognos settings that you want to preserve, and review the list prior to upgrading the system. After the upgrade is complete, you can restore the values manually to return them to the settings in the original configuration.

== Corrected issues in OnCommand Insight 7.2.2

OnCommand Insight 7.2.2 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-3843
a|
The database field that stores virtual disk natural keys in the data warehouse had a smaller size than in the Insight server database. This caused connection errors after upgrading to 7.2.
a|
The database field size is now identical in the data warehouse and in the server.
a|
ICI-3667
a|
OIDs of some SNMP trap variables did not match with those defined in the MIB.
a|
Variables for the following traps have been updated to match with those defined in the MIB: sanViolationTrapUp, sanViolationTrapDown, sanChangeTrap, violationTrapUp, violationTrapDown, AhrFailureTrap. (Fixed in 7.1.3)
a|
IBG-9070
a|
MySQL installation fails under certain conditions related to SELinux being enabled.
a|
The SELinux recursive link issue was corrected, and there are no longer SELinux conditions that cause MySQL installations to fail.
|===

== Warning when configuring user access to systems

Security best practices dictate that administrators configure the host operating system to prevent the interactive login of non-administrator/standard users.

== Changes to published documentation

Additional information has become available after the documentation provided with this release was published. You should use the updated information in conjunction with the materials that were originally published.

== Correction to the annotation import table

In the OnCommand Insight 7.2 Configuration and Administration guide, the annotation import table has incorrect values for qtree and share entries.

The correct qtree and share entries are as follows:

|===
| Type| Name or Key
a|
Share
a|
`+<Storage Name>-><Internal Volume Name>-><Share Name>-><Protocol>+`[`+->+``<Qtree Name >`]`<Qtree>` is optional if there is a default qtree.

a|
Qtree
a|
`+<Storage Name>-><Internal Volume Name>-><Qtree Name>+`
|===

== Correction to the command for importing annotation values

In the OnCommand Insight 7.2 Configuration and Administration guide, the java command for importing annotation values is incorrect. The correct command is as follows:

java -jar rest-import-utility.jar [-uusername] [-ppassword] [-aserver name or IP address] [-bbatch size] [-ccase sensitive:true/false] [-lextra logging:true/false] csv filename

== Incorrect data types listed in Data Warehouse datamart schema

The Data Warehouse data base schema lists incorrect data types in some fact tables.

The data type for throughput, IOPs, and latency is now DOUBLE, but is listed in the datamart schema as INT in the following fact tables:

* Application_volume_hourly_performance_fact
* Disk_daily_performance_fact
* Disk_hourly_performance_fact
* Host_vm_daily_performance_fact
* Host_vm_hourly_performance_fact
* Host_volume_hourly_performance_fact
* Internal_volume_ hourly_performance_fact
* Internal_volume_daily_performance_fact
* Storage_node_hourly_performance_fact
* Storage_node_daily_performance_fact
* vm_hourly_performance_fact
* vm_daily_performance_fact
* volume_ hourly_performance_fact
* volume_daily_performance_fact

== How historical data is retained in Data Warehouse

Data is maintained in Data Warehouse according to a schedule.

Data Warehouse retains historical data based on the data marts and granularity of the data, as shown in the following summary:

|===
| Data mart| Measured object| Granularity| Retention period
a|
Performance marts
a|
Volumes and internal volumes
a|
Hourly
a|
14 days
a|
Performance marts
a|
Volumes and internal volumes
a|
Daily
a|
13 months
a|
Performance marts
a|
Application
a|
Hourly
a|
13 months
a|
Performance marts
a|
Host
a|
Hourly
a|
13 months
a|
Performance marts
a|
Switch performance for port
a|
Hourly
a|
5 weeks
a|
Performance marts
a|
Switch performance for host, storage and tape
a|
Hourly
a|
13 months
a|
Performance marts
a|
Storage node
a|
Hourly
a|
14 days
a|
Performance marts
a|
Storage node
a|
Daily
a|
13 months
a|
Capacity marts
a|
All (except individual volumes)
a|
Daily
a|
13 months
a|
Capacity marts
a|
All (except individual volumes)
a|
Monthly representative
a|
14 months and beyond
a|
Inventory mart
a|
Individual volumes
a|
Current state
a|
1 day (or until next ETL)
|===
After 13 months, which is configurable, Data Warehouse retains only one record per month instead of one record per day for capacity, performance, and resource data in the following tables:

* Chargeback fact table (dwh_capacity.chargeback_fact)
* File System Utilization fact table (dwh_fs_util.fs_util_fact)
* Host fact table (dwh_sa.sa_host_fact)
* Internal Volume Capacity fact table (dwh_capacity.internal_volume_capacity_fact)
* Ports fact table (dwh_ports.ports_fact)
* Qtree Capacity fact table (dwh_capacity.qtree_capacity_fact)
* Storage and Storage Pool Capacity fact table (dwh_capacity.storage_and_storage_pool_capacity_fact)
* Volume capacity fact table (dwh_capacity.vm_capacity_fact)
* Storage Node Hourly Performance (storage_node_hourly_performance_fact) and Storage Node Daily Performance (storage_node_daily_performance_fact) fact tables
