---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-1-4.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.1.4 provides changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.1.4
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.1.4 provides changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== Installing OnCommand Insight on the ReFS file system is currently not supported

The Resilient File System (ReFS) is a Microsoft file system introduced with Windows Server 2012. This file system is not compatible with OnCommand Insight because it does not support hard links, which are required by Cassandra. Windows installation of OnCommand Insight is only supported on the NTFS file system.

== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* MySQL is upgraded to version 5.5.49
* Java is upgraded to version 1.8.92

[NOTE]
====
MySQL Connector/J was update to version 5.1.38 in OnCommand Insight 7.1.3, but it was not documented in the release notes. This version is also available in the 7.1.4 release.
====

== Corrected issues in OnCommand Insight 7.1.4

OnCommand Insight 7.1.4 corrects an issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-3970
a|
Qtrees with the same API results show different capacity values.
a|
Corrected the handling of zero Qtree capacity values.
|===

== Data Source enhancements

The following data sources have been added since OnCommand Insight 7.1.3 was released:

* The NetApp StorageGrid data source provides beta support for inventory.
* The EMC ECS data source provides beta support for inventory.

Enhancements to existing data sources include the following:

* The HDS HiCommand Device Manager provides beta support for using Tuning Manager for performance.
* The EMC Celerra (SSH) data sources contains SSH improvements.
* The EMC VNX (SSH) data sources contains SSH improvements.
* The VMware vSphere (Web Services) data source adds support for NFS 4.1 as a protocol hosting VMs.
