---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-3.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.3 includes new and enhanced features, changes to data sources, updates to non-NetApp software, corrected issues, and a new documentation delivery method. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.3
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.3 includes new and enhanced features, changes to data sources, updates to non-NetApp software, corrected issues, and a new documentation delivery method. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== Whats new?

* A dramatic increase in data retention from 7 to 90 days.
* Increased flexibility to search and display operational information with new widgets, for quicker identification of resource behavior.
* Custom dynamic dashboards that enable sharing of information on the operational aspects of the environment.
* Consolidation and streamlining of the configuration functions in the web interface
* An additional data collection mechanism including any SNMP-enabled device, e.g. an Ethernet switch

== *Increased data retention from 7 to 90 days*

With OnCommand Insight 7.3.0, data retention has been increased to 90 days, allowing you to view performance data over longer periods and making it easier to identify operational trends over time. With this increased retention comes an ability to reduce the space for performance data backups with an archival function.

== Custom dashboards

OnCommand Insight 7.3.0 introduces dynamic, resizable dashboard layouts based on our new widgets. Increased filtering and display options allowing you to view data in various ways.

* Dashboard data visualization includes a 3h, 24h, 3d, 7d, 30d, or a custom time range.
* Common variables can be simultaneously applied to all widgets on a dashboard.

For more information, see "Creating custom dashboards" in the _"How To" guides_.

== Widgets

The new widgets allow far simpler and quicker searches of data across objects and metrics. Data can now be grouped and multiple search results can be displayed in the same widget. These allow comparisons to be made across metrics on the same object or across objects with related metrics.

== Device Resolution in web UI

Device resolution has migrated from the Java UI to the web UI. The updated web interface for device resolution provides an easy to use interface that allows you to see all of your devices, create rules, set schedules for rules runs, create and enable or disable device resolution schedules and view devices that have been identified, unidentified, or partially identified after you load and run data sources.

For more information, see "`Device resolution`" in the _Configuration and administration guide_.

[NOTE]
====
If you have inactive Auto Resolution rules in the system you are upgrading from, these rules will be deleted during the upgrade. To preserve inactive Auto Resolution rules, activate the rules (check the box) before the upgrade is performed.
====

== Additional data collection

A new generic collection API has been introduced to push data, including dimension data and attributes, with examples available for SNMP-enabled devices.

For more information, see "How to collect SNMP Integration data" in the _"How To" guides_

== Additional changes

* NAS paths are created when virtual machines have access to the backend shares.
* The Atmos service level has been renamed to Object Storage service level.
* Data Warehouse changes include the following
 ** The Data Warehouse now includes a health monitor.
 ** dwh_inventory.nas_cr_logical table is added to the Inventory data mart and dwh_inventory.nas_logical is removed.
+
Any Insight 7.2 reports containing the NFS path table are preserved.

 ** {blank}
  *** {blank}
+
== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* Elasticsearch 5.1.1 replaces Cassandra
* MySQL is upgraded to 5.7.17
* JBOSS is upgraded to Wildfly 10

== Legacy licenses are no longer supported

NetApp no longer supports port based licenses in any release after June 2016. The support for port based licenses is removed in OnCommand Insight7.3. License entitlement checks for TB based licenses check capacity numbers, but no longer convert the ports monitored.

For Insight 7.3, only the following license codes are supported. Customer with only the retired license codes must contact NetApp to get a new licenses.

|===
| License Part| Display Name| Unit
a|
IASR
a|
OnCommand Insight Assure
a|
TB
a|
IPER
a|
OnCommand Insight Perform
a|
TB
a|
IPLN
a|
OnCommand Insight Plan
a|
TB
a|
IDIS
a|
OnCommand Insight Discover
a|
TB
a|
ARAP
a|
Additional Report Authoring Packages
a|
No Units
a|
IHUP
a|
OnCommand Insight Host Utilization Pack
a|
Compute Resources Counts
|===

== Customer-requested enhancements

The following customer-requested enhancements are included in this release.

|===
| IFR| Description
a|
IFR-2194 IFR-2347 IFR-2348

a|
Expose Application and Business entities in the VM Performance data mart to enable drag and drop report creation.

a|
IFR-2302
a|
Expose vCPU and Memory in the VM performance data mart for drag and drop reporting to provide trending on these metrics.
a|
IFR-1708
a|
Add storage pool status to the Inventory data mart.
|===

== Replication Assurance removed

Replication Assurance has been removed from OnCommand Insight. This includes removing the following views in the Java UI:

* DR paths
* Replication dashboards
* DR rules
* DR Violations

== Performance views removed from the Java UI

Performance views for the following features have been removed from the Java UI:

* Storage Array Performance
* Storage Virtualization Performance
* Host Virtualization Performance
* Switch Performance

== Data Source enhancements

The following new data source is supported:

* SNMP integration data source

*Bulk actions on Data Sources*

Insight now supports performing some actions on data sources in bulk. You can perform the following actions on multiple data sources, simultaneously:

* Delete data sources
* Postpone and resume polling
* Poll

== Corrected Issues in OnCommand Insight 7.3

OnCommand Insight 7.3 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-4122
a|
Export of query brings down the Insight server
a|
Documentation assigns a limit to exporting table data. No more than 10,000 rows of table data can be exported at one time.
a|
ICI-3754
a|
Scheduled DB backup is not occurring at the time listed on the Insight web console.
a|
The Insight web console now the contains following information: `The main backup occurs weekly between Sunday 10:00 PM and Monday 2:00 AM at the desired location.`
a|
ICI-2955
a|
Need to document the Server Health page
a|
Server Health page is documented in the _Configuration and Administration Guide_
a|
ICI-4520
a|
During an upgrade, the DWH db restore fails at the reporting layer and no DWH db restore is available; the upgrade must be restarted from the beginning.
a|
The Data Warehouse db is restored and the following messages are displayed: `DWH database was restored, so ETL will run successfully. Reports restoration and upgrade failed. Save your DWH backups and contact NetApp support to discuss reports restoration.``Reason: Failed to restore from 'dwh_x.x.x.x.zip. Failed to connect to reporting server, server might be down. Confirm reporting server availability and try again.`

a|
ICI-4093
a|
ASUP failing with "Nonrepeatable request" error
a|
When ASUP is configured for HTTP and the backup file is larger than 2 GB, the file is split and sent in slices of 2 GB. Occasionally ASUP transfers over HTTP fail with a "`Nonrepeatable request`" error. To resolve this issue the default ASUP over HTTP slice size has been changed from 2 GB to 100 MB.
a|
ICI-4401
a|
Power VM virtual disks not correctly recognised in Data Warehouse
a|
"Prior to OCI 7.3.0, the OCI Data warehouse (DWH), incorrectly assumed that all Raw Device Mapping (RDM)-like volumes should have a reference to a datastore.

RDM - (i.e, the guest operating system consumed the volume directly from the storage array with low/no interference or indirection from the hypervisor the guest sits on)

This assumption was VMware centric. Other hypervisor platforms such as AIX PowerVM can have "VMs" consume storage in a RDM-like fashion.

The OCI DWH has been changed in 7.3.0 to properly handle RDMs with no such relationship. This may result in more RDM relationships being visible in the DWH in 7.3.0 and above.

a|
ICI-4144
a|
HDS HiCommand Runtime exception error
a|
The issue was due to obsolete hv_paths which were referencing dead ports.

OCI corrects this problem by ensuring that when the merger runs, connectivity records are only created for active ports.

|===

== Known problems and limitations

Known issues identify some unexpected and potentially undesired behaviors that affect functionality in this OnCommand Insight release. You must be aware of these issues to avoid or troubleshoot them.

== Inline Upgrade to 7.3.0 fails with custom certificates

If you are upgrading OCI and your system uses custom certificates, you cannot perform an inline upgrade. You need to use the following procedure to upgrade to OCI 7.3:

. Backup the OCI database to a safe location outside of the install path
. Uninstall the old OCI version
. Install OCI version 7.3
. Restore the backup you created in step 1
. Build and import a new custom certificate

== Custom reports might require modifications

This release of Insight removed the Cognos model versioning of packages for reports. This change might require customers to modify custom reports that were authored on older versions of models. Some custom reports will need to use new field names if they are using fields that were renamed in OnCommand Insight 7.3.

== Uninstalling Anomaly Detection software does not unregister the software from the OCI server

When OCI 7.3 is running with a 7.2.x version of the Anomaly Detection software registered, a problem is encountered when you uninstall the Anomaly Detection software. The uninstall appears to complete successfully, but the System Health Page reports that the Anomaly Detection software is still registered.

You must unregister the software from the server before attempting to install a newer version of Anomaly Detection software, otherwise the installation will fail.

You can unregister the Anomaly Detection software from the OCI server using the Server Health page.

== Upgrade to MySQL 5.7 introduces new reserved names that might break reports

OnCommand Insight 7.3 includes an upgrade to MySQL version 5.7. This release of MySQL introduces new reserved names: `virtual` and `generated`. NetApp has updated these fields from `virtual` and `generated` to `isVirtual` and `isGenerated`.

This change affects customers who leverage reports that are built in SQL when they upgrade to 7.3. If a customer were to upgrade to 7.3 and have reports from the PS catalog or from the Automaton Storefront that have SQL-driven queries, with the virtual or generated flags, they will break.

Customers who have reports from the PS catalog that are affected by this change should be notified pro-actively by PS.

Customers customers that have Reports that use the `virtual` and `generated` flags need to update their reports.

The following tables and views are effected by the change from *virtual* to *isVirtual*:

* dwh_capacity.disk_group_dimension
* dwh_capacity.storage_and_storage_pool_capacity_fact
* dwh_capacity.storage_and_storage_pool_capacity_future_fact
* dwh_capacity.storage_pool_dimension
* dwh_capacity.volume_dimension
* dwh_capacity.volume_fact_current
* dwh_capacity.volume_capacity_fact
* dwh_capacity.volume_history_capacity_fact
* dwh_inventory.disk_group
* dwh_inventory.storage
* dwh_inventory.storage_pool
* dwh_inventory.volume
* dwh_performance.capacity_volume_fact_current
* dwh_performance.storage_pool_dimension
* dwh_performance.volume_dimension

The following tables are views will be affected by the change from *generated* to *isGenerated*:

* dwh_inventory.switch
* dwh_inventory.switch_port
* dwh_inventory.virtual_switch
* dwh_performance.port_dimension
* dwh_performance.switch_dimension
* dwh_ports.port_dimension
* dwh_ports.switch_dimension

== A date page variable cannot be used in a widget

You can create a date page variable, but it cannot be used in a widget.

== After upgrade the Reporting link on the web UI toolbar is empty

After you complete an upgrade to OnCommand Insight 7.3, the Reporting link on the web UI toolbar is empty. You must run ETL and then restart the server to get the link updated in the Web UI.

== Changes to published documentation

This release of OnCommand Insight includes the following documentation changes:

*Installation Guides contain new sizing guidelines*

Due to enhanced functionality, storage and other sizing requirements have changed since previous releases of OnCommand Insight. Please refer to the prerequisites section of the Installation Guides for more information. Contact your Sales Engineer for detailed sizing guidance.

*Documentation Center*

The OnCommand Insight 7.3 documentation is delivered in a NetApp Documentation Center that provides access to the Release Notes, user documentation, and many other resources. The Documentation Center provides one-stop access to information that was previously in separate PDFs. You can search for information more easily, filter search results to show only the content you want, and get to your answers more quickly. All major features of the Documentation Center are supported for languages in which content is available.

The Documentation Center provides:

* Search with filtering that allows you search all documents or specified document.
* You can rate individual topics, provide feedback, and send us comments to let us know what you think.
* The ability to print individual pages, topics, or groups of topics.
* A tour that introduces all of the Documentation Center features.

Visit the Documentation center: https://docs.netapp.com/oci-73/index.jsp[http://docs.netapp.com/oci-73/index.jsp]

== Frequently Asked Questions

This new guide for OnCommand Insight 7.3 introduces OnCommand Insight through questions and answers about the product. The questions and answers address several topics that are helpful for customers that are new to Insight. The guide describes general information about OCI, licensing, supported devices, ease of use, how performance troubleshooting is performed, and tools that can be integrated with OCI.

== "How To" Guides

The "How To" Guides is a set of guides that describe how to perform common operational and business planning tasks that you might use to monitor and manage your multivendor Hybrid IT infrastructure. The topics in this collection cover several areas:

* Initial configuration steps you need to perform after you install Insight software
* Configuring the system so that assets are visible
* Creating dashboards to view data
* Creating policies to monitor performance
* Configuring your system to create a Chargeback report
* How to collect SNMP integration data
* Troubleshooting topics
