---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-3-3.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.'
---
= Product enhancements and changes for OnCommand Insight 7.3.3
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight is designed to simplify operational management of hybrid IT infrastructures on public and private clouds as well as traditional on-premise environments.

OnCommand Insight provides intelligent operations and business insights across the enterprise. The software enables the rationalization and optimization of costs, reduces risks, and provides advanced troubleshooting and analytics across the multi-vendor infrastructure of systems, networks, and storage.

== New assets available in the web UI

The following assets are now available in the web UI:

* *Qtree table on Application asset landing pages*
+
The Application landing page now displays a table for Qtrees, showing Qtree name, type, used capacity, IOPS total, and associated internal volume.

== UI enhancements

The following improvements and enhancements have been added to the Insight web UI:

* *Movable and resizable columns*
+
Columns in tables on the query page and in dashboard table widgets can now be resized and moved. To resize, hover the mouse over the header of the column until a blue bar appears. Place the mouse over the bar and drag it right or left. To move a column, click on the column header and drag it right or left.
+
When adding more columns than can fit on the screen, a horizontal scroll bar appears, allowing you to view all columns. These improvements remove the ellipsis from the screens. (IFR3308, IFR3251, IFR3220, IFR3533, IFR3534, IFR3535)

* *Time aggregation for bar chart widget and single-value widget*
+
Time aggregation options are available for bar chart widget and single-value widget. You can choose to aggregate data in these widgets by Avg, Min, Max, Sum, or by the Last data point collected. Time aggregation is available when you choose to roll up data by any of the available methods.

* *Additional metrics available*
+
Cache hit ratio counters are available for storage assets for use in widgets and queries.
+
Cache Utilization and Pending Writes are available for HDS VSP/G1000 devices.
+
VMAX3 StorageGroup information is available as an extended attribute.
+
The following extended VM counters are available:

 ** CPU Co-Scheduling Delay Time
 ** CPU Idle Time
 ** CPU Total Wait Time
 ** Waiting to be Scheduled Time
 ** CPU Demand to Entitlement

* *StorageGrid data source replaced*
+
A new StorageGrid data source is introduced with this release of Insight. The new data source collects more data than the previous version. You must delete the old version of the data source and configure the newer version to collect the additional data.
+
In the data warehouse, the new StorageGrid data is reported as traditional storage, and can be used in the chargeback datamart.

* *Removal of object storage asset type*
+
Object storage data is no longer searchable in the UI. Queries or dashboard widgets configured with object storage data will display an error message in 7.3.3 and prompt you to remove or re-create the widget/query.
+
StorageGrid asset data can now be found as traditional storage objects.

== Third-party software library changes

The following third-party software changes are included in this release:

* ElasticSearch has been upgraded to 5.6.8
* Wildfly has been updated to 12.0.0
* Cognos has been upgraded to 11.0.9. This version contains a new user interface.
* Java has been upgraded to 8.0.172
* MySQL has been upgraded to 5.7.22

== Data Source changes

The following new data sources are supported in 7.3.3:

* Brocade FOS 8.3 firmware provides support for inventory.
* Brocade Network Advisor provides beta support for inventory and switch performance.
* Nutanix adds beta support for performance.

The following data sources are promoted out of beta status in 7.3.3:

* EMC VNXe performance
* Oracle ZFS inventory

== Audit Logs accessible by preview Rest API

Insight 7.3.3 provides access to Audit Logs using preview REST API.

Insight includes a number of preview REST APIs. In the REST API help, these are shown with a yellow exclamation mark ("!") stating that the preview API is subject to change. When including these APIs in your scripts, be aware that future releases of Insight may change the syntax of these APIs, which can cause scripts to fail.

== Corrected issues in OnCommand Insight 7.3.3

OnCommand Insight 7.3.3 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
N/A
a|
"Single" or disconnected data points do not show in graphs or charts until you hover the mouse over them.
a|
Rendering of single data points is improved in 7.3.3. Data points are displayed without the need to hover over them.
a|
ICI-5433
a|
Number of Fabrics reported on REST call do not match the UI
a|
Insight previously listed the fabrics connected to both the storage and the host. With 7.3.3, Insight lists only the fabric connected to the host.
a|
ICI-5420
a|
Date format localization issue with Change Report form results in a form that is not accepted as a valid date format.
a|
The form now contains a valid date format.
a|
ICI-5359
a|
ETL takes progressively longer to complete.
a|
Adding an index to a temporary table results in 'DELETE FROM dwh_inventory.annotation' to run successfully.
a|
ICI-5357
a|
WebUI data source page doesn't load when phantom data sources exist.
a|
Filtering out data sources that do not return a valid type from a getAllDatasources() query corrects this problem.
a|
ICI-5299
a|
Clicking the update button on the DWH LDAP page, resets the password to the default, although it is shown as already entered.
a|
The update operation no longer resets the password to the default.
a|
ICI-5265
a|
Storage manager dashboard main page and detail reports differ on orphaned capacity.
a|
The detailed report now shows both backend and virtual volumes for the Dashboard and the drill down operation.
a|
ICI-5262
a|
Utilization graph shows discrepancy between the node daily performance table and the column 'utilization'.
a|
Utilization in the storage node daily fact table was previously aggregated using MAX instead of AVG. Insight now aggregates using AVG.
a|
ICI-5149
a|
Insight identifies a physical and virtual host representing the same virtual host.
a|
NAS paths are created based on share definitions that require a DNS lookup to match against a discovered VM. Auto resolution deletes Hosts that it created, but later realizes are VMs.
a|
ICI-4264
a|
The HDS HNAS data source does not make internalVolumeID globally unique, while the DWH expects it to be, causing failures in ETL.
a|
The HNAS data source reports the "InternalVolumeId" attribute on internal volumes with a value set to "storage name:file system name"
a|
ICI-5355, ICI-5275, ICI-4531, ICI-4384
a|
Support HDS FMC AcceleratedCompression
a|
Detect if the storage pool is "`AcceleratedCompression`" enabled. If true, report correct capacities and calculate the compression savings.
|===

== Customer requested enhancements in OnCommand Insight 7.3.3

OnCommand Insight 7.3.3 contains several customer-requested enhancements. The enhancements are listed in the following table and in the **UI enhancements**section of this document.

|===
| Issue number| Description| Resolution
a|
IFR-3663
a|
The audit log should be supported and documented via REST to support security teams monitoring and control.
a|
Implemented with a Preview flag in the API documentation indicating this API is subject to change in the future.
a|
IFR-3728
a|
HDS VSP/G1000 Cache Utilization & Pending Writes
a|
Data is only available through export tools. Tuning Mgr is not supported.
|===

== Documentation notes

The Insight Documentation Center contains all of the published user documentation. For secure sites that do not allow unlimited access to the Internet, you can download PDF or EPUB versions of the documents.

* *New Reporting Guide*
+
A new Reporting Guide for 7.3.3 has been added, which reflects the new interface style in Cognos version 11. The previous Reporting Guide is still valid for Insight version 7.3.2.

* *"Beta" data sources indicated in Data Source Support Matrix*
+
The Data Source Support Matrix now includes information for data sources with "Beta" status. The latest OnCommand Insight Data Source Support Matrix can always be found on the NetApp https://mysupport.netapp.com/matrix/#welcome[Interoperability] site.

* *ServiceNow Integration How-To*
+
A How-To for integration with ServiceNow has been added.
