---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-0-3.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.0.3 provides some data source enhancements, new beta data sources, and updates to some non-NetApp software. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.0.3
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.0.3 provides some data source enhancements, new beta data sources, and updates to some non-NetApp software. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== Data source enhancements

* The NetApp Data ONTAP operating in 7-Mode data source supports qtree-to-qtree replication for 7-Mode SnapVault.
* The EMC Symmetrix data source supports Solutions Enabler 8, VMAX 3, and node latency counters.
* The EMC Isilon data source supports node modeling and node performance.
* The NetApp E-Series data source supports ISCSI and node modeling.
* The NetApp data source supports QoS internal volume counters and root-data partitioning for clustered Data ONTAP 8.3.
* The Host and VM File System data source now supports mapping file systems to the HDS AMS array, EMC Symmetrix, and NetApp E-Series.
* The HDS data sources support nondisruptive data migration (NDM).

== New beta data sources

Following are the new beta data sources in this release:

* EMC XtremIO with configuration support
* Dell Compellent with configuration and performance support
* Microsoft Hyper-V performance support

== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* Upgrade to Java version 7 update 75
* Upgrade to Cassandra 2.0.9
