---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-0.html
sidebar: sidebar
keywords: 
summary: 'The major improvement in OnCommand Insight 7.0 is the new web interface based on HTML 5. The new interface is used for all of the standard Insight setup processes, and includes a streamlined data source setup wizard and tools to help you monitor your environment.'
---
= Product enhancements and changes for OnCommand Insight 7.0
:icons: font
:imagesdir: ./media/

[.lead]
The major improvement in OnCommand Insight 7.0 is the new web interface based on HTML 5. The new interface is used for all of the standard Insight setup processes, and includes a streamlined data source setup wizard and tools to help you monitor your environment.

The OnCommand Insight Client (Java UI) has been enhanced and now requires Java 7. The enhanced OnCommand Client (Java UI) can be launched from the web UI and is often used to define policies, thresholds, annotations, and business entities. The Java UI also retains detailed monitoring features in the Violations browser, as well as performance analysis tools, switch migration, and planning capabilities.

The new web UI contains these features:

* *Improved user experience*
+
The new web interface based on HTML 5 enables you to better visualize the IT infrastructure relationships. It is designed to work as well on tablets as on laptops, enabling you to have the information at hand.
+
New dashboards and improved asset search and navigation enable quicker troubleshooting.

* *Enhanced analytics*
+
Visualization of correlated and non-correlated resources simplify and accelerate complex troubleshooting across layers in the platform.

* *Scalable architecture*
+
NoSQL technology to increase the scale of performance management enabling access to more data for faster troubleshooting.

* *Simplified product administration*
+
Simplified installation and upgrade, administration, patch, and health monitoring processes.

== Customer-requested enhancements

Customers requested the following enhancements that are included in the 7.0 release:

|===
| Request ID| Description
a|
9
a|
Update SNMP community string on FC switches.
a|
73
a|
Permit AD primary groups to be used to configure the user access through Insight LDAP settings.
a|
153
a|
Allow access to the Link Reset metric to help the user identify performance problems in the fabric resulting from failures in connectivity.
a|
249
a|
Add a vendor-specific report that lists the EMC VMAX thick LUNs and, therefore, enables users to reclaim the free capacity.
a|
289
a|
Include the ability to exclude VM acquisition by vClusters. This enables users to choose exclusion by vCluster.
a|
622
a|
Add data source cloning for faster setup.
a|
709
a|
Support soft pool limits for the storage pool of XIV arrays. Soft pool limits set for storage pools of IBM XIV can be reported using storage and storage pool data mart.
|===

== New data sources

Support for the following data sources is included in the OnCommand Insight 7.0 release:

* NetApp UM 6.x for clustered Data ONTAP collection
* Node configuration and performance for systems operating in 7-mode

== Deprecated data sources

* Brocade FC Switch Firmware 3.0-4.1 (HTTP)
* Brocade Multi-Protocol Router (SSH)
* Brocade FC Switch Firmware 4.2x and 4.4x (SNMP)
* EMC Enterprise Fabric Connectivity Manager 7, 8.1, 8.6, 8.7, 8.8, 8.9, 9.0, and 9.1
* EMC Solutions Enabler (CLI) with Performance (CLI)
* Engenio E-Series (Firmware 5.x)
* HP XP (CVCLI)
* IBM ESS (ESSCLI)
* IBM Total Storage DS4000 series (firmware 5.x)
* McData Enterprise Fabric Connectivity Manager 7, 8.1, 8.6, 8.7, 8.8., 8.9, 9.0, and 9.1
* NetApp E-Series (firmware 5.x)
* NetApp Unified Manager 5.2-5.3 Annotations (SQL)

== Manual backup command replaced

The manual `backup.cmd` file under SANscreen\backup has been replaced in this release with a manual backup through the new web UI.

If you want to continue to archive automated backups, you can use daily backup features that create a full backup every day and automatically store them in SANscreen\backup\db. If you want to move those backups to a different directory, you can create a customized script for that process.
