---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-2-4.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.2.4 includes new and enhanced features, changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.2.4
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.2.4 includes new and enhanced features, changes to data sources, updates to non-NetApp software, and corrected issues. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== OnCommand Insight Ethernet traffic monitoring

OnCommand Insight 7.2.4 introduces Ethernet traffic monitoring capabilities. The Insight server and a dedicated Ethernet Monitoring Unit (EMU) inspect Ethernet packet headers on a switch adjacent to storage and determine the type of NFSv3 operation being performed, the destination IP address of the operation, and the volumes being addressed. The information allows customers to pro-actively monitor NAS traffic and easily identify the clients that are putting the heaviest loads on specific volumes.

The EMU is a dedicated hardware server connected to the network switches using mirror ports or Switch Port Analyzer 'SPAN' ports. These mirror ports are configured to mirror packets flowing to the ports connected to the storage links. The EMU is designed to parse every packet it receives to determine information about operations and endpoint IP addresses.

Because packets can be dropped, Insight shows Ethernet Monitoring performance data as "`observed`" data, for example, "`Observed Total IOPs`". However, relative counts are still accurate because the percentage of dropped packets is expected to be roughly equivalent across clients.

Periodically, collected data is sent to the Insight server associated with the EMU. Since the Insight server is also acquiring the relevant storage details for the same volumes and potentially the host details, the server merges the EMU data into the standard Insight data model, correlating Volume IDs to discovered Internal Volumes and client IPs to resolved physical hosts or discovered Virtual Machines. OnCommand Insight provides the following information:

* Volumes with the highest number of protocol operations
* Clients driving the protocol operations on specific volumes
* Details of the protocol traffic for each volume and clients over a user defined time period

For OnCommand Insight 7.2.4, only Ethernet/-IPv4/NFSv3 traffic is monitored on NetApp storage systems running ONTAP 9.0, Clustered Data ONTAP, and Data ONTAP 7-Mode.

For more information about Ethernet monitoring, see the OnCommand Insight Configuration and Administration guide and the OnCommand Insight Installation guides.

== Additional capabilities required for Ethernet Monitoring Unit with Data ONTAP 7-mode

The addition of the _security-priv-advanced_ and _cli-vol_ capabilities are required in order for the data source to log in to a Data ONTAP 7-mode system. For more information about the capabilities see KB3012995 at the NetApp support site.

== Requirement to upgrade the anomaly detection engine

If you are upgrading from OnCommand Insight version 7.2.0 or 7.2.1 and you have the anomaly detection engine running on your system, you must upgrade to the newest version of the anomaly detection software. The anomaly detection engine will no longer run if you do not perform this upgrade. If you are upgrading from OnCommand Insight 7.2.2 and have the anomaly detection engine running, you do not need to upgrade the software.

Instructions for upgrading the anomaly detection engine are available in the _OnCommand Insight Installation Guides._

== Requirement when upgrading all OnCommand Insight software

When you upgrade OnCommand Insight software, the upgrade must include the following servers:

* OnCommand Insight server
* Data Warehouse server
* Remote Acquisition Unit servers
* Ethernet Monitoring Unit server

Not all upgrades require you to upgrade the Anomaly Detection server software.

== Vendor terminology mapped to Insight objects

OnCommand Insight 7.2.4 includes a table of object terms for most supported data sources. This table provides a mapping of common vendor-specific terms for objects with the equivalent OnCommand Insight terms. For example, a data source may acquire a "LUN" from a vendor's storage array, which Insight will then report as a "Volume". These terminology mappings are found in the *Vendor-specific data source reference* section of the _Configuration and Administration Guide_ as well as in the Insight Server web UI online help.

== CentOS is supported for Insight 7.2.4

OnCommand Insight 7.2.4 has been qualified on CentOS version 7. Follow the requirements and instructions in the _OnCommand Insight 7.2.3 Installation Guide for Red Hat Enterprise Linux_. All other Red Hat-specific information contained in product documentation and online help is valid for CentOS as well.

== Storage virtualizer improvement

Support for visualizing and troubleshooting storage virtualizers has been improved in the web UI.

== DWH maintenance job improvement

The DWH maintenance jobs engine was redesigned to significantly improve scalability. This change resolves cases where some DWH maintenance jobs (such as purge and optimize) would time out, resulting in transaction rollback errors.

Along with this improvement, maintenance jobs will be automatically enabled.

== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* MySQL is upgraded to 5.5.51
* MySQL JDBC Connector is upgraded to 5.1.39
* Cassandra is upgraded to 2.2.7
* Java is upgraded to 1.8.101

== Data Source Enhancements

The following new data source is supported

* The EMC Elastic Cloud Storage (ECS) provides beta support for inventory.

The following changes have been made to existing data sources:

* The HDS data source now support Disk Groups, as well as Tuning Manager for performance.
* The OpenStack data source now supports VM and VMDK disk latency.
* The VNXe data source provides full support for inventory.
* The NetApp SolidFire 8.1+ data source provides full support for inventory.
* The HNAS data source provides full support for inventory and now includes DiskGroups, Qtrees, and Quotas.

== Corrected Issues in OnCommand Insight 7.2.4

OnCommand Insight 7.2.4 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-3327
a|
When editing the Comments field on a data source asset page, a web UI refresh causes the window to close.
a|
Comments window no longer closes during web UI refresh.
a|
ICI-3776
a|
In some cases, timeouts in the Data Warehouse might occur when running maintenance jobs.
a|
The MySQL parameter `innodb_io_capacity`, set in the `my.cnf` file on the data Warehouse server, has been increased to 1000 to reduce the possibility of timeouts occurring during the execution of maintenance jobs.
a|
ICI-3965
a|
On a switch landing page, attempting to export the NPV Ports table to .csv gives a "`Could not find UrlMapping Object`" error.
a|
NPV table export now works correctly.
a|
ICI-3992
a|
DWH sometimes fails to get inventory from a connector. This is due to the size of the `sanscreen.hv_host_to_nas_share.oid` field being limited to 255 characters. Entries that had more than 255 characters in this field got truncated, resulting in the same oid for different relationships.
a|
Field is increased to 1024 characters in Insight 7.2.4.
a|
ICI-3994
a|
Cassandra service doesn't start. The Cassandra versions previously included with OnCommand Insight contained a problem where temporary compaction files were not all renamed after a kill or crash. This led to a drastic use of temporary space which would eventually cause the cassandra service not to start.
a|
The problem is fixed with the Cassandra version included with Insight 7.2.4.
a|
ICI-4049
a|
Some data sources fail after upgrade to 7.2.2 with"` Failed to run OriginatorUpdateTask`" exception, due to duplicate entries in `volume_storage_sync_originator` table.
a|
Table is fixed in Insight 7.2.4.
a|
ICI-4068
a|
The reporting engine cannot render reports with the `dwh_capacity.vm_dimension.os` field if that field has double-byte characters.
a|
The report renderer can now properly handle double-byte characters.
a|
ICI-4109
a|
Disk Space on Health page doesn't throw alert status in low-space situation
a|
Starting with Insight 7.2.4, the Health Page will show a warning if free disk space is 10% or below.
a|
ICI-4124
a|
Using the REST import tool utility, attempting to set a business entity on an asset without setting the application will error out saying "`Application column empty and Tenant is not. ignoring`". Using the Web UI to set a BE on an asset without an application succeed correctly.
a|
The REST import utility will now correctly handle business entities on assets without applications set.
a|
ICI-4141
a|
Business entities containing periods may be split when added to resources.
a|
Business entities with periods are now correctly handled.
a|
ICI-4197
a|
Copy/Paste of an object with annotation from the Java UI exports the annotation ID instead of display name.
a|
Copy/Paste from Java UI now correctly handles annotation display name instead of ID
a|
ICI-4214
a|
DWH ETL might fail with message "Out of range value for column 'usedCapacityMB' at row 1". This might happen when large databases are processed.
a|
The field type for this column is fixed to now handle very large numbers.
a|
ICI-4279
a|
Java client stops refreshing after using several filters for list-type annotations.
a|
Filtering of list-type annotations is fixed in Insight 7.2.4.
|===

== Known problems and limitations

Known issues identify some unexpected and potentially undesired behaviors that affect functionality in this OnCommand Insight release. You must be aware of these issues to avoid or troubleshoot them.

*Performance charts contain gaps following upgrade to 7.2.x*

Because of changes to processing total performance counters in the 7.2 release of OnCommand Insight, some counters are not available after an upgrade from 7.1.x to 7.2.x, resulting in gaps in the web UI charts. The missing counters will be restored as data is collected over time.

*Installing OnCommand Insight on the ReFS file system is currently not supported*

The Resilient File System (ReFS) is a Microsoft file system introduced with Windows Server 2012. This file system is not compatible with OnCommand Insight because it does not support full Cassandra functionality. Windows installation of OnCommand Insight is only supported on the NTFS file system.

== Changes to published documentation

Additional information has become available after the documentation provided with this release was published. You should use the updated information below in conjunction with the materials that were originally published.

*Correction to VNXe data source:*

The Insight WebUI help states "`The EMC VNXe data source does not currently report fibre channel (FC) ports as belonging to the array, or FC mapping or masking for volumes.`"

This should be corrected to: "`The EMC VNXe data source provides NAS and iSCSI support for inventory; fibre channel volumes will be discovered, but Insight will not report on FC mapping, masking, or storage ports.`" This information is correctly stated in the _OnCommand Insight 7.2.3 Configuration and Administration_ guide.
