---
permalink: product-enhancements-and-changes-for-oncommand-insight-7-1-2.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.1.2 provides customer requested enhancements, changes to data sources, and updates to some non-NetApp software. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.'
---
= Product enhancements and changes for OnCommand Insight 7.1.2
:icons: font
:imagesdir: ./media/

[.lead]
OnCommand Insight 7.1.2 provides customer requested enhancements, changes to data sources, and updates to some non-NetApp software. Becoming familiar with these changes enables you to take advantage of their benefits more efficiently.

== Customer-requested enhancements

Customers requested the following enhancements, which are included in this release:

|===
| Request ID| Description
a|
IFR 2088
a|
Performance is provided at the VMDK level rather than only an aggregated performance at the VM level. This is provided in DWH and in drag-and-drop Cognos reporting.
a|
IFR 1672
a|
Customers with multiple Insight servers and a single DWH can access a single report providing usage versus entitlement across all Insight servers.
a|
IFR 1488
a|
When VM latency is not available, a correlation of VM IOPS with Hypervisor CPU, VM IOPS with Hypervisor latency, and VM IOPS with Hypervisor IOPS is provided for performance troubleshooting and analysis.
a|
IFR 2178
a|
ETL jobs no longer fail when a circular reference of SnapMirror relationships is encountered. When this condition occurs, a warning is entered in the log files.
a|
IFR 1351
a|
Capability to integrate external data into Cognos is provided. By default, the Report Studio "`Allow External Data`" capability is assigned to the Admin user.
|===

== Backup and restore custom tables in Data Warehouse

Starting with OnCommand Insight 7.1.2, user created custom schemas (MySQL DBs) and tables added to the DWH are backed up and restored.

== Data source enhancements

The following data source changes have been made:

* The XtremIO data source is fully supported for foundation and performance.
* The Dell Compellent data source is fully supported for foundation and performance.
* The EMC Centera data source is fully supported for foundation only.
+
There is no performance package for this data source.

* The Hyper-V data source is fully supported for performance.
+
The data source was fully supported for foundation in an earlier release.

* The Pure Storage data source is fully supported for foundation and performance.
* Red Hat Enterprise Virtualization (REST API) provides beta support for foundation only.
* Amazon AWS S3 provides beta support for foundation only.
* OpenStack (REST API / KVM) provides beta support for foundation and host virtualization performance.

For more information about how to configure data sources, see the _OnCommand Insight Configuration and Administration Guide_.

== Non-NetApp software changes

The following non-NetApp software changes are included in this release:

* Upgrade to Java version 8 update 65
* Upgrade to MySQL Server version 5.5.46
* Upgrade to MySQL Connector/J version 5.1.37

== BMC Connector for OnCommand Insight

The BMC Connector for OnCommand Insight has been upgraded to version 3.2. The BMC Connector software is available for download from the NetApp Support site.

== Corrected issues in OnCommand Insight 7.1.2

OnCommand Insight 7.1.2 corrects issues that you might have encountered in previous releases.

|===
| Issue number| Description| Resolution
a|
ICI-2651
a|
Disabling performance on an HDS data source results in `Error saving data source` error in the webUI.
a|
Insight no longer displays this message and performance is disabled for the device.
a|
ICI-3158
a|
JBoss has a 10GB default upload limit.
a|
The default upload limit for JBoss is increased to 50 GB.
a|
ICI-3129
a|
Annotations for Datastore, VMDK, and Storage Node are not available in the Data Warehouse database.
a|
Missing annotations are now displayed on the annotations page.
a|
ICI-3161
a|
HDS array shows WWPN for port name not the correct display name, such as "`CL1-G`".
a|
The correct port name is now displayed.
a|
ICI-3214
a|
The WebUI System Health event bus monitor displays up to 1000%.
a|
An accurate health status is displayed.
a|
ICI-3326
a|
Add data source report.
a|
The data source report is now available.
a|
ICI-3231
a|
Creating a plan to "`remove volume`" for a volume that is participating in a path does not generate a future violation.
a|
This problem is fixed for new remove volume actions. Existing remove volume actions must be re-created manually.
|===

== Known Issues

Known issues identify some unexpected and potentially undesired behaviors that affect functionality in this OnCommand Insight release. Becoming familiar with these issues helps you to avoid or troubleshoot them.

The Storage Capacity data mart and Storage Capacity fact table (dwh_capacity.capacity_fact) were removed in 7.1. If you have custom reports that use these data marts, the reports do not work after you install this release.

For reports that use the Storage Capacity data mart, you can rewrite the reports to collect data from the following data marts instead:

* You can use the Storage and Storage Pool Capacity data mart for pools (aggregates) or storage array data.
* You can use the Chargeback data mart to associate costs to business entities, applications, or both.
* You can use the Volume Capacity data mart, Inventory data mart, or both to understand which host has access to which volumes.
* You can use the Internal Volume Capacity data mart for information about internal volumes.
* You can use the Inventory data mart if you are interested only in point-in-time data for storage, storage pool, and internal volume metrics.

If you are restoring an Insight database backup copy that was created prior to 7.0, the restore operation takes a long time due to the transitioning of the performance sample data from MySQL into Cassandra.

Insight supports the Java client on Red Hat Enterprise Linux; however, it does not support Open Java Development Kit (OpenJDK). It requires the Oracle JRE. You can obtain the Oracle JRE from the Java website: http://java.com. If you experience problems running the Java UI, such as rendering errors, you should check the browser's file associations. You can set it to open JNLP files by using `javaws.exe` (Oracle's Java Web Start), but not by using IcedTea-Web.

The Java UI might not run with CAC for certain versions of JRE if the *Use TLS 1.2* option is selected in the *Advanced* tab of the Java Control Panel on the client system. You can leave the check boxes selected in the *Advanced* tab that you selected for previous versions of TLS; however, you should ensure that the *Use TLS 1.2* check box is not selected.

The values for max total IOPS and max total Throughput differ between the web UI and the Java UI. In the web UI, the maximum values are calculated from the whole storage. In the Java UI, these values are calculated as the single highest-value volume or internal volume within the given storage.

Some storage pool performance values also differ between the web UI and the Java UI. The web UI shows storage pool IOPS and storage pool Throughput based on the values of metrics on the underlying disks. The Java UI shows these values based on values of the volume or internal volumes on the storage pool.

Beginning in Java 7u40, x.508 certificates with RSA keys with fewer than 1024 bits are not considered secure; to resolve this issue, you should regenerate the x.508 certificate for the vCenter server with stronger keys. For more information about this issue, see the _Update Release Notes_ for Java 7u40.

In 7.0, data source names could include some nonalphanumeric characters (for example, hyphens). For this release, a data source name can include only alphanumeric characters and the underscore character (_). If you edit information for a data source that has a name including a hyphen and attempt to save it, `Data source name contains non-word characters` is displayed. You should remove the unsupported nonalphanumeric character from the data source name and then save it.

OnCommand Insight no longer generates NPV switches and instead makes the end nodes (host, storage, and so on) directly connect to switches through a generated port; therefore, when upgrading to 7.1, you see numerous connectivity changes listed in the Java UIChanges view when the data sources start reporting.

In the summary section of the switch assets page, port channels are incorrectly included in the total number of physical ports.

Java 7 update 75 is not recommended for use with Insight because only critical issues are corrected in the update. Some of the update's noncritical issues that were not fixed might affect the Java UI. Insight does support both Java 8 update 31 and Java 7 update 76, which were released at the same time as Java 7 update 75.

Due to the port performance changes in this release, the following port performance counters in the Java UI do not have values after restoring a backup from an earlier version of Insight or when upgrading an earlier version to 7.1: Transfer Rate, Rx Transfer Rate, and Tx Transfer Rate. These counters show only the new values acquired by 7.1.

When setting up weekly backups for your Insight database, you must ensure that the backup location you choose has write permission for ocisys.

If you are using Internet Explorer, you must set the IE Enhanced Security Configuration to *Off* to avoid this message.

Due to security issues, Insight 7.1.1 now only supports TLSv1.2, eliminating support for TLSv1 and TLSv1.1. In 7.1, the REST API samples are hardcoded for TLSv1.0; therefore, any code written using the samples in 7.1 does not work in 7.1.1. As a workaround, you must limit the protocol to TLSv1.2 in `jbossweb.sar/server.xml`, `cogonos/c10_64/bin64/bootstrap_winx64.xml`, and the REST API samples.

If you are upgrading from 7.0.2 to 7.1.1 and you do not have a C:/ drive, the upgrade fails because Cassandra calls the environment variable, user.home, to generate nodetool output. You should ensure that when Insight calls Cassandra's nodetool, it sets this environment variable.

The workaround is to go to the `SANscreen\cassandra\bin` directory, edit the nodetool.bat script, and change the line where NodeCmd is executed. Following is an example of the original line:

`"%JAVA_HOME%\bin\java" -cp %CASSANDRA_CLASSPATH% -Dlog4j.configuration=log4j-tools.properties org.apache.cassandra.tools.NodeCmd %*`

Using an available drive (for example, X:\ in this example), the line should look like the following after it is modified:

`"%JAVA_HOME%\bin\java" -cp %CASSANDRA_CLASSPATH% -Dlog4j.configuration=log4j-tools.properties-Duser.home=X:\\ org.apache.cassandra.tools.NodeCmd %*`

Avoid using the less-than sign, greater-than sign, semicolon, colon, apostrophe, dollar sign, and ampersand in the Directory Lookup User's password to prevent authentication from failing:

`< > ; : ' $ &`
