---
permalink: dwh/concept_oncommand_insight_data_warehouse_portal.html
sidebar: sidebar
keywords: 
summary: 'The Data Warehouse Portal is a web-based user interface that you use to configure options and set up fixed schedules to retrieve data. From the Data Warehouse Portal, you can also access the OnCommand Insight reporting portal.'
---
= What you can do using the Data Warehouse Portal
:icons: font
:imagesdir: ../media/

[.lead]
The Data Warehouse Portal is a web-based user interface that you use to configure options and set up fixed schedules to retrieve data. From the Data Warehouse Portal, you can also access the OnCommand Insight reporting portal.

Using Data Warehouse portal, you can do the following:

* Access the OnCommand Insight reporting portal to view predesigned reports or to create custom reports using report authoring tools.
* Consolidate multiple OnCommand Insight databases.
* Manage connections to OnCommand Insight servers.
* Check the status of current jobs or queries that are running.
* Schedule Data Warehouse builds.
* Edit the site name.
* View Data Warehouse version and upgrade history, including specific information such as module versions, sites, and licenses.
* Import annotations.
* Configure a build from history.
* View Data Warehouse documentation and the database schema.
* Reset the Data Warehouse database.
* Back up and restore the Data Warehouse database.
* Troubleshoot Data Warehouse issues.
* Manage user accounts.
