---
permalink: dwh/including-the-data-warehouse-database.html
sidebar: sidebar
keywords: 
summary: 'By default, ASUP sends only the Data Warehouse log files to technical support for assistance in troubleshooting; however, you can also choose to include a backup of the Data Warehouse database and select the type of data that is sent.'
---
= Including a backup of the Data Warehouse database
:icons: font
:imagesdir: ../media/

[.lead]
By default, ASUP sends only the Data Warehouse log files to technical support for assistance in troubleshooting; however, you can also choose to include a backup of the Data Warehouse database and select the type of data that is sent.

== Steps

. Log in to the Data Warehouse portal at `+https://hostname/dwh+`, where `hostname` is the name of the system where OnCommand Insight Data Warehouse is installed.
. From the navigation pane on the left, click *Troubleshooting*.
. To specify that ASUP should include a backup of the Data Warehouse database, click the *Include DWH Database Backup* list and select one of the following options for the type of data that the backup should include:
 ** All (including Performance)
 ** All Except Performance
 ** Inventory Only
. Click *Update*.
