---
permalink: dwh/issue-resolution-with-autosupport-asup.html
sidebar: sidebar
keywords: 
summary: 'You can send ASUP logs to technical support for assistance in troubleshooting. ASUP for Data Warehouse is configured to run automatically. In the Data Warehouse Portal, you can disable the automatic send process, choose to include a backup of the Data Warehouse database, or initiate a transmittal to ASUP.'
---
= Issue resolution with ASUP
:icons: font
:imagesdir: ../media/

[.lead]
You can send ASUP logs to technical support for assistance in troubleshooting. ASUP for Data Warehouse is configured to run automatically. In the Data Warehouse Portal, you can disable the automatic send process, choose to include a backup of the Data Warehouse database, or initiate a transmittal to ASUP.

The information in the logs is forwarded to technical support by using HTTPS protocol. No data is forwarded using ASUP unless you first configure it on the Insight Server.

Data Warehouse sends the logs to the OnCommand Insight Server that is the first connector listed in the Data Warehouse Portal Connectors page. The automatic process sends the following files:

* Data Warehouse logs, which includes the following:
 ** boot.log (including backups)
 ** dwh.log (including backups such as dwh.log.1)
 ** dhw_troubleshoot.log
 ** dwh_upgrade.log (including backups)
 ** WildFly.log (including backups)
 ** ldap.log (including backups)
 ** SQL dump of the Data Warehouse management database
 ** mysql: my.cnf, .err and slow query logs
 ** full innodb status
* Cognos logs, which include the following:
 ** cognos-logs.zip
+
Contains the Cognos log files from the `<install>\cognos\c10_64\logs` directory. It also contains the logs generated by Cognos as well as the OnCommand InsightAP.log file that contains all logging from users logging in to and out of OnCommand Insight reporting.

 ** DailyBackup.zip
+
Contains the backup of the reporting artifacts in the Public Folders. The contents of My Folders is not included in this.

 ** cognos_``version``_``site name``_content_store.zip
+
Contains a full backup of the Cognos Content Store.

You can generate a troubleshooting report manually. The Troubleshooting Report .zip file contains the following Data Warehouse information:

* boot.log (including backups)
* dwh.log (including backups such as dwh.log.1)
* dwh_upgrade.log (including backups)
* wildfly.log (including backups)
* ldap.log (including backups)
* dump files in c:\Program Files\SANscreen\wildfly\standalone\log\dwh\
* SQL dump of the Data Warehouse management database
* mysql: my.cnf, .err and slow query logs
* full innodb status

[NOTE]
====
ASUP does not automatically send a backup of the OnCommand Insight database to technical support.
====
