---
permalink: dwh/reporting-user-roles.html
sidebar: sidebar
keywords: 
summary: 'Each user account is assigned a role with a set of permissions. The number of users is limited by the number of Reporting licenses attached to each role.'
---
= Reporting user roles
:icons: font
:imagesdir: ../media/

[.lead]
Each user account is assigned a role with a set of permissions. The number of users is limited by the number of Reporting licenses attached to each role.

Each role can perform the following actions:

* *Recipient*
+
Views OnCommand Insight Reporting portal reports and sets personal preferences such as those for languages and time zones.
+
[NOTE]
====
Recipients cannot create reports, run reports, schedule reports, export reports, nor perform administrative tasks.
====

* *Business Consumer*
+
Runs reports and performs all Recipient options.

* *Business Author*
+
Views scheduled reports, runs reports interactively, creates stories, in addition to performing all Business Consumer options.

* *Pro Author*
+
Creates reports, creates packages and data modules, in addition to performing all Business Author options.

* *Administrator*
+
Performs reporting administrative tasks such as the import and export of report definitions, configuration of reports, configuration of data sources, and the shutdown and restart of reporting tasks.

The following table shows the privileges and the maximum number of users allowed for each role:

|===
| Feature| Recipient| Business Consumer| Business Author| Pro Author| Admin
a|
View reports in the Team Content tab
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Run reports
a|
No
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Schedule reports
a|
No
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Upload external files
a|
No
a|
No
a|
Yes
a|
Yes
a|
No
a|
Create stories
a|
No
a|
No
a|
Yes
a|
Yes
a|
No
a|
Create reports
a|
No
a|
No
a|
Yes
a|
Yes
a|
No
a|
Create Packages and Data Modules
a|
No
a|
No
a|
No
a|
Yes
a|
No
a|
Perform administrative tasks
a|
No
a|
No
a|
No
a|
No
a|
Yes
a|
Number of users
a|
Number of OnCommand Insight users
a|
20
a|
2
a|
1
a|
1
|===
When you add a new Data Warehouse and Reporting user, if you exceed the limit in a role, the user is added as "`deactivated,`" and you need to deactivate or remove another user with that role to give a new user membership.

[NOTE]
====
Report authoring capabilities require Insight Plan license. You can add additional Business Author and Pro Author users by purchasing the ARAP (Additional Report Authoring Package). Contact your OnCommand Insight representative for assistance.
====

These reporting user roles do not affect direct database access. These reporting user roles do not impact your ability to create SQL queries using the data marts.
