---
permalink: dwh/running-external-scripts-in-data-warehouse.html
sidebar: sidebar
keywords: 
summary: 'Data Warehouse allows customers to create jobs that can run custom scripts that prepare customized data in Data Warehouse.'
---
= Running custom scripts in Data Warehouse
:icons: font
:imagesdir: ../media/

[.lead]
Data Warehouse allows customers to create jobs that can run custom scripts that prepare customized data in Data Warehouse.

== Before you begin

To prevent the custom script from being deleted during a Data Warehouse upgrade, you must not store the script in the SANscreen directory.

== About this task

The job can specify only one script. You can run multiple scripts and commands from one script.

== Steps

. In Data Warehouse, select *DWH Admin* > *Schedule*.
. Select the *Script enabled* check box.
. Enter the absolute path of the script name in the *Script Location* text box.
. Click *Save*.

== Results

The Data Warehouse job engine schedules the task to run a "`Custom scripting`" job. The job is scheduled to run after an ETL and avoiding other conflicting background processes. The job is not run by a "`Build from history`" operation.
