---
permalink: dwh/task_viewing_oncommand_insight_logs.html
sidebar: sidebar
keywords: 
summary: 'You can view various Data Warehouse and Cognos logs in OnCommand Insight.'
---
= Viewing OnCommand Insight logs
:icons: font
:imagesdir: ../media/

[.lead]
You can view various Data Warehouse and Cognos logs in OnCommand Insight.

== About this task

You can examine troubleshooting and status information in Cognos and Data Warehouse log files.

== Steps

. Log in to the Data Warehouse portal at `+https://hostname/dwh+`, where `hostname` is the name of the system where OnCommand Insight Data Warehouse is installed.
. In the navigation pane on the left, click *Troubleshooting*.
. In the *Logs* section, click *Log Files*.
+
The following log files are displayed:
+
|===
a|
dwh.log
a|
Lists the status of Data Warehouse jobs
a|
wildfly.log
a|
Provides information about the WildFly application server
a|
dwh_upgrade log
a|
Provides information about the upgrade on Data Warehouse
a|
ldap.log
a|
Logs messages related to LDAP authentication
a|
dwh_troubleshoot.log
a|
Logs messages that can help troubleshooting DWH problems
a|
sanscreenap.log
a|
Provides information about connection to the server, authentication and access to the Cognos repository, and information about other processes
a|
cognosserver.log
a|
Cognos log
|===

. Click on the name of the log file you want to view.
