---
permalink: dwh/task_configuring_a_weekly_scehdule.html
sidebar: sidebar
keywords: 
summary: 'Although you can manually build Data Warehouse by using the Build now control at any time, it is best practice to schedule automatic builds, defining when and how often to build the Data Warehouse database. Data Warehouse performs a build job for each connector and for each data mart. Data Warehouse performs a build job for each connector for licenses and inventory and all other build jobs \(for example, capacity\) are performed on the consolidated database. With a weekly schedule, you can specify the time you want the build to run for each day of the week.'
---
= Configuring a weekly schedule
:icons: font
:imagesdir: ../media/

[.lead]
Although you can manually build Data Warehouse by using the Build now control at any time, it is best practice to schedule automatic builds, defining when and how often to build the Data Warehouse database. Data Warehouse performs a build job for each connector and for each data mart. Data Warehouse performs a build job for each connector for licenses and inventory and all other build jobs (for example, capacity) are performed on the consolidated database. With a weekly schedule, you can specify the time you want the build to run for each day of the week.

== Steps

. Log in to the Data Warehouse Portal at `+https://hostname/dwh+`, where `hostname` is the name of the system where OnCommand Insight Data Warehouse is installed.
. From the navigation pane on the left, click *Edit Schedule*.
. Choose the frequency - weekly.
. Choose the time of day for each day you want the job to run.
. Chose N/A for days you do not want to run the build.
. To enable the schedule, select *Enabled*.
+
[NOTE]
====
If you do not check this, the schedule build does not occur.
====

. Click *Save*.
. To build Data Warehouse outside of the automatic scheduled build, click *Build now*.
