---
permalink: dwh/task_getting_started_with_data_warehouse.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight Data Warehouse enables you to configure options needed before generating reports that include your data. Data Warehouse contains many features; however, you need to use only a few of them to get started. To set up Data Warehouse, you use options in the Data Warehouse Portal.'
---
= Getting started with Data Warehouse
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight Data Warehouse enables you to configure options needed before generating reports that include your data. Data Warehouse contains many features; however, you need to use only a few of them to get started. To set up Data Warehouse, you use options in the Data Warehouse Portal.

== About this task

To set up OnCommand Insight Data Warehouse, a storage administrator should complete the following procedures:

* Accessing the Data Warehouse portal
* Connecting Data Warehouse to OnCommand Insight servers
* Building the database from history
* Setting up backup and restore processes

Additionally, a storage administrator might want to complete the following procedures.

* Accessing MySQL using the command line interface
* Scheduling daily builds
* Setting up multiple tenancy in reporting
* Troubleshooting setup issues
 ** Why can't I see my annotations?
 ** What should I do with failing historical build points?

If this is the first time you are using the Data Warehouse Portal, you must set up Data Warehouse before any information can appear on the Jobs page. You also need to repeat this setup process after resetting the Data Warehouse database.
