---
permalink: dwh/task_backing_up_the_data_warehouse_database.html
sidebar: sidebar
keywords: 
summary: 'You can back up the Data Warehouse database, which also includes a Cognos backup, to a file and later restore it using the Data Warehouse portal. Such a backup enables you to migrate to a different Data Warehouse server or upgrade to a new Data Warehouse version.'
---
= Backing up the Data Warehouse database
:icons: font
:imagesdir: ../media/

[.lead]
You can back up the Data Warehouse database, which also includes a Cognos backup, to a file and later restore it using the Data Warehouse portal. Such a backup enables you to migrate to a different Data Warehouse server or upgrade to a new Data Warehouse version.

== Steps

. Log in to the Data Warehouse Portal at `+https://fqdn/dwh+`.
. From the navigation pane on the left, select *Backup/Restore*.
. Click *Backup* and select your backup configuration:
 .. All Datamarts except Performance Datamart
 .. All Datamarts

+
This operation can take 30 minutes or more.
+
Data Warehouse creates a backup file and displays its name.
. Right-click the backup file and save it to a location you want.
+
You might not want to change the file name; however, you should store the file outside the Data Warehouse installation path.
+
The Data Warehouse backup file includes the DWH instance's MySQL; custom schemas (MySQL DBs) and tables; LDAP configuration; the data sources that connect Cognos to the MySQL database (not the data sources that connect the Insight server to devices to acquire data); import and export tasks that imported or exported reports; reporting security roles, groups, and namespaces; user accounts; any modified Reporting Portal reports; and any custom reports, regardless of where they are stored, even in the My Folders directory. Cognos system configuration parameters, such as SMTP server setting, and Cognos custom memory settings are not backed up.
+
The default schemas where custom tables are backed up include the following:
+
|===
a|
dwh_capacity
a|
dwh_capacity_staging
a|
dwh_dimensions
a|
dwh_fs_util
a|
dwh_inventory
a|
dwh_inventory_staging
a|
dwh_inventory_transient
a|
dwh_management
a|
dwh_performance
a|
dwh_performance_staging
a|
dwh_ports
a|
dwh_reports
a|
dwh_sa_staging
a|
 
a|
 
a|
 
|===
Schemas where custom tables are excluded from backup include the following:
+
|===
a|
information_schema
a|
acquisition
a|
cloud_model
a|
host_data
a|
innodb
a|
inventory
a|
inventory_private
a|
inventory_time
a|
logs
a|
management
a|
mysql
a|
nas
a|
performance
a|
performance_schema
a|
performance_views
a|
sanscreen
a|
scrub
a|
serviceassurance
a|
test
a|
tmp
a|
workbench
a|
 
a|
 
a|
 
|===
In any backup initiated manually, a `.zip` file is created that contains these files:

 ** A daily backup `.zip` file, which contains Cognos report definitions
 ** A reports backup `.zip` file, which contains all the reports in Cognos, including those in the My Folders directory
 ** A Data Warehouse database backup file
In addition to manual backups, which you can perform at any time, Cognos creates a daily backup (automatically generated each day to a file called `DailyBackup.zip`) that includes the report definitions. The daily backup includes the top folders and packages shipped with the product. The My Folders directory and any directories that you create outside the product's top folders are not included in the Cognos backup.

+
[NOTE]
====
Due to the way Insight names the files in the `.zip` file, some unzip programs show that the file is empty when opened. As long as the `.zip` file has a size greater than 0 and does not end with a `.bad` extension, the `.zip` file is valid. You can open the file with another unzip program like 7-Zip or WinZip®.
====
