---
permalink: dwh/task_sending_oncommand_insight_logs_to_asup.html
sidebar: sidebar
keywords: 
summary: 'You can send ASUP logs to technical support for assistance in troubleshooting. ASUP for Data Warehouse is configured to run automatically. In the Data Warehouse portal, you can disable the automatic send process, choose to include a backup of the Data Warehouse database, or initiate a transmittal to ASUP. When you request an ASUP report, the report request appears as a job in the Data Warehouse portal Jobs page.'
---
= Sending Insight logs to ASUP
:icons: font
:imagesdir: ../media/

[.lead]
You can send ASUP logs to technical support for assistance in troubleshooting. ASUP for Data Warehouse is configured to run automatically. In the Data Warehouse portal, you can disable the automatic send process, choose to include a backup of the Data Warehouse database, or initiate a transmittal to ASUP. When you request an ASUP report, the report request appears as a job in the Data Warehouse portal Jobs page.

== About this task

The job is managed by the job queue similar to the processing of other jobs. If an ASUP job is in a Pending or Running state already, an error message appears indicating that the ASUP report request cannot be added to the job request, because the job queue contains pending or running requests.

== Steps

. Log in to the Data Warehouse portal at `+https://hostname/dwh+`, where `hostname` is the name of the system where OnCommand Insight Data Warehouse is installed.
. From the navigation pane on the left, click *Troubleshooting*.
. In the *OnCommand Insight ASUP* section of the *Troubleshooting* page, click *Download DWH Troubleshooting Report* to retrieve the troubleshooting report.
. To send the report to the OnCommand Insight Server listed as the first connector in the Data Warehouse Portal *Connectors* page, click *Send Now*.
