---
permalink: dwh/task_resetting_the_data_warehouse_database.html
sidebar: sidebar
keywords: 
summary: 'You can delete the contents of the Data Warehouse data marts and delete all configured connectors. You might want to do this if an installation or upgrade did not complete successfully and it left the Data Warehouse database in an intermediate state. You can also delete only the Inventory data model or the Cognos Reporting data model.'
---
= Resetting the Data Warehouse database or Reporting server
:icons: font
:imagesdir: ../media/

[.lead]
You can delete the contents of the Data Warehouse data marts and delete all configured connectors. You might want to do this if an installation or upgrade did not complete successfully and it left the Data Warehouse database in an intermediate state. You can also delete only the Inventory data model or the Cognos Reporting data model.

== Steps

. Log in to the Data Warehouse Portal at `+https://hostname/dwh+`, where `hostname` is the name of the system where OnCommand Insight Data Warehouse is installed.
. From the navigation pane on the left, click *Reset DWH database*.
. Click one of the following options:
 ** *Reset DWH Database*
+
This deletes the contents of all Data Warehouse data marts and all configured connectors and places the Data Warehouse to the default installed state without any custom configurations. You might choose this option, for example, if you changed your connected servers, but restored a different Data Warehouse database accidentally on your server and need to return to a default installed state. This does not delete any reports. (Reports are saved in the Cognos Content Store.)

 ** *Reset Inventory Only*
+
This deletes the contents of the Inventory data model only. This does not delete any historical data.

 ** *Reset Reporting Content*
+
This resets the content of the reporting server. This deletes any custom reports you may have. Backup your reports before you choose this option.

+
A warning message displays.
. To continue, click *Yes*.
