---
permalink: howto/analyzing-your-infrastructure.html
sidebar: sidebar
keywords: 
summary: 'The procedures in this topic are ones that you might use to perform an analysis of parts of the infrastructure in your environment. The steps, views, and data you gather in this exercise use virtual computing objects as an example. Analysis of other assets in your environment will follow similar steps using relevant counters for each specific asset. The intent of this exercise is to familiarize you with the variety of options Insight offers to monitor and understand the characteristics of the assets in your data center.'
---
= Analyzing your infrastructure
:icons: font
:imagesdir: ../media/

[.lead]
The procedures in this topic are ones that you might use to perform an analysis of parts of the infrastructure in your environment. The steps, views, and data you gather in this exercise use virtual computing objects as an example. Analysis of other assets in your environment will follow similar steps using relevant counters for each specific asset. The intent of this exercise is to familiarize you with the variety of options Insight offers to monitor and understand the characteristics of the assets in your data center.

== About this task

Some of the actions you can take to analyze the state of your infrastructure might include the following:

* Observe an objects's behavior over time
* Compare an object's metrics against the metrics of the top 10 like objects
* Compare numbers for objects
* Compare the top 10 objects against the average
* Compare metrics A vs. B for many objects to show categories and anomalies
* Compare a range of objects against other objects
* Use an expression to display metrics not available in the web UI

You can create all of these views of objects in your infrastructure in a dashboard using widgets for each analysis you perform. The dashboards can be saved to provide quick access to current data on your infrastructure.
