---
permalink: howto/concept_how_to_trobleshootfibre_channel_bb_credit_0_errors.html
sidebar: sidebar
keywords: 
summary: 'Fibre Channel uses buffer-to-buffer credits \(BB credits\) to control transmission flow. The credit value is decremented when a frame is sent from a port and the credit value is replenished when the port receives a response. If the BB credits in the port are not replenished, the transmission flow can be impacted. Ports need memory, or buffers, to temporarily store frames until they are assembled in sequence, and delivered. The number of buffers is the number of frames a port can store and is called a Buffer Credit.'
---
= Troubleshooting Fibre Channel BB credit 0 errors
:icons: font
:imagesdir: ../media/

[.lead]
Fibre Channel uses buffer-to-buffer credits (BB credits) to control transmission flow. The credit value is decremented when a frame is sent from a port and the credit value is replenished when the port receives a response. If the BB credits in the port are not replenished, the transmission flow can be impacted. Ports need memory, or buffers, to temporarily store frames until they are assembled in sequence, and delivered. The number of buffers is the number of frames a port can store and is called a Buffer Credit.

As the available credits for a given port approach zero, an error warns that the port will stop receiving transmissions when zero is reached and will not resume until the BB credits are replenished.

Insight performance policies allow you to set thresholds on the following port metrics.

|===
a|
BB credit zero - Rx
a|
Number of times the receive buffer-to-buffer credit count transitioned to zero during the sampling period
a|
BB credit zero - Tx
a|
Number of times the transmit buffer-to-buffer credit count transitioned to zero during the sampling period
a|
BB credit zero - Total
a|
Number of times this port had to stop transmitting because the attached port was out of credits to provide
a|
BB credit zero duration - Tx
a|
Time in milliseconds during which the Tx BB credit was zero during the sampling interval
|===
BB Credit errors might be caused by some of the following scenarios:

* If a given implementation has a high percentage of FC frames of sizes significantly less than the maximum size, then more BB_Credits might be required.
* Workload changes to your environment that could be impacting ports or devices that are connected to them, such as storage nodes.

You can use the fabric, switch, and port asset pages to monitor your Fibre Channel environment. Port asset pages present summary information about the resource, its topology (the device and its connections), performance charts, and tables of associated resources. When troubleshooting Fibre Channel issues the performance chart for each port asset is helpful because it shows traffic for the selected top contributor port. Port asset pages also show buffer-to-buffer credit metrics and port errors in this chart, with Insight displaying a separate performance chart for each metric.
