---
permalink: howto/concept_service_level_and_environment.html
sidebar: sidebar
keywords: 
summary: 'Add Service Level and Environment annotations to the appropriate assets using the steps and concepts you’ve learned.'
---
= Service Level and Environment annotations
:icons: font
:imagesdir: ../media/

[.lead]
Add Service Level and Environment annotations to the appropriate assets using the steps and concepts you've learned.

To add Service Level and Environment annotations to the appropriate assets in your environment, follow the steps noted above, choosing the desired assets and appropriate Service Level or Environment annotations. You can have multiple annotations associated with the same assets, and in fact this practice will allow you greater flexibility in managing your environment through Insight.

Now that you have created queries to annotate your assets, you can use these annotations in many different ways, such as:

* Performance policies to alert you when events occur on desired assets
* Custom dashboards and widgets to monitor activity
* Reporting
