---
permalink: howto/concept_custom_dashboards.html
sidebar: sidebar
keywords: 
summary: 'OnCommand Insight 7.3 includes enhanced custom dashboard capabilities to give users an operational view of the data that is important to them and provide a single-stop view of that data.'
---
= Creating custom dashboards
:icons: font
:imagesdir: ../media/

[.lead]
OnCommand Insight 7.3 includes enhanced custom dashboard capabilities to give users an operational view of the data that is important to them and provide a single-stop view of that data.

OnCommand Insight provides users the flexibility to create operational views infrastructure data across IT platforms, by allowing you to create custom dashboards with a variety of widgets, each of which provides extensive flexibility in displaying and charting your data. In this How-To, we will create an example dashboard to highlight VM Performance.

This How-To should serve as an example only and does not cover every possible scenario. The concepts and steps herein can be used to create your own custom dashboards to highlight the data specific to your particular needs.

*Overview*

You create a custom dashboard by either of the following methods:

* *Dashboards* > *+New dashboard*
* *Dashboards* > *Show all dashboards* and click *+Add*

The New Dashboard screen has several controls:

* *Time selector*: allows you to view dashboard data for a range of time from 3 hours up to 90 days by use of the custom date range selector. You can choose to override this global time range in individual widgets.
* *Edit* button: Selecting "`On`" will enable Edit mode, which allows you to make changes to the dashboard. New dashboards open in Edit mode by default.
* *Save* button: Allows you to save, rename or delete the dashboard.
* *Variable* button: Variables can be added to dashboards. Changing the variable updates all of your widgets at once. For more information on variables, see link:concept_custom_dashboard_concepts.md#[Custom Dashboard concepts]
* *Widget* button, which allows you to add any number of tables, charts, or other widgets to the dashboard.

Widgets can be resized and relocated to different positions within the dashboard, to give you the best view of your data according to your current needs.

*Widget types*

You can choose from the following widget types:

*Table* widget: A table displaying data according to filters and columns you choose. Table data can be combined in groups that can be collapsed and expanded.

*Line, Spline, Area, Stacked Area* charts: These are time-series chart widgets on which you can display performance and other data over time.

*Single value* widget: A widget allowing you to display a single value that can be derived either directly from a counter or calculated using a query or expression. For example, you can display the sum of total IOPS for all storage in your environment as a single value at the top of your dashboard.

*Bar* chart: A chart to display top or bottom 5, 10, 20, or 50 values.

*Box Plot* chart: A plot of the min, max, median, and the range between lower and upper quartile of data in a single chart.

*Scatter Plot* chart: Plots related data as points, for example, IOPS and latency. In this example, you would quickly see assets with high latency and low IOPS.

Additionally, there are a number of legacy widgets that you can choose. In the *Widgets* drop-down, select **Show more...**to see these widgets.
