---
permalink: howto/creating-policies-and-thresholds-for-storage-pools.html
sidebar: sidebar
keywords: 
summary: 'You can create performance policies that trigger alerts to notify you when thresholds for Storage Pool assets have been exceeded.'
---
= Creating performance policies for Storage Pools
:icons: font
:imagesdir: ../media/

[.lead]
You can create performance policies that trigger alerts to notify you when thresholds for Storage Pool assets have been exceeded.

== Before you begin

This procedure assumes that you have thin provisioned the storage pool.

== About this task

You want to create policies that monitor and report changes in a storage pool that could contribute to outages. For the thin provisioned physical storage pool, you want to monitor the physical capacity and monitor the Overcommit Ratio.

== Steps

. Open OnCommand Insight in your browser.
. Select *Manage* > *Performance Policies*
+
The Performance Policies page is displayed. Policies are organized by object, and are evaluated in the order in which they appear in the list. If notifications are enabled (*Admin* > *Notifications*), you can configure Insight to send email when performance policies are breached.

. Click **+Add**to create a new policy.
. In *Policy Name* enter a policy name for the Storage Pool.
. In *Apply to objects of type* select Storage Pool.
. In *Apply after window of* enter First occurrence.
. In *With severity* enter Critical
. Configure the Email recipients that you want notified when thresholds are breached.
+
By default, email alerts on policy violations are sent to the recipients in the global email list. You can override these settings so that alerts for a particular policy are sent to specific recipients.
+
Click the link to open the recipients list, then click the + button to add recipients. Violation alerts for this policy will be sent to all recipients in the list.

. In *Create alert if any of the following are true* enter Capacity ratio - Used > 85%

== Results

This configuration results in the system sending a critical warning message when more than 85% of the physical capacity of the storage pool is used. Using 100% of the physical memory will result in application failure.

== Create additional Storage Pool policies

=== About this task

Create an additional "`Capacity ratio - Used`" policy that raises a warning message when the Storage Pool capacity used exceeds 75%. If notifications are enabled (*Admin* > *Notifications*), you can configure Insight to send email when performance policies are breached.
