---
permalink: howto/custom-dashboard-top-bottom-results.html
sidebar: sidebar
keywords: 
summary: 'In a chart widget on a custom dashboard, you can show either the Top or Bottom results for rolled up data, and choose the number of results shown. In a table widget, you can select the number of rows displayed and sort by any column.'
---
= Showing top/bottom results in dashboard widgets
:icons: font
:imagesdir: ../media/

[.lead]
In a chart widget on a custom dashboard, you can show either the Top or Bottom results for rolled up data, and choose the number of results shown. In a table widget, you can select the number of rows displayed and sort by any column.

== Chart widget top/bottom

In a chart widget, when you choose to rollup data by a specific attribute, you have the option of viewing either the top N or bottom N results. Note that you cannot choose the top or bottom results when you choose to rollup by _all_ attributes.

You can choose which results to display by choosing either *Top* or *Bottom* in the query's *Show* field, and selecting a value from the list provided.

== Table widget show entries

In a table widget, you can select the number of results shown in the table results. You can choose from 5, 10, 20, or 50 results. You are not given the option to choose top or bottom results because the table allows you to sort ascending or descending by any column on demand.

You can choose the number of results to show in the table on the dashboard by selecting a value from the query's *Show entries* field.

Note that the more results you choose to display, the taller your widget will be when you save it to the dashboard. You will not be able to resize the widget smaller than the number of rows displayed.
