---
permalink: howto/custom-dashboard-roll-up.html
sidebar: sidebar
keywords: 
summary: 'Data displayed in dashboard widgets is rolled up from acquired data points, allowing flexibility and conciseness in your dashboards.'
---
= Roll up and Aggregation
:icons: font
:imagesdir: ../media/

[.lead]
Data displayed in dashboard widgets is rolled up from acquired data points, allowing flexibility and conciseness in your dashboards.

Data displayed in each widget is rolled up from the underlying data points collected during acquisition. For example, if you have a line chart widget showing Storage IOPS over time, you might want to see a separate line for each of your data centers, for a quick comparison. You can choose to roll up this data in one of several ways:

* *Avg*: displays each line as the _average_ of the underlying data.
* *Max*: displays each line as the _maximum_ of the underlying data.
* *Min*: displays each line as the _minimum_ of the underlying data.
* *Sum*: displays each line as the _sum_ of the underlying data.

To do this, in your widget's query, first choose an asset type (for example, _Storage_) and metric (such as __IOPS - Tota__l). For *Roll up*, choose a rollup method (such as _Avg_) and select an attribute or annotation by which to roll up the data (for example, _Data Center_). The widget updates automatically and shows a line for each of your data centers.

You can also choose to roll up _all_ of the underlying data into the chart or table. In this case, you will get a single line for each query in the widget, which will show the average, min, max or sum of the chosen metric for all of the underlying assets.

If you have set a filter for the query, the data that is rolled up is based on the filtered data.

Note that when you choose to roll up a widget by any field (for example, _Model_), you will still need to *Filter by* that field in order to properly display the data for that field properly on the chart or table.

*Aggregating data:* You can further align your time-series charts (line, area, etc.) by aggregating data points into minute, hour, or day buckets before that data is subsequently rolled up by attribute (if chosen). You can choose to aggregate data points according to their Avg, Max, Min, or Sum, or by the Last data point collected during the chosen interval. To choose an aggregation method, click on *More options* in the widget's query section.

The minimum allowed interval is ten minutes. A small interval combined with a long time range may result in a "Aggregation interval resulted in too many data points." warning. You might see this if you have a small interval and increase the dashboard time frame to 7 days. In this case, Insight will temporarily increase the aggregation interval to 1 hour until you select a smaller time frame.

You can also aggregate data in bar chart widget and single-value widget.

Most asset counters aggregate to _Avg_ by default. Some counters aggregate to _Max_, _Min_, or _Sum_ by default. For example, port errors aggregate to _Sum_ by default, where storage IOPS aggregate to _Avg_.
