---
permalink: howto/preparation-and-prerequisites-for-servicenow-integration.html
sidebar: sidebar
keywords: 
summary: 'The necessary preparations and prerequisites must be satisfied for ServiceNow, Insight, and the Python middleware connector prior to integration.'
---
= Preparation and prerequisites for Service Now integration
:icons: font
:imagesdir: ../media/

[.lead]
The necessary preparations and prerequisites must be satisfied for ServiceNow, Insight, and the Python middleware connector prior to integration.

== Recommended workflow

The following workflow is strongly recommended when integrating ServiceNow with Insight:

. Deploy the Python middleware connector in your development instance first.
. Once you have confirmed all faults have been identified and corrected in your development instance, deploy the connector in your test/stage instance.
. Once you have confirmed correct operation in your staging instance, deploy the connector in your production instance.

If problems are found during any of these stages, follow your rollback steps and disable the connector, then troubleshoot the problem and re-deploy.

== General prerequisites:

* You can use either a standalone host or VM (recommended) or the Insight server host/VM to host the python middleware connector.
* It is highly recommended to backup the production Insight server and deploy it on a development instance.
* ServiceNow must be accurately discovering servers in the CMDB.
* Insight must be accurately discovering your storage and compute environments.
* Port 443 and 80 to the Insight Server and ServiceNow Instance.

== ServiceNow prerequisites:

* It is highly recommended to use a development/test instance.
* Permission to load ServiceNow update sets.
* Permission to create users.
* ServiceNow version Jakarta or later

== Insight prerequisites:

* It is highly recommended to use a development/test instance.
* Permission to create users (Admin permissions).
* Insight version 7.3.1 or later is supported, but to get the most out of Insight, use the latest version.

== Python middleware connector prerequisites:

* Python version 3.6 or greater installed.
* When installing Python, check the box to enable all users. This sets Python for standard application install locations.
* When installing Python, check the box to enable the installer to update the path. Otherwise, you will have to update the path manually.
* Download the Python *pysnow* and *requests* libraries.
