---
permalink: howto/servicenow-integration-install-python-and-libraries.html
sidebar: sidebar
keywords: 
summary: 'Python can be installed on the Insight server or on a standalone host or VM.'
---
= Install Python and libraries
:icons: font
:imagesdir: ../media/

[.lead]
Python can be installed on the Insight server or on a standalone host or VM.

== Steps

. On your VM or host, download Python 3.6 or later.
. Choose custom installation and choose the following options. These are either necessary for proper connector script operation or are highly recommended.
 ** Install launcher for all users
 ** Add Python to the PATH
 ** Install pip (which allows Python to install other packages)
 ** Install tk/tcl and IDLE
 ** Install the Python test suite
 ** Install py launcher for all users
 ** Associate files with Python
 ** Create shortcuts for installed applications
 ** Add python to environment variables
 ** Precompile standard library
. After Python is installed, install the "`requests`" and "`psnow`" Python libraries. Run the following command: `python -m pip install requests pysnow`
+
*NOTE:* This command might fail when you are operating in a proxy environment. To work around this issue, you need to manually download each one of the Python Libraries and run the install requests one by one and in the correct order.
+
The command will install several files.

. Verify the Python libraries are installed correctly. Start Python using one of the following methods:
 ** Open a cmd prompt and type `python`
 ** On Windows, open *Start* and choose *Python* > *python-<version>.exe*
. At the Python prompt, type `modules`
+
Python will ask you to wait a moment while it gathers a list of modules, which it will then display.
