---
permalink: howto/task_servicenow_integration_scheduling_daily_sync.html
sidebar: sidebar
keywords: 
summary: 'You can use the Windows task scheduler to automatically sync the ServiceNow connector.'
---
= Scheduling synchronization to occur daily
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Windows task scheduler to automatically sync the ServiceNow connector.

== About this task

Automatic synchronization ensures that Insight data is regularly moved to ServiceNow. You can use any method for scheduling. The following steps use the Windows task scheduler to accomplish automatic syncing.

== Steps

. On the Windows screen, click *Start* and enter *run* > *task scheduler*.
. Click *Create Basic Task...*
. Enter a meaningful name, such as "`OCI2SNOW Connector Sync`". Enter a description of the task. Click *Next*.
. Select to run the task *Daily*. Click *Next*.
. Choose a time of day to run the task. Click *Next*.
. For Action, select *Start a program*. Click *Next*.
. In the *Program/script* field, enter `C:\OCI2SNOW\oci_snow_sync_pyz`. In the *Arguments* field, enter `sync`. In the *Start in* field, enter `C:\OCI2SNOW`. Click *next*.
. Review the Summary details, and click *Finish*.
+
The synchronization is now scheduled to run daily.
