---
permalink: howto/task_configuring_the_aws_cloud_cost_data_source.html
sidebar: sidebar
keywords: 
summary: 'You configure the AWS Cloud Cost data source as you would for any Insight data source.'
---
= Configuring the AWS Cloud Cost data source
:icons: font
:imagesdir: ../media/

[.lead]
You configure the AWS Cloud Cost data source as you would for any Insight data source.

== Before you begin

You must have your Amazon AWS account already set up and prepared for Insight data collection, and have the following pieces of information at hand.

* Report Name
* S3 Bucket Name
* AWS Region where your S3 bucket resides.
* Report path prefix

== About this task

Once your AWS account is ready and has the proper permissions set, you are ready to configure OnCommand Insight to collect billing report data.

[NOTE]
====
You will need to add a separate AWS Cloud Cost data source for each billable user/account from which you wish to retrieve billing data.
====

== Steps

. Log in to OnCommand Insight as an administrator.
. Click on *Admin* > *Data sources* to open the Insight Data Source page.
. Click *+Add* to add a new data source. Choose *Amazon* and select *AWS Cloud Cost*.
. In the *Configuration* section, fill in the _Report name_, _S3 Bucket_ name, _S3 Region_ (must be the region where your S3 bucket resides), _Report path prefix_, _AWS IAM Access Key ID_, and _AWS IAM Secret Access Key_. If you are unsure of any of these, check with your cloud provider or AWS account holder.
. Click the checkbox to verify your understanding that AWS will bill you for API requests and data transfers made by the Insight data source.
. In *Advanced Configuration*, enter the HTTP connection and socket timeout. The default is 300 seconds.
. Click *Save*.
