---
permalink: howto/task_defining_applications_how_to_chargeback.html
sidebar: sidebar
keywords: 
summary: 'If you want to track cost data associated with specific applications running in your environment, you first need to define the applications.'
---
= Defining applications for use with chargeback
:icons: font
:imagesdir: ../media/

[.lead]
If you want to track cost data associated with specific applications running in your environment, you first need to define the applications.

== Before you begin

If you want to associate application with a business entity, you must have already created the business entity.

[NOTE]
====
This example does not associate any application with business entities.
====

== Steps

. Log in to the OnCommand Insight web UI.
. Click *Manage* > *Application*
+
After you define an application, the Applications page displays the application's name, its priority, and, if applicable, the business entity associated with the application.

. Click**Add**
+
The Add Application dialog box displays.

. Enter a unique name for the application in the Name box. Enter the Applications identified in the Report: African Tours, APAC Commercial Sales, and so on.
. Click *Priority* and select the priority (critical, high, medium, or low) for the application in your environment.
. If you plan to use this application with a business entity, click *Business entity* and select the entity from the list.
. You will not use volume sharing, click to clear the *Validate* volume sharing box.
. Click *Save*.
+
The applications appears in the Applications page. If you click the application's name, Insight displays the asset page for the application. After defining an application, you can go to an asset page for host, virtual machine, volume, internal volume, or hypervisor to assign an application to an asset.
