---
permalink: howto/task_create_an_annotation_rule_to_automate_excluding_specific_aggregates_from_your_query.html
sidebar: sidebar
keywords: 
summary: 'As an alternative to manually applying annotations to individual assets, you can automatically apply annotations to multiple assets using annotation rules. Annotation rules are based on queries you create and when run on the system they add new assets to existing sets of assets. When these sets of assets are excluded from a report the new assets are automatically excluded too.'
---
= Create an annotation rule to automate excluding specific aggregates from your I/O density report
:icons: font
:imagesdir: ../media/

[.lead]
As an alternative to manually applying annotations to individual assets, you can automatically apply annotations to multiple assets using annotation rules. Annotation rules are based on queries you create and when run on the system they add new assets to existing sets of assets. When these sets of assets are excluded from a report the new assets are automatically excluded too.

== Before you begin

You must have created and saved a query that identifies the NetApp root aggregates you identified in your environment.

== Steps

. Log in to the OnCommand Insight web UI.
. Click *Manage* > *Annotation rules*
. Click *Add*
+
The Add Rule dialog box displays.

. Do the following:
 .. In the Name box, enter a unique name that describes the rule: "`RootAggrExclude`"
 .. Click Query and select the Query that Insight should use to apply the annotation rule to:"` Aggregate0`"
 .. Click Annotation and select: "`Root agg exclude`"
 .. Click Value and enter True
