---
permalink: howto/using-performance-policies-to-reduce-risk-in-thin-provisioning.html
sidebar: sidebar
keywords: 
summary: 'You should create performance policies to raise alerts when thresholds in your virtual infrastructure have been breached. The alerts allow you to respond to changes in your environment before they cause interruptions or outages in operations.'
---
= Using performance policies to reduce risk in thin provisioning
:icons: font
:imagesdir: ../media/

[.lead]
You should create performance policies to raise alerts when thresholds in your virtual infrastructure have been breached. The alerts allow you to respond to changes in your environment before they cause interruptions or outages in operations.

Policies that help in monitoring the virtual infrastructure include the following:

* *Datastore*
+
You could use the following policies on the Datastore:

 ** Capacity ratio - Overcommit
 ** Capacity ratio - Used
 ** Capacity - Used
 ** Capacity - Total

* *Storage pool*
+
The following policies can protect against storage related capacity outages in thin provisioned environments:

 ** Capacity provisioned
 ** Capacity used
 ** Capacity ratio - Overcommit
 ** Capacity ratio - Used

You can expand from these policies to monitor capacity in the virtual infrastructure, including:

* Internal volumes
* LUNs
* Disks
* VMDKs
* VMs

You can configure policies using annotations. You assign the same annotation to the specific assets that support an application. For example, you can assign annotations to the Datastores and the Storage pools of a thin provisioned application. You might have annotations named Production for the production environment, Development for the development environment, and so on. You can change the thresholds and criticality of warnings depending on the type of application the assets are supporting. For example, a breach of a threshold for a production application's DataStore might raise a _critical warning_, while the same breach for a development environment might only raise a _warning_. Incorporating annotations within defined policies can help to further reduce unwanted alerting noise for non-critical assets.
