name: Jekyll Catalyst

on: [push]

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  FRAMEWORK_BRANCH: main
  
jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: "Repository Checkout"
        uses: actions/checkout@v2

      - name: "Ruby Configuration"
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: false
          
          
      - name: "Framework Checkout"
        uses: actions/checkout@v2
        with:
          repository: 'NetAppDocOps/jekyll-catalyst'
          token: ${{ env.GH_TOKEN }}
          path: dependencies/jekyll-catalyst
          ref: ${{ env.FRAMEWORK_BRANCH }}
      
      - name: "Before install"
        shell: bash
        run: |
          sudo apt-get update
          gem update --system 3.3.5 && gem install bundler -v 2.3.5
          
      - name: "Install and Test"
        shell: bash
        run: |
          cd dependencies/jekyll-catalyst
          bundle _2.3.5_ install --jobs=3 --retry=3
          bundle exec rake install:local
          cd -
          
      - name: "Script"
        shell: bash
        run:  catalsyt-hashmap -a
